### ISSUE TITLE
enabled_methods not excluding 'put' operations

### ISSUE THREAD

**Issue by nijsure25** [marcgibbons/django-rest-swagger#108]
I have following SWAGGER_SETTINGS, which reading the documentation should exclude the put, patch operation from my setting, but I still see them in documentation generated by swagger.
SWAGGER_SETTINGS = {
    "exclude_namespaces": ["deskstop_interface"], # List URL namespaces to ignore
    "api_version": '1',  # Specify your API's version
    "api_path": "/api/",  # Specify the path to your API not a root level
    "enabled_methods": [
        'get',
        'post',
        'delete',
    ],
    "api_key": '', # An API key
    "is_authenticated": False,  # Set to True to enforce user authentication,
    "is_superuser": False,  # Set to True to enforce admin only access
}

See this url - http://i.imgur.com/GvgzJ5t.png

![swagger-bug](https://cloud.githubusercontent.com/assets/7637963/4002901/66554060-2971-11e4-8fef-27bdb25f09f6.png)

What I am doing wrong that is causing PATCH and PUT operations to show up.

-Subodh

**Comment by edmorley** [comment]
So this is different to #73.

The enabled_methods django-rest-swagger setting (which itself sets the supportedSubmitMethods setting passed to swagger-ui) isn't supposed to hide non-specified methods from the swagger UI.

Instead, it's only supposed to hide the "try it now" button (albeit this is broken, which is #73).

That said, the variable name (enabled_methods) and docs are not overly clear, so it's not surprising that there was confusion. I think we should rename the setting and tweak the docs.
