### ISSUE TITLE
Question: How to set Data Type when using custom parameters in the docstring?

### ISSUE THREAD

**Issue by WillHaack** [marcgibbons/django-rest-swagger#114]
I know I can add custom parameters by doing

'''
my_parameter -- My parameter's description.
'''

My question is - what is the syntax for being able to fill the data_type column?

**Comment by ankitml** [comment]
Is the status same? Possible to edit Data_type without worrying about a serializer?

**Comment by kakulukia** [comment]
its possible for a long time now .. the ticket should be closed by @WillHaack

**Comment by ankitml** [comment]
How to do it? Documentation seems a bit elusive on this.

**Comment by kakulukia** [comment]
http://django-rest-swagger.readthedocs.org/en/latest/yaml.html#parameters

**Comment by ankitml** [comment]
Right, this works well for basic types, but not very well for describing a  clickable JSON type schema.

**Comment by kakulukia** [comment]
okay, sorry .. cant help u there ..
i didnt need that before

**Comment by ankitml** [comment]
Yeah, this can be closed. I think this need can be removed by creating serializer classes just for swagger works. Although this is a bit unpythonic because there is much magic in pulling swagger meta types from only serializers and not explicit but it works.
