### ISSUE TITLE
Support for reStructuredText in docstrings

### ISSUE THREAD

**Issue by jonancm** [marcgibbons/django-rest-swagger#126]
Given that reStructuredText (reST) is the *de facto* standard for writing Python documentation (since [docutils](http://docutils.sourceforge.net/) and [Sphinx](http://sphinx-doc.org/) require its usage), it would be nice to have support for reST in docstrings, along with the already available support for Markdown.

Surely Markdown is more readable and its syntax is easier to remember, but reST is more versatile for the documentation of Python modules and is mandatory if you want to use tools as Sphinx.

Having your API documented with Swagger is nice for the end user of the API, but the Markdown-only docstrings prevent you from generating beautiful documentation with docutils and Sphinx.

With reST support in django-rest-swagger, you could have both Swagger documentation and Python/Sphinx documentation, which would be desirable for many software projects.

**Comment by cpbotha** [comment]
Would it not be a better option here to make use of DRF's existing VIEW_DESCRIPTION_FUNCTION setting, see http://www.django-rest-framework.org/api-guide/settings/#view_description_function ?

This function is used by the DRF to extract the docstring from the view class, and turn it into HTML. By default this is Markdown, but users can easily configure it to use reStructuredText see http://www.django-rest-framework.org/api-guide/settings/#view_description_function

django-rest-swagger would only need to use the already configured DRF VIEW_DESCRIPTION_FUNCTION, and whatever the user has configured in the DRF would then also work for django-rest-swagger.

**Comment by ariovistus** [comment]
hmm. drs is already using view_description_function in some places, looks like it should be using it in a few more..

I'll have a look at this tonight.

**Comment by ariovistus** [comment]
@cpbotha thanks for the suggestion; this worked out pretty well.

django-rest-swagger has reStructuredText support now, appropriate docs are at 

http://django-rest-swagger.readthedocs.org/en/latest/misc.html

which just says set VIEW_DESCRIPTION_FUNCTION to something that outputs reST.

**Comment by cpbotha** [comment]
Awesome, thank you!

**Comment by slora** [comment]
Hi guys,

I have the same issue with the following docstring:

Retrieves the data of a particular :class:`models.Product`.

I'm getting the following text rendered in the web docs:
Retrieves the data of a particular :class:`models System Message: WARNING/2 (string, line 1); backlink Inline interpreted text or phrase reference start-string without end-string.

I've already set up VIEW_DESCRIPTION_FUNCTION as mentioned in the docs. These are some of the packages I've installed in my virtualenv:

PyYAML==3.11
docutils==0.12
django-rest-swagger==0.2.9

I've tried with :py:class:`models.Product` as well, but it's failing too. 

Could you please give me a hand with this?

Thanks in advance!
