### ISSUE TITLE
Swagger POSTs with Content-Type application/x-www-form-urlencoded instead of application/json

### ISSUE THREAD

**Issue by visionscaper** [marcgibbons/django-rest-swagger#131]
Hello,

I'm using Swagger UI in combination with the Django REST framework. All my end points, including the parameter (types), get listed correctly. However, when I tried to post to an endpoint, Swagger POSTs the request with Content-Type application/x-www-form-urlencoded instead of application/json which is required for my REST API.

How can I let Swagger know to use the application/json instead of application/x-www-form-urlencoded?
Just like in the Django REST Browsable API, I was expecting to be able to set the raw JSON for the request body myself, but I can't...

**Comment by ariovistus** [comment]
is this a dup of #50?

**Comment by ariovistus** [comment]
I think it is
