### ISSUE TITLE
Multiple Separate Doc Urls?

### ISSUE THREAD

**Issue by sherzberg** [marcgibbons/django-rest-swagger#141]
I'd like to have two sets of swagger docs at different urls. Something like admin apis and user apis with completely separate doc urls. Basically just two different sets of root urls for each doc set. Would this be easy to do currently?

**Comment by mverteuil** [comment]
There's now `resource_access_handler` which I have used to provide various supersets of my documentation to differently authorized parties. This should solve your problem.

**Comment by marcgibbons** [comment]
It is now possible to expose multiple schema views in v2 w/ DRF 3.4,
