### ISSUE TITLE
Hide unwanted not allowed_methods

### ISSUE THREAD

**Issue by psychok7** [marcgibbons/django-rest-swagger#142]
I there guys, is it possible for me to specifically hide the methods that are not in my `allowed_methods` list `for EACH` ViewSet?

What i mean is if i have `allowed_methods = ['get']` i only want the documentation to show me the GET for that Viewset and not for all of the viewsets.

Cheers

**Comment by AndresOsinski** [comment]
@ariovistus I have a patch coming up for explicitly including and excluding URL names and namespaces. Interested?

**Comment by ariovistus** [comment]
if it has docs and tests, sure

**Comment by sosoriov** [comment]
@ariovistus @AndresOsinski  anything about this? 
I'm using
django-rest-swagger==0.3.2
djangorestframework==3.1.3

and still have the same problem.

thanks
