### ISSUE TITLE
api_key not being sent

### ISSUE THREAD

**Issue by hugomn** [marcgibbons/django-rest-swagger#173]
Looks like dummy, but I could not figure out how to send api_key parameter in the sandbox. I've tried to set the 'api_key' property in the config, or setting it in the top field, with no luck. Am I missing something?

Thanks!

**Comment by kibernick** [comment]
As far as I could figure it out, the "api_key" gets sent in the Authorization header, in the following format, depending on your 'token_type' value, in the SWAGGER_SETTINGS:

Authorization: {token_type} {api_key}

e.g. for OAuth2, it would be:
Authorization: Bearer {api_key}

**Comment by marcgibbons** [comment]
Fixed in v2
