### ISSUE TITLE
Incorrect yaml docs rendering.

### ISSUE THREAD

**Issue by peterVorman** [marcgibbons/django-rest-swagger#190]
Not trimmed yaml docs from endpoint description.
Only in version 0.2.8
http://screencast.com/t/L8sdsfoC

**Comment by ariovistus** [comment]
code please? I did change the parsing slightly from any '-------' as separator to only 3 dashes, but there were probably some paths I didn't test

**Comment by peterVorman** [comment]
class Company(CompanyAPIView):
    def post(self, request, company_id):
        """
        Creates or updates a company
        ---
        type:
          key_fields:
            required: true
            type: list
          correlations_rules:
            required: false
            type: list
        parameters_strategy: merge
        parameters:
            - name: company_id
              description: Identity Service organization ID
              required: true
              type: string
              paramType: path
            - name: company
              paramType: body
              type: json
        responseMessages:
            - code: 200
              message: '{"status": "ok", "company_id": "id"}'
            - code: 400
              message: '{"status": "error",  "error_description": "description", "error": "type"}'
        """
        return Response(data={"company_id": company.id, "status": "ok"}, status=HTTP_200_OK)

**Comment by peterVorman** [comment]
Parser works well in version 0.2.7

**Comment by ariovistus** [comment]
That looks like the one case I didn't test :)

**Comment by ariovistus** [comment]
CompanyAPIView extends APIView?

**Comment by peterVorman** [comment]
yes

**Comment by ariovistus** [comment]
hmm. I can't seem to duplicate this. I guess what version of python and DRF?

**Comment by peterVorman** [comment]
python 2.7
DRF 2.3.13

**Comment by peterVorman** [comment]
Django 1.6.5

**Comment by ariovistus** [comment]
does your code have \r newlines in it by any chance?

**Comment by peterVorman** [comment]
I use a windows environment for developing and it is default settings for it.
But code is executing on ubuntu machine. Maybe it is affecting rendering.

**Comment by AndresOsinski** [comment]
I'm having the same issue. Running django-rest-swagger==0.2.8

**Comment by ariovistus** [comment]
well, the current problem is I can't seem to duplicate it, so can you get me access to some code where it is happening? maybe set up something in vagrant cloud or docker hub?

**Comment by AndresOsinski** [comment]
I've debugged the issue to this point, in introspectors.py:113

```
description = strip_tags(get_view_description(
    callback, html=True, docstring=docstring)) \
    .split("\n")[0].split(".")[0]
return description
```

So the variables as they're comming look like the following:

```
docstring -> u'My comment\n---\nomit_serializer: true'
get_view_description(callback=callback, html=True, docstring=docstring) -> u'My comment<br />---<br />omit_serializer: true'
strip_tags(get_view_description(...)) -> u'My comment---omit_serializer: true'

It would appear that get_view_description transforms newlines into '<br />' tags, and strip_tags removes them without substituting for newlines again.

A solution would be to put either html=False, or add a conditional on strip_tags() so to turn br's into newlines. I'm willing to submit a pull request; tell me which you'd prefer.

**Comment by ariovistus** [comment]
html=False would be appropriate.

can you include a backtrace from that point? I'm just curious.

**Comment by AndresOsinski** [comment]
Here you go

```
  /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/django/views/generic/base.py(68)view()
     66             self.args = args
     67             self.kwargs = kwargs
---> 68             return self.dispatch(request, *args, **kwargs)
     69 
     70         # take name and docstring from class

  /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/rest_framework/views.py(404)dispatch()
    402                 handler = self.http_method_not_allowed
    403 
--> 404             response = handler(request, *args, **kwargs)
    405 
    406         except Exception as exc:

  /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/rest_framework_swagger/views.py(133)get()
    131             'basePath': self.api_full_uri.rstrip('/'),
    132             'resourcePath': '/' + path,
--> 133             'apis': generator.generate(apis),
    134             'models': generator.get_models(apis),
    135         })

  /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py(32)generate()
     30                 'description': IntrospectorHelper.get_summary(api['callback']),
     31                 'path': api['path'],
---> 32                 'operations': self.get_operations(api, apis),
     33             })
     34 

  /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py(75)get_operations()
     73             operation = {
     74                 'method': method_introspector.get_http_method(),
---> 75                 'summary': method_introspector.get_summary(),
     76                 'nickname': method_introspector.get_nickname(),
     77                 'notes': method_introspector.get_notes(),

  /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py(233)get_summary()
    231         return IntrospectorHelper.get_summary(
    232             self.callback,
--> 233             self.get_docs() or self.parent.get_description())
    234 
    235     def get_nickname(self):

> /home/osinski/Projects/feastly/env/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py(110)get_summary()
    108         """
    109         from ipdb import set_trace; set_trace()
--> 110         description = strip_tags(get_view_description(
    111             callback, html=True, docstring=docstring)) \
    112             .split("\n")[0].split(".")[0]
```

**Comment by ariovistus** [comment]
what version of Markdown do you have?

**Comment by ariovistus** [comment]
Oh my gosh I just realized the op's pic shows the overflow happening on the summary and not the main doc element. boy am I dense. So I'm guessing you have a different version of markdown than me which is replacing the newlines. Please tell me which version you have so we can capture this in travis. fix coming.

**Comment by ariovistus** [comment]
can you see if my PR fixes this?

**Comment by AndresOsinski** [comment]
It omits the parsing of the remainder, but if there's not text above the '---' it will use that as the summary.

**Comment by ariovistus** [comment]
better?

**Comment by AndresOsinski** [comment]
It's better, yes.

**Comment by AndresOsinski** [comment]
Can I submit another patch to omit the --- line if no comments exist above?

**Comment by ariovistus** [comment]
I changed my PR to do that

**Comment by ariovistus** [comment]
nag: what version of Markdown do you have?

pip freeze | grep Markdown

**Comment by eillarra** [comment]
This is not a real issue, but it is somehow related, so here it goes:
Why is a `<br/>` always added at the beginning of a note?

**Comment by ariovistus** [comment]
are you looking at code that does this, or the html that drs is pumping out?

**Comment by eillarra** [comment]
Just looking at the generated JSON with the apis. It is adding a line break at the beginning of the note.
```
...
notes: " <br/>Test.",
...
```
with `django-rest-swagger==0.2.9`

**Comment by ariovistus** [comment]
Then I would guess either markdown is doing something goofy or whatever builds notes isn't stripping newlines.

**Comment by ariovistus** [comment]
looks like it is the latter, but my version of markdown seems to be wrapping things in <p>, so stripping newlines doesn't make much of a difference.

**Comment by ariovistus** [comment]
oh well. can't hurt.

**Comment by eillarra** [comment]
Markdown is not activated.
Replacing [this line (L505)](https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/introspectors.py#L505) with this should make the trick:
```
return docstring.strip().replace("\n\n", "<br/>")
```

**Comment by ariovistus** [comment]
#247 should fix this

**Comment by eillarra** [comment]
Both solutions seem to work, yes.

**Comment by jonzlin95** [comment]
I'm a bit late to this, and not sure if this is what you mean, but I think another fix is to simply put a period at the end of the first sentence.
