### ISSUE TITLE
problem of using swagger when I use the get_serializer_class() for dynamic serializer based on the URL's charges

### ISSUE THREAD

**Issue by gufeisun** [marcgibbons/django-rest-swagger#194]
I am using django-rest-swagger for api doc generation. I would like to return different user the different part of models. So I used the `get_serializer_class()` function to use different serializer for different users by checking the `kwargs['pk']` on the url.

The `urls.py` is:

    url(r'^api/users/$', views.UserEnum.as_view()),
    url(r'^api/users/(?P<pk>[0-9]+)/$', views.UserDetail.as_view()),

The view that I am using is:

    #List all the users or create a new user
    class UserEnum(generics.ListCreateAPIView):
        queryset = User.objects.all()
        serializer_class = UserSerializer
        permission_classes = (IsAuthenticated, IsAdminUser,)
    
    class UserDetail(generics.RetrieveUpdateDestroyAPIView):
        queryset = User.objects.all()
        #serializer_class = UserSerializer #TODO: Problem with Swagger
        permission_classes = (IsAuthenticated, IsOwnerAdminOrReadOnly,)
    
        def get_serializer_class(self):
            #swagger crash here.
            user_id = int(self.kwargs['pk'])
            if self.request.user.id == user_id or self.request.user.is_superuser:
                serializer_class = UserSerializer
            else:
                serializer_class = UserProfileSerializer
            return serializer_class
    
        def get_object(self, *args, **kwargs):
            user_id = int(self.kwargs['pk'])
    
            if self.request.user.id == user_id or self.request.user.is_superuser:
                return User.objects.get(id=user_id)
            else:
                return UserProfile.objects.get(user=user_id)

**The above two urls work successfully without problems.** But when I type the `http://127.0.0.1:8000/api/` for generate api docs, it return the below error:

    `Unable to read api 'users' from path http://127.0.0.1:8000/api/api-docs/api/users (server returned Internal Server Error)`

    File "/Users/Scofield/anaconda/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py" in ask_for_serializer_class
      179.                 return view.get_serializer_class()
    File "/Users/Scofield/Dropbox/My Projects/Angels&Demons/src/doWishSites/doWishCore/views.py" in get_serializer_class
      27.         user_id = int(self.kwargs['pk'])

    Exception Type: KeyError at /api/api-docs/api/users
    Exception Value: 'pk'

**Comment by ariovistus** [comment]
hmm. looks like drs might be able to have enough smarts to inject 'pk' into kwargs. Not sure what you would expect to see, though, since I don't think swagger supports the notion of different models based on input.

view_mocker ought to be a suitable workaround: http://django-rest-swagger.readthedocs.org/en/latest/yaml.html#view-mocker

**Comment by f0ysal** [comment]
@gufeisun Is it fixed yet? I am still finding this bug. django-rest-swagger is always expecting a model or serializers but there are situations like util APIs which is not for any specific model or serializers.

**Comment by gufeisun** [comment]
Not yet, @f0ysal , I'm still suffering from this problem. Maybe it's a functional missing of django-rest-swagger .

**Comment by mcgeeco** [comment]
I'm having a different but, I think, linked problem. One of my views calls a get_serializer_class based on the request.query_params. The DRS use the django httprequest objects instead of Rest Framework Request objects for some reason, so I get an attribute error.
I can get around it with a try/except in the get_serializer_class method, but that's not ideal. 
The mock view thing in the documentation doesn't work for me at all. Is it outdated or something? The mock view function gets called but it doesn't seem to have any affect on the request that gets sent to the get_serializer_class method.

**Comment by ariovistus** [comment]
it might be at this point if you're using DRF 3.1. Haven't had a chance to play with that yet

**Comment by mcgeeco** [comment]
No just 3.0.5. Maybe something else was messing with it.

**Comment by ariovistus** [comment]
well, that's peculiar. The request object passed to view_mocker isn't the same object passed to get_serializer_class?

**Comment by mcgeeco** [comment]
No they both received the same request object. If I copy the exact example in the docs, I get:
AttributeError: 'HttpRequest' object has no attribute 'tacos'
It's really confusing though. I put a print statement in 'if self.request.tacos' in get_serializer_class, and if I make one call to /docs/api-docs/files, which is the call that causes the problem, I get the print output four times and the error twice.

**Comment by ariovistus** [comment]
Is the AttributeError happening in view_mocker, or get_serializer_class?

**Comment by mcgeeco** [comment]
In get_serializer_class.

**Comment by mcgeeco** [comment]
I'll be back in work tomorrow, I can show you the code then, if you like.

**Comment by mcgeeco** [comment]
Sorry for the wait, and thanks for the help.

So if this is part of my views.py: https://gist.github.com/mcgeeco/a7a915792cff6fcb80e6
If I do a runserver and go to /docs/api-docs/files, I get the attribute error for tacos, and in the terminal I see:

This is the viewmocker, just changed view.request.tacos to Hi
This is the get_serializer_class method, self.request.tacos is Hi
This is the viewmocker, just changed view.request.tacos to Hi
This is the get_serializer_class method, self.request.tacos is Hi
This is the viewmocker, just changed view.request.tacos to Hi
This is the get_serializer_class method, self.request.tacos is Hi
This is the viewmocker, just changed view.request.tacos to Hi
This is the get_serializer_class method, self.request.tacos is Hi
-------------------------------------------------------
(2015-03-18 18:06:59; base.py:231) 
ERROR:django.request: Internal Server Error: /docs/api-docs/files
Traceback (most recent call last):
...
  File ".../views.py", line 94, in get_serializer_class
    print "This is the get_serializer_class method, self.request.tacos is %s" % self.request.tacos
AttributeError: 'HttpRequest' object has no attribute 'tacos'
-------------------------------------------------------
(2015-03-18 18:06:59; base.py:231) 
ERROR:django.request: Internal Server Error: /docs/api-docs/files
Traceback (most recent call last):
...
  File ".../views.py", line 94, in get_serializer_class
    print "This is the get_serializer_class method, self.request.tacos is %s" % self.request.tacos
AttributeError: 'HttpRequest' object has no attribute 'tacos'
[18/Mar/2015 18:06:59] "GET /docs/api-docs/files HTTP/1.1" 500 171711


My current workaround is a try/except in get_serializer_class, but I'm not crazy about that...

**Comment by ariovistus** [comment]
could you get me a stacktrace for that exception? It looks like there is some path that isn't using the view_mocker, which is probably a bug.

**Comment by mcgeeco** [comment]
Sorry, left it out for brevity. Here it is in full:

ERROR:django.request: Internal Server Error: /docs/api-docs/files
Traceback (most recent call last):
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 104, in get_response
    response = middleware_method(request, callback, callback_args, callback_kwargs)
  File "/home/conor/workspace/api/...api/...middleware/middlewares.py", line 27, in process_view
    response = view_func(request, *view_args, **view_kwargs)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework/views.py", line 407, in dispatch
    response = self.handle_exception(exc)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework/views.py", line 404, in dispatch
    response = handler(request, *args, **kwargs)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/views.py", line 134, in get
    'models': generator.get_models(apis),
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 104, in get_models
    serializers = self._get_serializer_set(apis)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 222, in _get_serializer_set
    serializer = self._get_method_serializer(method_introspector)
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/docgenerator.py", line 165, in _get_method_serializer
    serializer = method_inspector.get_response_serializer_class()
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 218, in get_response_serializer_class
    serializer = self.get_serializer_class()
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 211, in get_serializer_class
    serializer = self.ask_for_serializer_class()
  File "/home/conor/.virtualenvs/<env>/local/lib/python2.7/site-packages/rest_framework_swagger/introspectors.py", line 194, in ask_for_serializer_class
    return view.get_serializer_class()
  File "/home/conor/workspace/api/<env>/filesystem/views.py", line 94, in get_serializer_class
    print "This is the get_serializer_class method, self.request.tacos is %s" % self.request.tacos
AttributeError: 'HttpRequest' object has no attribute 'tacos'

I get two of those. Thanks again!

**Comment by ariovistus** [comment]
Diagnosis: it's happening on the OPTIONS method. Solution: TBD

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema.
