### ISSUE TITLE
Question: Custom page for the documentation generated

### ISSUE THREAD

**Issue by GerardPaligot** [marcgibbons/django-rest-swagger#195]
Hi all,

Sorry if this question has been already asked but I didn't find my answer.

I'll integrate django-rest-swagger for a french open-source project and we would like to know if it is possible to customize the documentation generated with the CSS of the open-source project?

Thanks in advance for your answer!

**Comment by ariovistus** [comment]
according to http://stackoverflow.com/questions/7819730/override-specific-admin-css-files-in-django, you should be able to copy rest_framework_swagger/templates/rest_framework_swagger/index.html to your template dir and change it to point to your css.

**Comment by GerardPaligot** [comment]
Thanks @ariovistus. Through my research and your answer, we have succeeded to customize the documentation generated.

I close this issue. :)
