### ISSUE TITLE
Method description not being parsed

### ISSUE THREAD

**Issue by viperfx** [marcgibbons/django-rest-swagger#196]
Hi all,

I am running into an issue with the YAML docstrings where the method docstrings are not being shown in the UI. Here is some sample code so you can see what I trying to do. 

```
class OCILoginViewSet(viewsets.ViewSet):

    """
    Login resource.
    ---
    AuthLoginRequest:
        omit_serializer: true
        type:
            cookie:
                type: string
                required: true
            sessionId:
                type: string
                required: true
        parameters:
            - name: userId
              required: true
              type: string
            - name: password
              type: string
              required: true
    """

    @list_route(methods=['post'])
    def AuthLoginRequest(self, request):
        """
        Method description here
        """
        ...
        return Response(response)
```

The `Login resource` appears to be getting parsed and is being displayed on the UI as the description for all endpoints under this class. I am trying to also add the method description which should appear under the class description. However, the method docstring does not appear to be getting parsed and shown in the UI.

Here are my package versions

```
Django==1.7.3
PyYAML==3.11
django-rest-swagger==0.2.8
djangorestframework==3.0.3
```

Thanks

**Comment by AndresOsinski** [comment]
I'm having a similar issue under a similar format scheme and the same installed software.

**Comment by ariovistus** [comment]
does it work with django-rest-swagger==0.2.7 ?

**Comment by viperfx** [comment]
@ariovistus No it does not.

**Comment by soulseekah** [comment]
This happens only if your method is not lowercased. Camelcase methods do not work because of this line:

https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/introspectors.py#L332

You cannot use uppercases because methods in Python are case-sensitive.

**Comment by soulseekah** [comment]
Good discussions on case conventions here:

http://stackoverflow.com/questions/778203/are-there-any-naming-convention-guidelines-for-rest-apis
