### ISSUE TITLE
How to add array parameters type support in docstring?

### ISSUE THREAD

**Issue by n37r06u3** [marcgibbons/django-rest-swagger#204]
```
parameters:
- name: images
  description: pics
  required: true
  type: array
```

? it seems not work

**Comment by dsteinberger** [comment]
Yes I have the same problem when I sended post request with an array parameter like this: `"hello", "bye"` or `hello,bye`. Swagger always send like one parameter, it do not undestand that its a list ?
Or perhaps I sent it in bad format ? 
I have a `SlugRelatedField` with `many=True` and I need to rewrite for this field in docstring view for that field be an array type... but still doesn't work

**Comment by marcgibbons** [comment]
Closing, YAML is now deprecated
