### ISSUE TITLE
Documenting a method for multiple HTTP methods.

### ISSUE THREAD

**Issue by kjagiello** [marcgibbons/django-rest-swagger#214]
Let's say that I have following method and I want to write different documentations for GET and POST:
```python
class MovieViewSet(ViewSet):
    @detail_route(methods=['get', 'post'])
    def comments(self, request, pk, *args, **kwargs):
        """
        ???
        """
        if request.method == 'POST':
            # create a comment for given movie
        else:
            # list comments for given movie
```
I did some digging around the source code, but it does not like it is currently supported. I am keen to implement this, but I just want to double-check with you first and make sure that there really is no solution to this problem.

**Comment by ariovistus** [comment]
Go for it! I vote for embedding it in the yaml. wonder how that'll work with reST..

**Comment by daonb** [comment]
I need it too. Any progrees?

**Comment by kjagiello** [comment]
No progress on this one. I've started digging around in the code and it looks like this change would require quite a lot of work.

**Comment by monk8800** [comment]
This feature would definitely be nice, just ran into this issue looking for a solution.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.
