### ISSUE TITLE
Query parameter not accessible within the 'create' function of ModelViewSet.

### ISSUE THREAD

**Issue by harisibrahimkv** [marcgibbons/django-rest-swagger#216]
I defined two query parameters as follows on a ViewSet.

    class StreamViewSet(viewsets.ModelViewSet):
        """
        Returns Stream list and details.
    
        brand_id -- ID of the brand
        stream_name -- Name of the stream
        hashtags -- List of hashtags
        """
All the three parameters were listed on the swagger UI. However, the entered values do not seem to be within request.POST or request.DATA.

    def create(self, request, *args, **kwargs):
        brand_id = request.POST.get('brand_id', None)
        stream_name = request.POST.get('stream_name', None)
        hashtags = request.POST.get('hashtags', None)

All of them are none, including args and kwargs.

Doesn't the swagger UI allow passing in of query parameters?

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema.
