### ISSUE TITLE
No real documentation

### ISSUE THREAD

**Issue by AncientSwordRage** [marcgibbons/django-rest-swagger#219]
The closest I found to a read me is [here](https://github.com/marcgibbons/django-rest-swagger/blob/master/docs/source/index.rst) ?

Where am I supposed to look for a guide to installing and using this?

**Comment by ariovistus** [comment]
there is a readthedocs site: http://django-rest-swagger.readthedocs.org/en/latest/
there is an example project in the tests directory

**Comment by AncientSwordRage** [comment]
@ariovistus would it be worth putting that in the read me...near the top?

**Comment by AncientSwordRage** [comment]
@ariovistus  Also, there's no installation process documented. I typed `pip install rest_framework_swagger` and it barfed. Every other RTFD style documentation has loads more on how to install etc. Nothing is explained for someone who's never used Swagger.

You have to realise that this might be something you find easy, but for a novice, it's not something I can do easily without hand-holding. Without that I don't see the point in install this.

**Comment by ariovistus** [comment]
In the readme, there are badges that link to readthedocs and pypi.
Try ```pip install django-rest-swagger```, then the instructions on the main readthedocs page, and see if that gets you going.

**Comment by AncientSwordRage** [comment]
@ariovistus I tried to follow the quick start and copy and pasted in the  Swagger Settings, but it looks like Swagger is still trying to fetch my 'resource list'.

**Comment by ariovistus** [comment]
that doesn't sound familiar

**Comment by cancan101** [comment]
In my first pass through the README, I also did not notice the link to the RTD site. I tend to glaze over the badges on GH.

**Comment by igorpejic** [comment]
In the README, there is a badge and a link to [readthedocs](http://django-rest-swagger.readthedocs.org/en/latest/).
