### ISSUE TITLE
Documentation not available via HTTPS

### ISSUE THREAD

**Issue by GerardPaligot** [marcgibbons/django-rest-swagger#220]
Hi,

I developed an API for an open source project with Django Rest Framework and I used Django Rest Swagger to generate the documentation of this API. Everything is fine in HTTP but our website is available in HTTPS (and redirect in this protocol automatically) and Swagger doesn't seem to like HTTPS.

There is a solution for that or this is a bug in Django Rest Swagger?

Thanks in advance for your answer!

PS : You can find our documentation generated by Swagger [here](https://zestedesavoir.com/api/).

**Comment by ariovistus** [comment]
#215 deals with this sort of thing, but I don't know if it will handle both. If not, it can probably be modified to exclude the protocol ('//zestedesavoir.com/api/api-docs/' uses whichever protocol the page it is on uses).

**Comment by danigosa** [comment]
I was having the same problem and then I add this in settings:

    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')  # Needed to get     request.is_secure() == True

From documentation: https://docs.djangoproject.com/en/1.8/ref/settings/#secure-proxy-ssl-header

This is working if your web server is forwarding x_forwarded_proto, on nginx add this to your location within server config:

    proxy_set_header  X-Forwarded-Protocol  $scheme;

It works both with 0.2.8 and 0.2.9 without having to patch it or without the need of this PR.

**Comment by jebsky** [comment]
this solution is not workin for me

**Comment by CodyMorris** [comment]
Not working for me either, and its been reopened here:
https://github.com/marcgibbons/django-rest-swagger/issues/363
