### ISSUE TITLE
actually requires django-rest-framework 2.4.0

### ISSUE THREAD

**Issue by fleur** [marcgibbons/django-rest-swagger#221]
Hey there.  FYI.  Django-rest-swagger uses the django-rest-framework's default setting of VIEW_DESCRIPTION_FUNCTION which didn't get put in django-rest-framework until 2.4.0.

**Comment by ariovistus** [comment]
whoops, thanks

**Comment by ariovistus** [comment]
wait, if that's the case, why isn't the build with drf 2.3.8 screaming at me?

**Comment by ariovistus** [comment]
definitely fails with drf 2.3.7. would you be terribly upset if we just officially dropped support for >2.3.8?

**Comment by fleur** [comment]
Because VIEW_DESCRIPTION_FUNCTION first made it into 2.3.8, not 2.4.0.  My mistake.  2.3.8 is what it actually requires.  There must be a better way to link to this, but I don't know it. https://github.com/tomchristie/django-rest-framework/commit/d07dae6e79d53fdcfc7d88e085fe7e6da97c9c74#diff-f9716c39348a77db61afdaa2ed35cd87
Also the commit right after this one sets a default for it.

**Comment by fleur** [comment]
What I figured was the only thing that would change is the version in the README, which might save someone else a few hours.  So no, I wouldn't be terribly upset. Thanks.
