### ISSUE TITLE
Swagger is always expecting model or serializers

### ISSUE THREAD

**Issue by FoysalOsmany** [marcgibbons/django-rest-swagger#222]
There are scenarios like utility APIs which do not need any Model or Serializers. I tried to put those namespace in exclude_namespaces but sill does not work.

![image](https://cloud.githubusercontent.com/assets/1332990/6430224/d1d34af8-c02a-11e4-909e-55cadd861df8.png)

**Comment by ariovistus** [comment]
There's a parameter in the yaml ```omit_serializer: true```. Does that fix this for you?

**Comment by f0ysal** [comment]
@ariovistus This does not help in my end. The problem the doc generator method executing all the APIs and later its excluding from exclude_namespace.

**Comment by f0ysal** [comment]
I have fixed the issue in this pull request: https://github.com/marcgibbons/django-rest-swagger/pull/231

Usage Example:

SWAGGER_SETTINGS = {
    'exclude_namespaces': ['price_apis', 'shopping_cart_apis'],
    'exclude_endpoints': [
        '/api/price-calculator/',
        '/api/transfer-cart/{user_from}/{user_to}/',
        '/api/variant/{variant_pk}/total-stock/'
    ],
    'api_version': '1.0',
    "enabled_methods": [  # Methods to enable in UI
        'get',
        'post',
        'put',
        'patch',
        'delete'
    ],
    'is_authenticated': True,
    'is_superuser': False,
    'permission_denied_handler': 'bases.handlers.permission_denied_handler',
    'doc_expansion': 'none',
}

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema.
