### ISSUE TITLE
Exception using ModelViewSet + paginate_by attribute

### ISSUE THREAD

**Issue by viniciuschiele** [marcgibbons/django-rest-swagger#232]
Hi,

I have a view which does not work when it uses paginate_by attribute.

```python
class ProductView(viewsets.ModelViewSet):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer
    paginate_by = 100
```

Exception: 'ProductView' object has no attribute 'page_kwarg'

if I remove paginate_by attribute everything works well.

I am using django rest framework 3

Thanks

**Comment by lukas-hetzenecker** [comment]
django-rest-swagger seems to be incompatible with the recently released django-rest-framework 3.1 (there were major changes in the pagination API)

**Comment by snanda85** [comment]
+1

**Comment by monyiliev** [comment]
+1 
I could also confirm this. 
Python 2.7.6
Django REST framework 3.1.1
django-rest-swagger 0.2.9

**Comment by fanshuai** [comment]
My project update django-rest-swagger==0.3.2 and django==1.8.3, the issue is resolved.
