### ISSUE TITLE
Instructions to run the tests

### ISSUE THREAD

**Issue by duduklein** [marcgibbons/django-rest-swagger#235]
I tried to run the "cigar" tests, but it failed with the error that it could not import "rest_framework_swagger". The problem is that the main directory (which contains the "rest_framework_swagger" is not included in the python path.

I could get around this problem by simply creating a simlink (ln -s ../../rest_framework_swagger), but I'm not sure this is the best way to proceed.

I did not find instructions to run the tests anywhere.
Can you point to some direction please. I would like to test a bugfix that I'm submitting.

Thanks in advance

**Comment by ariovistus** [comment]
usually what I do is ```pip install -e django-rest-swagger```, where django-rest-swagger is the top-level directory of this repo.

**Comment by duduklein** [comment]
Thanks. This is an option, but still does not work out of the box.
What do you think of adding a line `sys.path.append("../../")` to the manage.py files of each example?
This way, running `./manage.py shell` or `./manage.py runserver`would just work.

**Comment by ariovistus** [comment]
I'll accept a pull request
