### ISSUE TITLE
Unable to display serializers.fields on swagger docs

### ISSUE THREAD

**Issue by abdulwahid24** [marcgibbons/django-rest-swagger#238]
Hi,

I am using https://pypi.python.org/pypi/django-rest-authemail for basic email based authentication. 
While creating swagger docs its working fine with all api which I have created using django models but django-rest-authemail module uses serializers.fields for Login Serializer i.e.

```
class LoginSerializer(serializers.Serializer):
    email = serializers.EmailField(max_length=255)
    password = serializers.CharField(max_length=128)
```

Hence django-rest-swagger is unable to recognize these fields and failed to load into api docs.
I have attached the picture for reference.
![loginswagger](https://cloud.githubusercontent.com/assets/4718496/6707648/ec1cb630-cd8e-11e4-8880-8932d9029740.png)

Thanks,
AbdulWahid

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.
