### ISSUE TITLE
Method-level documentation

### ISSUE THREAD

**Issue by wolever** [marcgibbons/django-rest-swagger#24]
Currently DRF only allows documentation at the class level, but it would be nice to take advantage of Swagger's ability to document at the method/action level (ie, so "GET /users", "GET /users/{id}/friends", and "DELETE /users" can all have separate documentation). Are there any plans for this? Would it be considered?

**Comment by kjagiello** [comment]
Let's say that I have following method and I want to write different documentations for GET and POST. Is it supported?
```python
class MovieViewSet(ViewSet):
    @detail_route(methods=['get', 'post'])
    def comments(self, request, pk, *args, **kwargs):
        """
        ???
        """
        if request.method == 'POST':
            # create a comment for given movie
        else:
            # list comments for given movie
```

**Comment by ariovistus** [comment]
I don't think so. feel free to open a new issue.

**Comment by kjagiello** [comment]
Done: #214
