### ISSUE TITLE
Django 1.8 Support

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#249]
First step would be to add 1.8 to tox build and see what breaks.

**Comment by guizhenwei** [comment]
I got this after using with Django 1.8.1:


```
C:\Python27\lib\site-packages\rest_framework_swagger\urlparser.py:4: RemovedInDjango19Warning: django.utils.importlib will be removed in Django 1.9.
  from django.utils.importlib import import_module
```

It would be nice to have Django 1.8.x support, since it is a LTS version.

**Comment by marcwebbie** [comment]
No problem here running on an UAT environment. 

setup:

`Python 3.4.3`, `Django 1.8.1`, `Rest Framework 3.1.1` and `Swagger 0.2.9`

**Comment by ariovistus** [comment]
I think #246 addressed this.

**Comment by blueyed** [comment]
Yes, this appears to has been addressed, and the issue should be closed.
