### ISSUE TITLE
Management Command

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#251]
A management command that will spit out the swagger spec JSON. That way I don't need to have Django serve up the swagger content; rather I can statically generate API docs using something like [swagger-codegen](https://github.com/swagger-api/swagger-codegen).

**Comment by pennomi** [comment]
I would also be interested in this feature.

**Comment by marcgibbons** [comment]
In V2, it is possible to render the spec without the UI. Also check out coreapi for a CLI. To get a dump of the spec, using CURL is probably easy enough to use rather than creating a util.

**Comment by cancan101** [comment]
Can you clarify on how to dump out the swagger doc programmatically without needing to spin up a server and then curl?

**Comment by omidraha** [comment]
@cancan101 , @marcgibbons 
Is there any example for Generate PDF from Swagger API documentation?

**Comment by dstran** [comment]
Has anyone successfully generated PDF from Swagger API documentation?
