### ISSUE TITLE
pytype not really documented

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#252]
From reading [this](https://github.com/marcgibbons/django-rest-swagger/blob/4593ae91469dd58e569011222509af47a0f99e45/docs/source/yaml.rst#pytype) I am not really sure what `pytype`.

**Comment by ariovistus** [comment]
Hm. that is pretty terrible. So there is the option `type` which lets you specify the fields and whatnot of your model manually in the yaml. There is also the standard drs behavior of generating type from the drf serializer associated with whatever view is being inspected. I think pytype is something in between the two, where you specify some other serializer in the yaml and drs generates the swagger type from that.

Don't remember what particular case this is useful for, though

**Comment by marcgibbons** [comment]
I have no idea what that is - but, it has been deprecated.
