### ISSUE TITLE
Simple way of setting URL Parameter

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#253]
The docs state that one of the features is: "URL parameters (ie. /product/{id})" but unless I am missing something this is how I deal with a when my model's pk is a `UUID`. This is the docstring for the `ViewSet`:
```python
    """
    Item resource.
    ---
    retrieve:
        parameters:
            - name: pk
              type: uuid
    update:
        parameters:
            - name: pk
              type: uuid
    partial_update:
        parameters:
            - name: pk
              type: uuid
    destroy:
        parameters:
            - name: pk
              type: uuid
    """
```
Otherwise the UI shows the type as "string"

**Comment by cancan101** [comment]
Related note is that the type for URL params is [hardcoded to "string"](https://github.com/marcgibbons/django-rest-swagger/blob/cdabd70562129019576673ee3c6aa16308bcc5f7/rest_framework_swagger/introspectors.py#L339) which seems less than ideal in either the UUID case or the int pk case.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.
