### ISSUE TITLE
Specifying Parameter Type Resets Required

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#254]
I have a parameter that is being auto-generated. When auto-generated it is correctly marked as required.
If I try to override the type using:
```yaml
            - name: person
              type: uuid
```
then the field is no longer marked as required unless I explicitly add:
```yaml
              required: true
```

**Comment by monk8800** [comment]
This seems to be a design feature once you override the parameters you need to explicity define the rest of the attributes such as required etc, which makes sense in my opinion.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.
