### ISSUE TITLE
type and format are switched for datetimes and wrong for enum

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#258]
Per [the spec](https://github.com/swagger-api/swagger-spec/blob/0afe1d351dc0e08b80fdf9a47816a9415a3f1a32/versions/1.2.md#431-primitives)
![image](https://cloud.githubusercontent.com/assets/51059/7264116/345b2f1c-e856-11e4-9952-0733b59b01bb.png)

but [it looks like](https://github.com/marcgibbons/django-rest-swagger/blob/cdabd70562129019576673ee3c6aa16308bcc5f7/rest_framework_swagger/introspectors.py#L389) this is being set wrong by django-rest-swagger.

For example I end up with:
```
format: "string"
type: "datetime"
```

**Comment by wing328** [comment]
I also encountered similar issue. May I know if there's any plan to address the issue ?
