### ISSUE TITLE
Arrays Always Treated as Primitives

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#268]
This is not the correct predicate here for checking for complex arrays:
https://github.com/marcgibbons/django-rest-swagger/blob/4e9e4ff79cfd30c66393997bc14a629a546a30a0/rest_framework_swagger/docgenerator.py#L345

**Comment by ariovistus** [comment]
do you mean arrays of arrays? I think swagger-ui 1.2 doesn't support those

**Comment by cancan101** [comment]
I believe this issue was fixed in a recent PR.
