### ISSUE TITLE
create_view should create DRF Request not Django HttpRequest

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#269]
See: https://github.com/cancan101/django-rest-swagger/commit/d80f426179d0a3b0eefcec819efa44309ac3cd3d

**Comment by andybak** [comment]
Yep. This is breaking in a fairly major way for me.

I'm getting a failure accessing either request.QUERY_PARAMS or request.query_params so the introspection phase fails.

**Comment by sebdiem** [comment]
:+1:  This bug is really annoying and it seems to be easily fixed with @cancan101's proposal.
Would you consider merging this to master ?

**Comment by ariovistus** [comment]
If you submit a pr, sure
