### ISSUE TITLE
Django rest swagger views.py only uses first default renderer class

### ISSUE THREAD

**Issue by samanehsan** [marcgibbons/django-rest-swagger#271]
My django rest framework application is using a custom content-type `application/vnd.api+json` with the following default renderer classes: 
```
'DEFAULT_RENDERER_CLASSES': (
        'api.base.renderers.JSONAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ),
```

With this configuration, I get a 406 : NOT ACCEPTABLE error, but if I switch the order of the 'DEFAULT_RENDERER_CLASSES' so that `rest_framework.renderers.JSONRenderer` is first, then the swagger documentation will render.

I think this might be the cause: https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/views.py#L22-28

It looks like the view expects `rest_framework.renderers.JSONRenderer` to be first when ideally, the order should not matter.

**Comment by marcgibbons** [comment]
This has been fixed in version 2.0; the SwaggerUI and the OpenAPI specs are now their own renderer classes.
