### ISSUE TITLE
Question: How to keep YAML stuff  separate from docstring in django project because it makes file bulky??

### ISSUE THREAD

**Issue by tnishank** [marcgibbons/django-rest-swagger#273]

**Comment by ariovistus** [comment]
Currently, there is no way to do this, but this does need to change for a variety of reasons.

**Comment by monk8800** [comment]
This would definitely be a nice feature to have.

**Comment by marcgibbons** [comment]
YAML is out in v2, schema generation is done by DRF.  Will be looking into allowing overrides to the swagger spec in the future, but will aim to make these separate templates, outside of the code and docstring.
