### ISSUE TITLE
Add hide_parameters in yaml config

### ISSUE THREAD

**Issue by shuoli84** [marcgibbons/django-rest-swagger#279]
I need to hide some parameter if following cases:
There are 2 models, car and wheel. And two endpoints to create wheel:
/api/cars/{carId}/wheels/ POST
/api/wheels/ POST

My wheel serialiser has field car, which is perfectly good in 2nd endpoints, but annoying in the first one. Because I already has carId there. I think a proper way to do this is add one hide_parameters list which quite like omit_paramters. But this one hide paramters by their name instead of type. Any idea?

**Comment by cancan101** [comment]
create a second serializer instead.

**Comment by shuoli84** [comment]
I guess we can also create multiple views to replace viewset?

**Comment by cancan101** [comment]
Not sure what you mean. Just inject the car in serializer save.

**Comment by shuoli84** [comment]
I use one serialiser class for both endpoints, for endpoint, /api/cars/{carId}/wheels/ POST, generated swagger doc has two params: carId in url and car defined in serialiser. I need to hide the one from serialiser class.
I am not talking about how to implement the serialiser, but how to hide the param from swagger.

**Comment by cancan101** [comment]
You are doing it wrong.

**Comment by shuoli84** [comment]
What is wrong?

**Comment by cancan101** [comment]
Why are you trying to hide a parameter that the serializer handles?seems
like a potential security issue. Just create a other serializer.

**Comment by shuoli84** [comment]
I am setting the serialiser's param in view's function, it is not hidden, just set in a different way. I don't think it is a good idea to create a new Serialiser class for such simple things. 
And also there is a flag which able to hide the whole type of params, the omit_parameters. Security is critical but not the responsibility of the doc generating lib, I guess.

**Comment by cancan101** [comment]
I agree that security is not the responsibility of the doc generating
library but adding this feature seems like the wrong solution to your
problem.
