### ISSUE TITLE
No files on PyPI (0.3.0)

### ISSUE THREAD

**Issue by hirokiky** [marcgibbons/django-rest-swagger#281]
I cant find any files on PyPI https://pypi.python.org/pypi/django-rest-swagger/0.3.0
How can I use this version?

**Comment by trbs** [comment]
+1
```
pip install django-rest-swagger==0.3.0
Collecting django-rest-swagger==0.3.0
  Could not find a version that satisfies the requirement django-rest-swagger==0.3.0 (from versions: 0.1.7, 0.1.8, 0.1.9, 0.1.10, 0.1.11, 0.1.12, 0.1.13, 0.1.14, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.2.5, 0.2.6, 0.2.7, 0.2.8, 0.2.9)
  Some externally hosted files were ignored as access to them may be unreliable (use --allow-external django-rest-swagger to allow).
  No matching distribution found for django-rest-swagger==0.3.0
```

**Comment by ariovistus** [comment]
I think what happened is pypi was down when I made this release, and I forgot to upload it later.

But, I just [re]did the upload, and pip still can't see it, so not sure what's going on.

**Comment by ariovistus** [comment]
there it goes! Alright, folks I think we're in business again

**Comment by bphirokiky** [comment]
great job! we like this library.

**Comment by mochawich** [comment]
@ariovistus I like your comments :smile:
