### ISSUE TITLE
Can't use blocks of code  in notes with bash commands that have "long options"

### ISSUE THREAD

**Issue by imposeren** [marcgibbons/django-rest-swagger#282]
Bash examples with long options are never shown in api docs notes. Tried both markdown and restructuredtext  VIEW_DESCRIPTION_FUNCTION-s.

```
class SomeViewSet(viewsets.ModelViewSet):

    """
    Some resource.

    Example call with digest auth:

        curl --digest -u "username:token" "http://www.example.com/api/v1/some_end_point/"

    Everything after curl example is stripped. This text will not be visible in API browser
    """
```

The problem is in ``IntrospectorHelper.strip_params_from_docstring`` which treats '--d' as "``parameter -- description``" separator and strips lines after example with curl

**Comment by ariovistus** [comment]
well, that's obnoxious, especially since the part that parses the parameter/description won't accept that line anyways.
