### ISSUE TITLE
Swagger not displaying fields when using get_serializer_class() to return different serializers for different URL's

### ISSUE THREAD

**Issue by pattisdr** [marcgibbons/django-rest-swagger#290]
I am using django-rest-swagger to generate API documentation.  First, I had eight view classes using eight different serializers. I wanted to make a single view class and use `get_serializer_class()` to check the route and choose the corresponding serializer class.

With my eight separate view classes, each calling their own serializer, the documentation displayed fine.   Here is one of the eight views, for example. The additional field besides the pk, was the summary.

    class NodeRegistrationsOpenEnded(generics.CreateAPIView, NodeMixin):
        """Register the current node.
         Registrations are read-only snapshots of a project.
         """
         permission_classes = (
             ContributorOrPublic,
             drf_permissions.IsAuthenticatedOrReadOnly,
         )
         serializer_class = RegistrationOpenEndedSerializer

![screen shot 2015-06-08 at 1 05 44 pm](https://cloud.githubusercontent.com/assets/9755598/8040634/f731a0b2-0ddf-11e5-9695-e3338ccbacfd.png)

This is my code after I condensed my eight views into one, using `get_serializer_class`:

 `views.py`:

    class NodeCreateRegistrations(generics.CreateAPIView, NodeMixin):
        """Register the current node.
        Registrations are read-only snapshots of a project.
        """
        permission_classes = (
            ContributorOrPublic,
            drf_permissions.IsAuthenticatedOrReadOnly,
        )

        def get_serializer_class(self):
            parse_object = urlparse(self.request.path)
            if "Open-Ended_Registration" in parse_object.path:
                if "Open-Ended_Registration" in basename(normpath(parse_object.path)):
                    return RegistrationOpenEndedSerializer
                return RegistrationOpenEndedWithTokenSerializer
            elif "Pre-Data_Collection_Registration" in parse_object.path:
                if "Pre-Data_Collection_Registration" in basename(normpath(parse_object.path)):
                    return RegistrationPreDataCollectionSerializer
                return RegistrationPreDataCollectionWithTokenSerializer
            elif "Replication_Recipe_Pre-Registration" in parse_object.path:
                if "Replication_Recipe_Pre-Registration" in basename(normpath(parse_object.path)):
                    return ReplicationRecipePreRegistrationSerializer
                return ReplicationRecipePreRegistrationWithTokenSerializer
            elif "Replication_Recipe_Post-Completion" in parse_object.path:
                if "Replication_Recipe_Post-Completion" in basename(normpath(parse_object.path)):
                    return ReplicationRecipePostCompletionSerializer
                return ReplicationRecipePostCompletionWithTokenSerializer

Below, the Swagger documentation no longer displays the summary field.  It seems like the serializer isn't loaded yet.  If I click Try it out!, the request is sent and the proper response is returned(since the summary is an optional field). It seems the proper serializers are linked to the right URL's, but the documentation isn't loading the serializer fields prior to submitting a request.

![screen shot 2015-06-08 at 12 50 53 pm](https://cloud.githubusercontent.com/assets/9755598/8040267/075e2846-0ddd-11e5-8527-1a4f88797e98.png)

Everything is working except for the Swagger documentation.  The actual API works, but the documentation isn't loading the serializer.

**Comment by ariovistus** [comment]
As memory serves, this is something swagger ui doesn't really support. I thought there was an open issue for this, but I can't seem to find it..

**Comment by pattisdr** [comment]
Thank you, I wasn't certain if it was supported or not.

**Comment by jsanders67** [comment]
This issue should remain open until there is support

**Comment by marcgibbons** [comment]
Sorry for the long delay in response. 
No, something like this was would not have been supported as there is no way for the introspector to anticipate what will be sent in a querystring other than filters or serializers. The issue of DRS not picking this up aside, separate views is probably a simpler implementation for multiple registration.
