### ISSUE TITLE
switch to pytest ?

### ISSUE THREAD

**Issue by ticosax** [marcgibbons/django-rest-swagger#292]
Hi @ariovistus,
I would like to know if you interested to switch to `pytest` instead of `nose` ?
I'll try to make the change if you agree.

**Comment by ariovistus** [comment]
I used pytest once. it was pretty nice. I don't remember if I noticed any compelling reason to use one over the other. Mostly DRS is using nose because that's what DRF uses, and I'm just copying their nice things.

**Comment by ticosax** [comment]
They updated to pytest as well since :)

https://github.com/tomchristie/django-rest-framework/blob/master/runtests.py

**Comment by ariovistus** [comment]
In that case, by all means.

**Comment by marcgibbons** [comment]
Nose is out, using unittest which is so much better in new python versions. Pytest is nice, but would prefer to keep things stock as much as possible.
