### ISSUE TITLE
Specifying method overrides in docstring is now broken

### ISSUE THREAD

**Issue by cancan101** [marcgibbons/django-rest-swagger#303]
My docstring is overriding `list` in the docstring:
```
    list:
        parameters:
...
```
which leads to:
```
Exception: methods ['list'] in class docstring are not in view methods [u'update', u'retrieve', u'partial_update']
```

This seems to be caused by the viewset being called twice:
```
<class 'exam_storage.views.ItemViewSet'> <RegexURLPattern item-list ^items/$> /api/items/
<class 'exam_storage.views.ItemViewSet'> <RegexURLPattern item-detail ^items/(?P<pk>[^/.]+)/$> /api/items/{pk}/
```

**Comment by cancan101** [comment]
The issue was introduced by this commit:

https://github.com/marcgibbons/django-rest-swagger/commit/d759ceb803d52564bff37b7be51f9500f0e8e6b8#diff-e7a0b15425bda5b4165c0a6888823a56L44

**Comment by cancan101** [comment]
A fuller stack trace:
```
    'apis': generator.generate(apis),
  File "/Users/alex/git/django-rest-swagger/rest_framework_swagger/docgenerator.py", line 32, in generate
    'operations': self.get_operations(api),
  File "/Users/alex/git/django-rest-swagger/rest_framework_swagger/docgenerator.py", line 62, in get_operations
    doc_parser = method_introspector.get_yaml_parser()
  File "/Users/alex/git/django-rest-swagger/rest_framework_swagger/introspectors.py", line 188, in get_yaml_parser
    self.check_yaml_methods(parent_parser.object.keys())
  File "/Users/alex/git/django-rest-swagger/rest_framework_swagger/introspectors.py", line 183, in check_yaml_methods
    % (list(missing_set), list(self.parent.methods())))
```

**Comment by ticosax** [comment]
@ariovistus already detected the regression in #298 
I recommend to revert #291 asap, then I'll work again on #291 with a better implementation.

**Comment by cancan101** [comment]
:+1:  on reverting.

**Comment by ariovistus** [comment]
hey cool! there's a button for reverting!

**Comment by cancan101** [comment]
@ticosax Any updates on re-fixing this?

**Comment by ticosax** [comment]
not yet, due to lack of time.

**Comment by cancan101** [comment]
@ticosax This is what I ended up using: https://github.com/cancan101/django-rest-swagger/commit/652f3618349d643a455f3d7aa60b7668e18d2d50

**Comment by ticosax** [comment]
That's awesome. feel free to take the tests in #291 (if it makes sense), and make a PR.

**Comment by xiaohanyu** [comment]
+1， waiting for the fix.
