### ISSUE TITLE
Question: Does django-rest-swagger support complex response types? 

### ISSUE THREAD

**Issue by gutfeeling** [marcgibbons/django-rest-swagger#305]
In the docs I found the following:

Type:
If your view does not use a serializer at all but instead outputs a simple data type such as JSON you may define a custom response object in the method signature as follows:

This was the example that was given:

type:
  name:
    required: true
    type: string
  url:
    required: false
    type: url

I am wondering whether it is possible to document complex JSON like this:

{ 'attr1': 'value1',
  'attr2' : [ 
               {'attr3' : 'value3',
                'attr4' : 'value4',
                },
               ...
               ]
}

Thanks in advance for your response  :)

**Comment by CodyMorris** [comment]
+1, really trying to figure this out

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Using body parameters in Swagger makes this possible, need to confirm that this is working in DRF 3.4.

**Comment by marcgibbons** [comment]
Going to track this in #529
