### ISSUE TITLE
consumes/produces mieme types 

### ISSUE THREAD

**Issue by ghost** [marcgibbons/django-rest-swagger#308]
I tried to populate the "Response Content Type" select box with multiple types using YAML syntax 
consumes:
   - application/json
   - application/xml
produces:
   - application/json
   - application/xml

but it doesn't work.

**Comment by thinkt4nk** [comment]
btw, @blakie if you intend to affect the response content type, you'll be defining `produces` instead

**Comment by marcgibbons** [comment]
Going to track this in #529
