### ISSUE TITLE
Use latest swagger-ui

### ISSUE THREAD

**Issue by rygwdn** [marcgibbons/django-rest-swagger#309]
It looks like the version of [swagger-api/swagger-ui](https://github.com/swagger-api/swagger-ui) that is in use by django-rest-swagger is quite old. From what I can see it looks like it's based on [2.0.17](https://github.com/swagger-api/swagger-ui/releases/tag/2.0.17). Is there a reason it hasn't been updated? Would a PR updating to the latest be likely to be accepted? I see there have been a few changes made manually to the JS and CSS, but those changes could probably be re-applied if necessary.

**Comment by ariovistus** [comment]
go for it

**Comment by ariovistus** [comment]
fine, I'll go for it.

**Comment by ariovistus** [comment]
ugh, I went for it: https://github.com/ariovistus/django-rest-swagger/tree/swagger-ui-2.1.0

currently, there be some javascript errors when I run it with cigar example, and both firefox and chrome are refusing to let me debug. Anybody want to have a look and tell me what's going on?
(like where node_modules/* is coming from) It might just be breaking on invalid data.

After that, we get to figure out all the non-upstream changes made to our swagger-ui that need to go back in, yay!

**Comment by jason-kane** [comment]
Looks like you figured it out; latest on your branch at least passes the sniff test.  No obviously issues in chrome (clean console).

**Comment by ariovistus** [comment]
wish i had your browser then. its still giving me grief.

**Comment by jason-kane** [comment]
spoke too soon

the problem is in swagger-ui

Handlebars.registerHelper('renderTextParam', function(param) {
    var result, type = 'text', idAtt = '';
    var isArray = param.type.toLowerCase() === 'array' || param.allowMultiple;

it's choking on the param.type.toLowerCase(); the GET and POST in class MyCustomView(APIView): are failing because they coming through with a "type" attribute.  If you remove those attributes from the class docstrings it will get further.

**Comment by jason-kane** [comment]
if I swap in my version of templates/base.html:

https://github.com/jason-kane/django-rest-swagger/blob/swagger2/rest_framework_swagger/templates/rest_framework_swagger/base.html

Most of the cosmetic stuff clears up too.

**Comment by ariovistus** [comment]
ah, thank you. #326 ought to fix the MyCustomView problems

**Comment by ariovistus** [comment]
it does. you're base.html gets us further, now the new swagger-ui is giving us an undefined model where a write model should be, and a goofy model schema.

**Comment by tarkatronic** [comment]
Have there been any further efforts on this? Or are there likely to be?

**Comment by ariovistus** [comment]
nope, sorry. afraid I don't have the time currently.

**Comment by blueyed** [comment]
There is a PR (WIP) for this at https://github.com/marcgibbons/django-rest-swagger/pull/356.

**Comment by edmorley** [comment]
Updating to a swagger-ui version >=2.1.0 would also fix #73.

**Comment by marcgibbons** [comment]
Done!

**Comment by robermorales** [comment]
Current version of Swagger UI is 2.2.5.

Any ideas of how can we help upgrading the UI inside django-rest-swagger?
