### ISSUE TITLE
Source of the image throbber.gif is wrong

### ISSUE THREAD

**Issue by rosesonfire** [marcgibbons/django-rest-swagger#311]
the source given is 
src="rest_framework_swagger/images/throbber.gif"

it should be
src="static/rest_framework_swagger/images/throbber.gif"

**Comment by ariovistus** [comment]
effectively, what should be happening is 

    src="{{STATIC_URL}}rest_framework_swagger/images/throbber.gif"

if you aren't getting that, either STATIC_URL is misconfigured, or this line: https://github.com/marcgibbons/django-rest-swagger/blob/e917f70a7b9a1468c79f6256c9be55516ae2a766/rest_framework_swagger/templates/rest_framework_swagger/base.html#L50

isn't being run.

**Comment by rosesonfire** [comment]
Rest of the page (css, js, etc) are properly url-ed. Only throbber.gif is not.

**Comment by rosesonfire** [comment]
Rest of the page (css, js, etc) are properly url-ed. Only throbber.gif is not. 


     On Tuesday, June 30, 2015 1:16 AM, ariovistus <notifications@github.com> wrote:
   

 effectively, what should be happening is src="{{STATIC_URL}}rest_framework_swagger/images/throbber.gif"
if you aren't getting that, either STATIC_URL is misconfigured, or this line: https://github.com/marcgibbons/django-rest-swagger/blob/e917f70a7b9a1468c79f6256c9be55516ae2a766/rest_framework_swagger/templates/rest_framework_swagger/base.html#L50isn't being run.—

**Comment by ariovistus** [comment]
so STATIC_URL is an empty string. maybe set

    STATIC_URL = '/static/'

in your settings.py?

**Comment by rosesonfire** [comment]
it is set already, I'm afraid :/

**Comment by ariovistus** [comment]
hmm. are you using the default templates (base.html and index.html)?

**Comment by rosesonfire** [comment]
myProject/Settings.py
=====================
```python
DEBUG = True

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_countries',

    'rest_framework',
    'rest_framework.authtoken',
    'rest_auth',
    'rest_framework_swagger',
    'rest_auth.registration',
    
    'allauth',
    'allauth.account',
    
    'django_extensions',
    .........
    ......
)

ROOT_URLCONF = 'myProject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")
```

myProject/urls.py
=================
```python
from django.conf.urls import include, url
from django.contrib import admin
from django.template.loader import render_to_string

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),

    .................
    .............

    url(r'^docs/', include('rest_framework_swagger.urls')),
    
    .........
    .....
]
```

**Comment by dpetzel** [comment]
I've bumped into this today as well using the stock templates. I am using version `0.3.2` I hacked up a template override and can see that `{{STATIC_URL}}` returns empty. I tried changing it to `{% static "" %}` which does return the proper value (`/static/` in my case), but still the image 404s with the wrong path. All the other static assets references in that link above work (and they are also using the static tag)

I made the following adjustment to the template: `window.static_url = '{% static "" %}';`, Looking at the js I can see its using `src='"+ window.static_url +"rest_framework_swagger/images/throbber.gif'` which sure seeme like it should work, but the static prefix is simply not part of the URL when the resource is fetched.

Its almost as if its attempting the fetch the image before that JS has fired but I don't know javascript well enough to know if that is the case for sure.

**Comment by ariovistus** [comment]
pr #334 made the same fix. maybe try using master?

**Comment by dpetzel** [comment]
I'll give master a shot, but when I mad that change it still didn't work properly.

**Comment by ccatterina** [comment]
Hi, I have the same problem with version 0.3.10.
here is a screen:

![image](https://cloud.githubusercontent.com/assets/9085116/19066455/a4dc869e-8a19-11e6-9bef-6f39372f5928.png)

the file exists in static/rest_framework_swagger/images/

**Comment by gabber7** [comment]
Hi, the problem was reintroduced by https://github.com/marcgibbons/django-rest-swagger/pull/420
