### ISSUE TITLE
[Question] Nested results/requests?

### ISSUE THREAD

**Issue by cristianocca** [marcgibbons/django-rest-swagger#314]
If I want to indicate that the result object has for example, a varible that is a list of strings, or another object, is this possible with the current "type" or "parameters" YAML strings? What about serializers?

**Comment by ariovistus** [comment]
not sure about "type", but you can reference a serializer with "pytype"

**Comment by cristianocca** [comment]
Most of the time I'm returning plain python lists/dicts, without serializers as I don't really need them for responses, so it would be great to be able to define a structure just like I can currently do with "type" or "parameters".

**Comment by ariovistus** [comment]
according to swagger spec

    type: array
    items:
        type: string

is how you specify a list of strings. unfortunately, it looks like our yaml parser doesn't believe in items.

**Comment by cristianocca** [comment]
Oww, yes I believe that is what I wanted. Well, looking forward for this to be added in the near future!

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.
