### ISSUE TITLE
Problem with custom CSRF cookie name

### ISSUE THREAD

**Issue by orporat** [marcgibbons/django-rest-swagger#316]
Hi,

I've encountered a problem making Non-GET requests with the error:
"CSRF Failed: CSRF token missing or incorrect."

When I looked at the request headers I saw the problem, the header looked like this:
X-CSRFToken: undefined

I figured it's happening because I'm using it on a dev env. where I've set a custom CSRF cookie name ("dev-csrftoken") where the DRS code bit (shred.bundle.js, line 2608) that gets the CSRF cookie value is hardcoded to the name "csrftoken".

Changing this value directly in the code fixed the problem, but I don't think it's good as a long term solution.

Can this be added as a value that can be configured in DRS's settings block?

Thanks!

**Comment by bahmany** [comment]
i have the same problem
