### ISSUE TITLE
Add `include_namespaces` setting

### ISSUE THREAD

**Issue by micahhausler** [marcgibbons/django-rest-swagger#327]
There is currently an [`exclude_namespaces`](http://django-rest-swagger.readthedocs.org/en/latest/settings.html#exclude-namespaces) setting, however I'd like to have an explicitly `include_namespaces` setting. 

## Proposal
A `include_namespaces` so that the swagger-ui would only display endpoints that matched the specified namespaces. This could override the existing `exclude_namespaces` in the event that an endpoint matched both `include_` and `exclude_`.

## Reasoning
I have a current site that does not have good API namespacing, but has over 30 private endpoints that I would have to specify in the current `exclude_namespaces` setting. This is a larger project with multiple developers, and I'd like to use this to start documenting publicly accessible endpoints (under a single namespace) without every dev having to remember to explicitly add new internal endpoints to the exclusion list.

## Implementation
I would be happy to implement this, but I wanted to get some feedback before hacking out the code.

**Comment by mverteuil** [comment]
There is a `resource_access_handler` callback that can exclude any view that isn't decorated with some particular view decorator of your choosing. 

This is a more elegant solution, as there's already a lot of machinery that people are trying to hack in for essentially the same overall behaviour.

**Comment by qrilka** [comment]
@mverteuil it's not quite clear what do you propose with `resource_access_handler` - it's being called with a `request` and `resource` (which is just a URLPattern) parameters and those don't have any information about namespaces or views (and its decorators).
So it doesn't appear to be a valid solution to me.

**Comment by marcgibbons** [comment]
In v2 / DRF 3.4, URL patterns can be explicitly specified in the schema generator.
