### ISSUE TITLE
Adding DynamicFieldsMixin causes KeyError 'request'

### ISSUE THREAD

**Issue by pmrukot** [marcgibbons/django-rest-swagger#328]
So here is my mixins.py:
```python
class DynamicFieldsMixin(object):
    def __init__(self, *args, **kwargs):
        super(DynamicFieldsMixin, self).__init__(*args, **kwargs)
        fields = self.context['request'].QUERY_PARAMS.get('fields')
        if fields:
            fields = fields.split(',')
            # Drop any fields that are not specified in the `fields` argument.
            allowed = set(fields)
            existing = set(self.fields.keys())
            for field_name in existing - allowed:
                self.fields.pop(field_name)
```

And here are the errors i get after adding it to my project:

![issue1](https://cloud.githubusercontent.com/assets/13131966/8820682/05879d70-3058-11e5-8cf3-eec2ebc817b6.png)

![issue2](https://cloud.githubusercontent.com/assets/13131966/8820684/07d05432-3058-11e5-95f7-57c621845de3.png)

When i disable the code from DynamicFieldsMixin everything works fine. Any ideas?
Seems like Swagger doesn't provide context for serializers (?)

**Comment by ariovistus** [comment]
might try sticking it in yourself with view_mocker: http://django-rest-swagger.readthedocs.org/en/latest/yaml.html#view-mocker

**Comment by mverteuil** [comment]
Are you mixing this into your View or your Serializer? In any event, your DRF code is a bit dated, because the current recommendation is to use [`query_params` rather than `QUERY_PARAMS`.](http://www.django-rest-framework.org/api-guide/requests/#query_params)
