### ISSUE TITLE
0.3.3 build?

### ISSUE THREAD

**Issue by davidrenne** [marcgibbons/django-rest-swagger#329]
Hey there hubbers!

I am not sure of the teams schedule or what bugs need to be in the next release, but it would be nice if I could cut a build and send over a pull request for a build to be hosted on pypi with my most recent pull request so I can take this out of my requirements.txt:

git+https://github.com/davidrenne/django-rest-swagger.git@f78b8d79df0edcf89d75fc87730919a75c51e656#egg=django-rest-swagger

**Comment by ariovistus** [comment]
yeah, we're a bit overdue for a release. I'll try and get her out there tonight

**Comment by ariovistus** [comment]
I think we're golden
