### ISSUE TITLE
resource_access_handler is not documented

### ISSUE THREAD

**Issue by ariovistus** [marcgibbons/django-rest-swagger#330]

**Comment by mverteuil** [comment]
Fair enough, I'll provide a reference implementation :)

**Comment by mverteuil** [comment]
Wait... yes I did document it!

**Comment by mverteuil** [comment]
http://django-rest-swagger.readthedocs.org/en/latest/settings.html#resource-access-handler

**Comment by ariovistus** [comment]
hm. must have looked at it before remembering to rebuild.
