### ISSUE TITLE
Trying to upgrade django rest swagger upgrades Django to 1.8.3 forcefully

### ISSUE THREAD

**Issue by somghosh** [marcgibbons/django-rest-swagger#332]
I am on Django 1.6.5 and have django-rest-swagger==0.1.14

I upgraded from djangorestframework==2.6.5 to djangorestframework==3.1.3 and my django rest swagger was not working. So I tried 

    pip install django-rest-swagger --upgrade

However, this is upgrading my Django to 1.8.3 by force and breaking my code. Is there a way to avoid this?

(tvenv)➜  ~  pip install django-rest-swagger --upgrade
Downloading/unpacking django-rest-swagger from https://pypi.python.org/packages/source/d/django-rest-swagger/django-rest-swagger-0.3.3.tar.gz#md5=6804aaae7ca65a0cce7ab6d4e252bc47
  Downloading django-rest-swagger-0.3.3.tar.gz (198kB): 198kB downloaded
  Running setup.py (path:/Users/somghosh/.virtualenvs/tvenv/build/django-rest-swagger/setup.py) egg_info for package django-rest-swagger

	Downloading/unpacking django>=1.5 from https://pypi.python.org/packages/py2.py3/D/Django/Django-1.8.3-py2.py3-none-any.whl#md5=a5d397c65a880228c58a443070cc18a8 (from django-rest-swagger)
	  Downloading Django-1.8.3-py2.py3-none-any.whl (6.2MB): 6.2MB downloaded
	Requirement already up-to-date: djangorestframework>=2.3.8 in ./.virtualenvs/tvenv/lib/python2.7/site-packages (from django-rest-swagger)
	Requirement already up-to-date: PyYAML>=3.10 in ./.virtualenvs/tvenv/lib/python2.7/site-packages (from django-rest-swagger)
	Installing collected packages: django-rest-swagger, django
	  Found existing installation: django-rest-swagger 0.1.14
	    Uninstalling django-rest-swagger:
	      Successfully uninstalled django-rest-swagger
	  Running setup.py install for django-rest-swagger

	  Found existing installation: Django 1.6.5
	    Uninstalling Django:
	      Successfully uninstalled Django
	Successfully installed django-rest-swagger django
	Cleaning up...

**Comment by ariovistus** [comment]
pip help install

```
-U, --upgrade               Upgrade all specified packages to the newest
                              available version. This process is recursive
                              regardless of whether a dependency is already
                              satisfied.
```

maybe pip install django-rest-swagger==0.3.3

**Comment by somghosh** [comment]
Thanks very much, that works well.
