### ISSUE TITLE
Nested many=True serializers?

### ISSUE THREAD

**Issue by smills2929** [marcgibbons/django-rest-swagger#335]
I have an object with multiple levels of nested many=True serializers.

I simply can't figure out how to show this kind of an output in the swagger view. If I just reference the top-level serializer in YAML it doesn't seem to go more than 1 deep, and if I use the "type:" docstring I can't figure out how to show the nested arrays. What am I missing?

So, I want to end up with something like:
{  
    "publishers":[  
        {  
            "authors":[  
                {  
                    "books":[  
                        {  
                            "chapters":[  
                                {  
                                    "name":"chapter 1"
                                }
                            ]
                        }
                    ]
                }
            ]
        }
    ]
}

**Comment by marcgibbons** [comment]
Hello, closing as YAML docstrings have been deprecated.
