### ISSUE TITLE
getting error "csrf failed while making POST request with an image file"

### ISSUE THREAD

**Issue by tnishank** [marcgibbons/django-rest-swagger#339]
I posted the detail question in stack oberflow [link] (http://stackoverflow.com/questions/31811427/csrf-failed-while-uploading-the-file)

**Comment by pushkarparanjpe** [comment]
Facing the same issue. However, if the user is not logged in then the POST request goes through smoothly and a response is returned.
I investigated the HTTP request headers and form data. Apparently, the csrf token is not being submitted. Could this be the cause of the trouble ?

**Comment by marcgibbons** [comment]
The CSRF token is fixed in v2 if using Django auth session. However, images are not yet supported in DRF 3.4 schemas.
