### ISSUE TITLE
boolean type doesn't work properly

### ISSUE THREAD

**Issue by dpetzel** [marcgibbons/django-rest-swagger#340]
I saw some other issues that danced around this a little, but nothing that hit specifically what I'm bumping up against.

I've documented one of my viewsets with this snippet:
```
        - name: active
          description: Filter on active vs inactive
          paramType: query
          type: boolean
```

This renders a dropbox box with these properties:
```
<select class="parameter" name="active">
  <option selected="" value=""></option>
  <option value="true">true</option>
  <option value="false">false</option>
</select>
```
So my issue is separate (I think) from https://github.com/marcgibbons/django-rest-swagger/issues/225 (regardless of the select vs check) in that the value is not usable.

Per the DRF docs:
> When using boolean fields, you should use the values True and False in the URL query parameters, rather than 0, 1, true or false. (The allowed boolean values are currently hardwired in Django's NullBooleanSelect implementation.)

When I `Try it out!` the filter doesn't work. I believe for this to actually work the values need to be `True` and `False`. There seems to be a bit of fingerpointing <sup>1</sup> on where the actual root of this issue is though.

It is possible on my end (either via config or code change) to fix that?  The only workaround I've thougt of so far is in the docstring yaml change the type to a string so users could put in the literal string values of True and False, but I'd much rather have accurate documentation on what the type is

Is this something you think should get addressed in this project?

<sup>1</sup> https://github.com/tomchristie/django-rest-framework/issues/2122

**Comment by cancan101** [comment]
Look at docs for `swagger-ui`:
![image](https://cloud.githubusercontent.com/assets/51059/9096773/4be30724-3b8d-11e5-95ac-e40c17c7b66b.png)

**Comment by dpetzel** [comment]
Thanks @cancan101 I had stumbled across that, but I couldn't figure out how/where I could configure `django-rest-swagger` to pass those configuration options into `swagger-ui`. I'm a total newb with swagger so apologies if this is a dumb question, but I'm struggling with where I might set that from my end or by messing with `django-rest-swagger` itself.

**Comment by cancan101** [comment]
These are the settings passed to the ui:
https://github.com/marcgibbons/django-rest-swagger/blob/b4117fe7fb2aabfb6ffc005b1ffcfb0cf3d63f95/rest_framework_swagger/templates/rest_framework_swagger/base.html#L65-L79

**Comment by dpetzel** [comment]
ahh ha! that I know how to work with :). Do you think it makese sense for those BooleanValues to be set in the base template here (rather than me overriding the block)? If so I can put together a PR.

**Comment by cancan101** [comment]
Given that this is specifically for django-rest, it might make sense to make the default consistent with DRF but allow the user to override the setting. 

I, for example, use the default swagger-ui setting by have customized DRF to handle the lower case boolean names.

**Comment by dpetzel** [comment]
Sadly the template override didn't work. I believe I've now hit this: https://github.com/swagger-api/swagger-ui/issues/1272

**Comment by dpetzel** [comment]
@cancan101 any chance you could share your customized DRF that handles lowercase boolean names?

**Comment by cancan101** [comment]
I am using django-filter and this is my solution:
```python
class NullBooleanSelectFixed(NullBooleanSelect):
    def value_from_datadict(self, data, files, name):
        value = data.get(name, None)
        if value in (True, 'True', 'true', '1'):
            return True
        elif value in (False, 'False', 'false', '0'):
            return False
        else:
            return None

class NullBooleanFieldFixed(forms.NullBooleanField):
    widget = NullBooleanSelectFixed

class BooleanFilterFixed(BooleanFilter):
    field_class = NullBooleanFieldFixed

class MyFilterSet(FilterSet):
    filter_overrides = dict(FilterSet.filter_overrides,
        **{models.BooleanField: {'filter_class': BooleanFilterFixed}})
```

**Comment by dpetzel** [comment]
@cancan101 , genius!, worked like a charm. And after digging into this, I don't believe the issue lies in this project so closing this out.

**Comment by cancan101** [comment]
I would say if swagger-ui adds back the `booleanValues` setting, then this project should set it to a value consistent with DRF defaults.
