### ISSUE TITLE
The comment can not be parsed when using decorator

### ISSUE THREAD

**Issue by virusdefender** [marcgibbons/django-rest-swagger#341]
Example
```python
class JoinGroupAPIView(APIView):
    def post(self, request):
        """
        加入某个小组的api
        ---
        request_serializer: CreateJoinGroupRequestSerializer
        """
        pass
```
It works fine
<img width="832" alt="qq20150811-5 2x" src="https://cloud.githubusercontent.com/assets/4939404/9192441/b8e29e70-403d-11e5-8cf1-b52ddee0bdf8.png">

But when I added `@login_required` decorator, the document it generated has something wrong
```python
class JoinGroupAPIView(APIView):
    @login_required
    def post(self, request):
        """
        加入某个小组的api
        ---
        request_serializer: CreateJoinGroupRequestSerializer
        """
        pass
```
<img width="461" alt="qq20150811-4 2x" src="https://cloud.githubusercontent.com/assets/4939404/9192446/c1d38cba-403d-11e5-8ce8-9638330a5d9a.png">

**Comment by ariovistus** [comment]
shouldn't you be using permission_classes or get_permissions in conjunction with permissions.IsAuthenticated instead of login_required?

**Comment by virusdefender** [comment]
I added `@wraps(func)` for my decorator. It worked now.

Because the decorator will change the name of the function.

http://stackoverflow.com/questions/308999/what-does-functools-wraps-do

Thanks!
