### ISSUE TITLE
`choice` parameter type is not valid

### ISSUE THREAD

**Issue by thinkt4nk** [marcgibbons/django-rest-swagger#343]
Is there a reason that a `ChoiceField` is returned as a `choice` type parameter?  The swagger spec doesn't support the type and it's not defined as a model, so anything that depends on it being valid swagger (e.g. codegen) fails when a django model has a `ChoiceField`.

[1] https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/introspectors.py#L490-L491

**Comment by ivanprjcts** [comment]
I agree with you. I think this is a bug.
