### ISSUE TITLE
Django REST Swagger shows only {version}

### ISSUE THREAD

**Issue by DevilPinky** [marcgibbons/django-rest-swagger#344]
I've integrated [Django REST Swagger][1] for my Django REST Framework API with python 3.4.3 and on the docs page I can only see one line: {version}, and I'm not able to expand it.

My **urls.py**:

    urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^docs/', include('rest_framework_swagger.urls')),

    # Dictionary methods
    url(r'^(?P<version>v1)/(?P<shop_id>.+)/dictionary/product_types/$',
        views.ProductTypesView.as_view()),

    url(r'^(?P<version>v1)/(?P<shop_id>.+)/dictionary/brands/$',
        views.BrandsView.as_view()),

    url(r'^(?P<version>v1)/(?P<shop_id>.+)/dictionary/popular_brands/$',
        views.PopularBrandsView.as_view()),

    url(r'^(?P<version>v1)/(?P<shop_id>.+)/dictionary/sizes/$',
        views.SizesView.as_view()),

    #Algorithm methods
    url(r'^(?P<version>v1)/(?P<shop_id>.+)/size/get_size_with_user/$',
        views.GetSizeWithUserView.as_view()),

    url(r'^(?P<version>v1)/(?P<shop_id>.+)/size/get_size_with_orders/$',
        views.GetSizeWithOrdersView.as_view()),

    url(r'^(?P<version>v1)/(?P<shop_id>.+)/size/get_size_with_brand_and_size/$',
        views.GetSizeWithBrandAndSizeView.as_view()), ]

My guess is it happens because of versioning. I'm using URL versioning. 
My **settings.py**:

    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.URLPathVersioning'

And this is my **docs page**:
![image](https://cloud.githubusercontent.com/assets/8843506/9271372/96174c2c-4279-11e5-8e09-c2732fa24592.png)

  [1]: https://github.com/marcgibbons/django-rest-swagger

**Comment by qrilka** [comment]
@DevilPinky have you found any solution to this?
I do a similar thing - versioned DRF but with `NamespaceVersioning` and when I `include` 1 versions (and I see only 1 in your URLs) django-rest-swagger shows me all the resources (with version in URLs).
But when I include another version all I get is 2 paths `v1` and `v2` and resources are listed as subresources of those.
Actually I think that http://stackoverflow.com/a/28867521/110400 seems to be correct and multiple swagger pages are needed but #327 isn't resolved and even it won't be enough as it talks about global django-rest-swagger settings.

**Comment by cancan101** [comment]
This might be related: https://code.djangoproject.com/ticket/26621

**Comment by marcgibbons** [comment]
Versioning is now supported in v2 / DRF 3.4. Each "version" can have its own schema generator view and render its own Swagger UI.
