### ISSUE TITLE
Can one generate a pdf or html using django-rest-swagger

### ISSUE THREAD

**Issue by tawanda** [marcgibbons/django-rest-swagger#345]
Can one generate a pdf or html of the documentation using django-rest-swagger

**Comment by ariovistus** [comment]
not to my knowledge.

cf #251

**Comment by tawanda** [comment]
That would be nice to have, maybe i can intercept the html as its generated and save it somehow, then i do a pull request. which files/methods should i look at in this project

**Comment by ariovistus** [comment]
saving the html wouldn't be sufficient, you'd also need to save the rest apis that drs generates, since swagger is a js application that is entirely driven by those rest apis.

**Comment by tawanda** [comment]
i see, thanks for the help
