### ISSUE TITLE
Unable to POST on serializer fields 

### ISSUE THREAD

**Issue by monk8800** [marcgibbons/django-rest-swagger#346]
Not sure if this is the right place to post this question, Am currently developing a REST API which has a few oneToMany and ManyToOne serialziers.

    specialty (SpecializationSerializer),
    specializations (array[string]),

I cant seem to be able to POST to the serializer fields using swagger, if done via curl or rest client works perfectly. Does Swagger support POST, PUT on serializer or nested serializers fields. If not is there any work arounds?

attempted the following without any successes during swagger POST
    
     def create(self, validated_data):
    		specializations_data = validated_data.pop('specializations')
    		specialty_data = validated_data.pop('specialty')
                specialityKey = specialty_data["id"] if(isinstance(specialty_data, dict)) else specialty_data

**Comment by marcgibbons** [comment]
I'm not sure I understand the problem. Going to close out as DRF is now responsible for generating schema. Please open an issue there for introspection issues in v2+.

**Comment by JJZolper** [comment]
I think the question is why can we not execute a proper POST request to our endpoints using swagger? That or why can we not even send data in a GET request using the Swagger UI? Is this a limitation of Swagger UI or the DRF?
