### ISSUE TITLE
Google Fonts and Remote Sources

### ISSUE THREAD

**Issue by Amnesthesia** [marcgibbons/django-rest-swagger#350]
I run Django REST Swagger in an environment that is not connected to the internet, or has very restricted access - however, Swagger UI makes an attempt to load some remote sources from Google Fonts amongst others, and this makes loading very slow as it has to time out before the rest of it loads. Is there a way I can disable remote sources, without digging into the lib and removing it and without editing my /etc/hosts file?

**Comment by ariovistus** [comment]
looks like the culprit is https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/templates/rest_framework_swagger/base.html#L9

you can override base.html in your project and omit the include. Not sure if there are any others pulled in by the swagger css or js.

**Comment by marcgibbons** [comment]
Static files are now all contained within the project.
