### ISSUE TITLE
Can't get this error to go away on GenericAPIView

### ISSUE THREAD

**Issue by martyzz1** [marcgibbons/django-rest-swagger#351]
AssertionError: 'ClientFinalizeConsultationView' should either include a `serializer_class` attribute, or override the `get_serializer_class()` method.

My code is as follows... 

    class ClientFinalizeConsultationView(generics.GenericAPIView):
          """
          ---
          # YAML (must be separated by `---`)

          POST:
              type:
                  consultation_id:
                      required: true
              omit_serializer: true
          OPTIONS:
              type:
                  consultation_id:
                      required: true
              omit_serializer: true

          """

      def post(self, request, *args, **kwargs):
          user = self.request.user
          consultation = Consultation.objects.current_consultation(
              user.uid, self.kwargs['consultation_id']
          )
          consultation.finalized = False
          consultation.active = False
          consultation.ended_by_client = True
          consultation.consultation_end_time = utc_now()
          consultation.save()

          args = (
              consultation.expert.uid, consultation.expert.expert.worker_sid,
              consultation.id
          )
          finalize_video_client.apply_async(queue='default', args=args)

          return Response({}, 200)

**Comment by martyzz1** [comment]
I've been doing some digging and I think it's down to this function.  DRF makes an assertion which it didn't use to do in older versions. so the call to
    
    serializer = method_inspector.get_response_serializer_class()

Is breaking.

Would it be possible to move this call to later in the function.

    def _get_method_serializer(self, method_inspector):
        """
        Returns serializer used in method.
        Registers custom serializer from docstring in scope.

        Serializer might be ignored if explicitly told in docstring
        """
        serializer = method_inspector.get_response_serializer_class()
        doc_parser = method_inspector.get_yaml_parser()

        if doc_parser.get_response_type() is not None:
            # Custom response class detected
            return None

        if doc_parser.should_omit_serializer():
            serializer = None

        return serializer

**Comment by martyzz1** [comment]
I've got a fix working in this pull request

https://github.com/marcgibbons/django-rest-swagger/pull/352

**Comment by marcgibbons** [comment]
I'm not sure if the PR above resolved the issue, however GenericAPIViews require serializer classes. Otherwise, use APIViews.
