### ISSUE TITLE
Add "include_namespaces" as a setting variable

### ISSUE THREAD

**Issue by cjhenck** [marcgibbons/django-rest-swagger#353]
For some monolithic applications, it may make sense for the generator to start with a subset of namespaces, or perhaps just a root URL.  Right now, it will parse all URLs, even if only some are used.

E.g. if my apis are at "/api/", then I should be able to limit the parsing to that prefix.  

Alternatively, perhaps just limiting URL parsing to the base API url would serve the same function.

**Comment by thinkt4nk** [comment]
duplicate of https://github.com/marcgibbons/django-rest-swagger/issues/327?

**Comment by marcgibbons** [comment]
Urlpatterns can now explicitly be specified in DRF 3.4 using the schema generator.
