### ISSUE TITLE
How to add custom endpoint 

### ISSUE THREAD

**Issue by davidportella** [marcgibbons/django-rest-swagger#354]
I have others enpoints in project (example package oauth2_provider add endpoints for oauth token's) how to add this in swagger doc, any fake docstring? or static format?

**Comment by ramsey-wwwings** [comment]
I have a problem with this as well. It doesn't seem to pick my yaml and isn't documented very well in the docs. Someone care to chime in?

**Comment by dotcs** [comment]
I face the same problem. Would be nice to have a way to create a "swagger-exempt" which will ignore the route. Some decorator or "magic" keyword in the docstring to archive this would be nice.

**Comment by ramsey-wwwings** [comment]
I solved this by converting my views into viewsets. From DRF docs:

>Typically, rather than explicitly registering the views in a viewset in the urlconf, you'll register the  viewset with a router class, that automatically determines the urlconf for you. 

http://www.django-rest-framework.org/api-guide/viewsets/

**Comment by marcgibbons** [comment]
The docs get generated for subsets of APIViews only. However, DRF now generates the schema documentation and it is possible to write explicit docs.
