### ISSUE TITLE
Should be a way to customize request serializer field type

### ISSUE THREAD

**Issue by cjhenck** [marcgibbons/django-rest-swagger#355]
```get_parameters()``` will call ```build_form_parameters``` and ```build_body_parameters```, both of which will return similar values based on the request serializer.  However, the form parameters will always be taken over the body parameters.  

There should be a way to specify what the default submission format should be.

**Comment by marcgibbons** [comment]
@cjhenck Sorry for the almost 1yr late response: this probably is no longer pertinent as of v2. Schema now comes from DRF
