### ISSUE TITLE
cannot implements read-only baseserializer because get_fields method is required

### ISSUE THREAD

**Issue by ychab** [marcgibbons/django-rest-swagger#358]
Hi,

We need to implements a read-only serializer, such as one describe here : http://www.django-rest-framework.org/api-guide/serializers/#read-only-baseserializer-classes.

Unfortunetly, introspectors expect that the method ``get_fields`` **must** be implemented (to then apply **later** settings such as ``omit_parameters`` or ``omit_serializer``. Just check ``rest_framework_swagger.introspectors.discover_parameters``).

Of course, we could have other possibilities to achieve it : 

* implements a model serializer and override create/update methods (but is that really safe?)
* implements a dummy method ``get_fields`` wich returns an empty dictionary (ugly, but this is how we do it for now).

Is there is a better way to achieve it? Or could it be fixed quickly (by just check if that method exists and just returns an empty data dict if not)?

thanks

**Comment by marcgibbons** [comment]
I realize this is a super late response. Sounds like this could be achieved using either ReadOnlyFields or settings `read_only_fields` in the serializer Meta class.

http://www.django-rest-framework.org/api-guide/serializers/#specifying-read-only-fields
