### ISSUE TITLE
Nested serializers: when combining form parameters and body, only body is sent.

### ISSUE THREAD

**Issue by cescp** [marcgibbons/django-rest-swagger#360]
I'm trying to get a writable nested serializer working in Swagger.
This is my code:

models.py
```python
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    user = models.OneToOneField(User)
    points = models.IntegerField()

```
serializers.py
```python
from rest_framework import serializers
from django.contrib.auth.models import User
from models import Profile

class ProfileSerializer(serializers.ModelSerializer):
    class Meta:
        model = Profile
        fields = ('points',)

class UserSerializer(serializers.ModelSerializer):
    profile = ProfileSerializer(required=False)
    
    def create(self, validated_data):
        profile_data = validated_data.pop('profile', None)
        user = super(UserSerializer, self).create(validated_data)
        self.create_or_update_profile(user, profile_data)
        return user

    def update(self, instance, validated_data):
        profile_data = validated_data.pop('profile', None)
        self.create_or_update_profile(instance, profile_data)
        return super(UserSerializer, self).update(instance, validated_data)

    def create_or_update_profile(self, user, profile_data):
        profile, created = Profile.objects.get_or_create(user=user, defaults=profile_data)
        if not created and profile_data is not None:
            super(UserSerializer, self).update(profile, profile_data)        

    class Meta:
        model = User
        fields = ('username','first_name', 'last_name','email','profile',)       

```
views.py
```python
from django.contrib.auth.models import User

from rest_framework import viewsets
from rest_framework import permissions

from serializers import UserSerializer

class UserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows a user to be viewed or edited (authentication is required).
    ---
    create:
        parameters:
            - name: profile
              description: profile of the user
              paramType: body
              pytype: serializers.ProfileSerializer
    """
    queryset = User.objects.all()
    serializer_class = UserSerializer
    lookup_field = 'username'
    permission_classes = (permissions.IsAuthenticated,)
    
    def create(self, request, *args, **kwargs):
        return viewsets.ModelViewSet.create(self, request, *args, **kwargs)

```
The swagger UI is correct. When:
1. I only specify a username, it's ok.
2. I specify a username and a profile, I get an error saying that username is mandatory.
Debugging the code, I can see that request data only contains the profile parameters, but not the username.

Is this the right way to proceed with nested serializers?

I'm using:
Django==1.8.4
django-rest-swagger==0.3.4
djangorestframework==3.2.3

**Comment by cescp** [comment]
![swagger_nested](https://cloud.githubusercontent.com/assets/1098977/10204446/10a320d0-67bc-11e5-8542-879f46080b68.png)

**Comment by monk8800** [comment]
This is something am curious about too, if anyone can point us in the right direction.

**Comment by geekashu** [comment]
I am also facing the same issue. Did you ever found the solution for this?

**Comment by mochawich** [comment]
Of course you won't see the username because the body field overrides the entire POST **body** removing anything else like **form** properties. The reason you were able to use only username or any other **form** property (when `profile` is empty) is that by default DRF enables [these parsers](http://www.django-rest-framework.org/api-guide/settings/#default_parser_classes)
```
(
    'rest_framework.parsers.JSONParser',
    'rest_framework.parsers.FormParser',
    'rest_framework.parsers.MultiPartParser'
)
```
This means in the first attempt `JSONParser` was failing and `FormParser` suceeded to fill `request.data` with the username. However, on the second attempt `JSONParser` worked since there is a valid json passed in the request body, therefore other from properties were ignored (as I mentioned above I doubt they were sent first place).

**Comment by mochawich** [comment]
**Bonus** for @cescp 

I'm not sure what is the usage of these lines
```py
        if not created and profile_data is not None:
            super(UserSerializer, self).update(profile, profile_data)        
```
you are somehow creating a recursion. I would rather replace it with
```py
        if not created and profile_data is not None:
            profile.update(**profile_data)        
```
