### ISSUE TITLE
Foreign key fields are represented as 'string', instead of 'field'.

### ISSUE THREAD

**Issue by steven-mercatante** [marcgibbons/django-rest-swagger#361]
http://django-rest-swagger.readthedocs.org/en/latest/examples.html#basic-example-with-a-viewset shows an example field, `manufacturer = models.ForeignKey('Manufacturer')`, whose type is shown to be `field` in the Swagger UI. 

In v0.3.4, Foreign keys are shown to be of type `string`. This also applies to `ManyToManyField`. The type is shown as `array[string]` instead of `array[field]`.

**Comment by savvaoff** [comment]
v.0.3.7 / Django 1.8

still the same:
standard ForeignKey fields are represented as "string" (i guess it should be "integer" or something else, but not "string").

**Comment by jvazquez** [comment]
v.0.3.7 / Django 1.9.7

I'm seeing the same, my fk fields are represented as "string"

**Comment by marcgibbons** [comment]
Yes, this is how the PrimaryKeyRelatedFields render.
v2 / DRF 3.4 is now rendering schema, but at this point, everything is loosely typed as a string.

**Comment by angvp** [comment]
is there any plans to stop being loosely typed as string? or will this be the default behaviour?
