### ISSUE TITLE
How to look for APIs via HTTPS

### ISSUE THREAD

**Issue by superciccio14** [marcgibbons/django-rest-swagger#363]
I'm quite new to django so please be patient if my question is trivial.

My APIs work via HTTPS but Django-rest-swagger tries to build the endpoints list over HTTP and does not find anything.

Is there a way to make django-rest-swagger look for APIs via HTTPS (e.g. https//myUrl/api_docs/)?

**Comment by ticosax** [comment]
Hi,
May I suggest, make sure `request.is_secure()` returns `True`.

**Comment by superciccio14** [comment]
Hi @ticosax, just checked. `request.is_secure()` returns `False`. But in my settings I have `SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')`. Probably the problem is there :(

**Comment by dawalama** [comment]
@superciccio14 I have 
```SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https')``` set in settings.py 

Will will also need to pass the header from apache or nginx. I nginx and have the following line in my site nginx config.
```proxy_set_header X-Forwarded-Protocol $scheme;```

After doing above, request.is_secure() should return True

**Comment by CodyMorris** [comment]
Dealing with the same problem here.  @dawalama , I tried your steps above, including the nginx config change, and no luck :(

**Comment by jebsky** [comment]
Tried to get https working with this and nginx on my setup and it did not work

**Comment by CodyMorris** [comment]
Can you post your nginx server config

**Comment by superciccio14** [comment]
How can I fix that problem with apache? (if i can ask here)

**Comment by mke21** [comment]
I've got the same problem. I use docker-compose for nginx and my django app and a serf-signed certificate (temporary sollution). Django runs with gunicorn.

nginx.conf (I have anonimised the domain):
```
worker_processes 1;
events {
    worker_connections 1024;
}
http {
    server {
        listen 80;
        listen 443 ssl;
        server_name mydomain;
        ssl_certificate /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        
        access_log /dev/stdout;
        error_log /dev/stdout info;
    location /static {
            autoindex on;
            alias /usr/src/app/static;
            include  /etc/nginx/mime.types;
        }
        location /media {
            autoindex on;
            alias /usr/src/app/media;
            include  /etc/nginx/mime.types;
        }
       location / {
            proxy_pass http://web:8000;
            proxy_set_header   Host $host;
            proxy_set_header   X-Real-IP $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header   X-Forwarded-Host $server_name;
            proxy_set_header   X-Forwarded-Protocol $scheme;

            proxy_connect_timeout 300;
            proxy_send_timeout 300;
            proxy_read_timeout 300;
            send_timeout       300;
        }
    }
}
```
Of course, I have set SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTOCOL', 'https').

**Comment by mackeyja92** [comment]
I am having this same issue but I think it is because we have HTTPS nginx pointing to a local HTTP only Apache. We need to be able to override the request is secure.
