### ISSUE TITLE
Get a JSON definition file

### ISSUE THREAD

**Issue by teone** [marcgibbons/django-rest-swagger#364]
I @marcgibbons,
is there any way to retrieve a Swagger definition JSON file out somewhere?

I'm asking as I would like to use it to generate a Js Client library.

Thanks in advance

Teone

**Comment by teone** [comment]
Anybody?

**Comment by soulseekah** [comment]
You'll probably need to wait until https://github.com/marcgibbons/django-rest-swagger/issues/250 is done as the current Swagger UI at http://editor.swagger.io/#/ seems to only support version 2.0.

But you can retrieve the definition by clicking the Raw button next to any endpoint in the docs. Or look at https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/views.py#L140 and call that manually.

**Comment by teone** [comment]
Thanks @soulseekah, 
I've used [fetch-swagger-schema](https://github.com/signalfx/fetch-swagger-schema) to programmatically retrieve the schema, and [swagger-js-codegen](https://github.com/wcandillon/swagger-js-codegen) to generate the APIs.
