### ISSUE TITLE
Unable to introspect fields.ListField

### ISSUE THREAD

**Issue by respondcreate** [marcgibbons/django-rest-swagger#367]
django-rest-swagger introspects `rest_framework.fields.ListField` as type `string` when it should be type `array`.

**Comment by davidrenne** [comment]
What about cases where a list field is using child= with another serializer?

I have seen issues with rest swagger here and would love to fix it, if I had a clue where we might be able to handle it better.

**Comment by respondcreate** [comment]
@davidrenne –

That's a great point! I'll do a bit of investigating and see if I can get ListField to introspect into its `child=` serializer (if defined). Stay tuned!

**Comment by davidrenne** [comment]
Thanks @respondcreate.  I would code it myself, but I seem to have found workarounds from using the ListField because I know its a bug in the project and I dont feel like getting into the inner workings of this project when I can work around it in my project.

You friggin rock!

**Comment by birdonfire** [comment]
:+1: to getting this one worked. just ran into it myself :)

**Comment by aumayr** [comment]
I ran into the same issue. In my serializer:

```
    payouts = serializers.ListField(child=APIPayoutSerializer())
```

And in the Swagger UI:

![screenshot](https://cloud.githubusercontent.com/assets/5135450/13604312/65a9b946-e542-11e5-90b9-b4f9de75ec18.png)

@respondcreate Have you found a solution for this?

**Comment by davidrenne** [comment]
Change your API to just not use lists of objects and some other kind of
format.

I think I just found a workaround and avoided using them until we fix the
source.

I think I did something like `SerializerClass(many=True)` which I think
outputs lists of the object if I am remembering right?

Am I right that many=True of a complex object will essentially output a
list of those objects?

**Comment by aumayr** [comment]
> I think I did something like `SerializerClass(many=True)` which I think
outputs lists of the object if I am remembering right?

Thanks @davidrenne for the hint! I changed it like this and it works:

```python
    payouts = APIPayoutSerializer(many=True)
```

**Comment by davidrenne** [comment]
HELLLLZZZZ YEA!!!  A WIN FOR PRODUCTIVITY!

We should just take the support for child=XXXXOBJECT in marc's project?
Where maybe it will throw an exception when traversing all serializers?

Maybe a list of strings might work where child=XXXX will output valid
swagger.

Or just raise exception when an complex object serializer and state to use
many=True.

Its just confusing for developers who arent super experienced with DRF to
know that django rest swagger might not be able to output proper
documentation on lists of objects.

I think the natural tendency when you dont know the "many" kwarg is to
express it like you and I did and you will find that things might work in
the DRF testing world, but not in the django-rest-swagger's world (yet).

**Comment by tonioo** [comment]
Hi, I encounter this issue with the following field:
```python
recipients = serializers.ListField(
        child=serializers.EmailField(), allow_empty=False)
```
And the corresponding javascript error:
```javascript
TypeError: param.items is undefined (swagger.js, line 698)
```
Since I can't replace my field with the upper solution (using many=True), does someone know how I could fix this ?

**Comment by Atorich** [comment]
+1

**Comment by gjcarneiro** [comment]
Same problem for, just this simple thing breaks it:
```
serializers.ListField(child=serializers.CharField())
```
Resulting in a JS exception client-side:
```
swagger.js:698 Uncaught TypeError: Cannot read property '$ref' of undefinedSwaggerOperation @ swagger.js:698SwaggerResource.addOperations @ swagger.js:471SwaggerResource.addApiDeclaration @ swagger.js:402obj.on.response @ swagger.js:357res.response @ swagger.js:1324EventEmitter.emit @ shred.bundle.js:1391emit @ shred.bundle.js:1191(anonymous function) @ shred.bundle.js:1211setBodyAndFinish @ shred.bundle.js:1815(anonymous function) @ shred.bundle.js:1832EventEmitter.emit @ shred.bundle.js:1388Response.handle @ shred.bundle.js:2716xhr.onreadystatechange @ shred.bundle.js:2584
2016-04-06 15:02:54.323 swagger.js:698 Uncaught TypeError: Cannot read property '$ref' of undefinedSwaggerOperation @ swagger.js:698SwaggerResource.addOperations @ swagger.js:471SwaggerResource.addApiDeclaration @ swagger.js:402obj.on.response @ swagger.js:357res.response @ swagger.js:1324EventEmitter.emit @ shred.bundle.js:1391emit @ shred.bundle.js:1191(anonymous function) @ shred.bundle.js:1211setBodyAndFinish @ shred.bundle.js:1815(anonymous function) @ shred.bundle.js:1832EventEmitter.emit @ shred.bundle.js:1388Response.handle @ shred.bundle.js:2716xhr.onreadystatechange @ shred.bundle.js:2584
```
```javascript
  for(var i = 0; i < this.parameters.length; i ++) {
    var param = this.parameters[i];
    // might take this away
    param.name = param.name || param.type || param.dataType;

    // for 1.1 compatibility
    var type = param.type || param.dataType;
    if(type === 'array') {
      // CRASH HERE:
      type = 'array[' + (param.items.$ref ? param.items.$ref : param.items.type) + ']';  
    }
    param.type = type;
```
param is an object like this, the crash is because there is no param.items field:
```javascript
{
description:"xxx"
name: "aname"
paramType: "form"
required: true
type:"array"
}
```
I have djangorestframework==3.3.3 and django-rest-swagger==0.3.5.

**Comment by vracheva** [comment]
As a temporary solution it can be fixed by adding docstring to viewset. 
For serializer's field 
`interest_list = serializers.ListField(child=serializers.CharField())`
I use next description

    """
    ViewSet description

    ---
    create:
        serializer: profiles.serializers.ProfileSerializer
        parameters:
            - name: interest_list
              description:
              required: false
              type: array[string]
              paramType: form

The same description is required for `update`, `partial_update` methods

**Comment by tonioo** [comment]
@vracheva It works, thank you!

**Comment by n4cr** [comment]
+1

**Comment by polomaciek** [comment]
Will it be fixed?

**Comment by marcgibbons** [comment]
Closing this out as the Django REST Framework now handles introspection with its schema generator.

**Comment by davidrenne** [comment]
@Ali-aqrabawi my brother and I support swagger without all the comment reflection that this package has. Maybe I'll add something similar if Golang can reflect comments for you.

https://github.com/DanielRenne/GoCore

Just getting an email from you reminds me I need to give swagger some tlc in our package.
