### ISSUE TITLE
Authorizations Object in SWAGGER_CONFIG

### ISSUE THREAD

**Issue by Zundrium** [marcgibbons/django-rest-swagger#371]
The `authorizations` property in the `SWAGGER_CONFIG` doesn't seem to work. ([link](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#511-object-example))

Does the information inside the Authorizations Object need to be valid to show up on the page?

**Comment by soulseekah** [comment]
None of the current two views support the `authorizations` key:

https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/views.py#L104

https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/views.py#L146

**Comment by Zundrium** [comment]
Ah too bad, it's an essential part of the REST documentation. Guess I'll place it inside another page for now. Thanks :+1:
