### ISSUE TITLE
Authorization support?

### ISSUE THREAD

**Issue by huiyiqun** [marcgibbons/django-rest-swagger#372]
I have quickly covered the code and do not find any support for authorization.

1. Is authorization supported?
2. If no, is there any plan?
3. I'd like to implement this feature by implement custom authentication classes.

**Comment by qrilka** [comment]
I guess the problem is around https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/static/rest_framework_swagger/index.html#L56 - `ApiKeyAuthorization` is hardcoded into the Swagger page.
E.g. we need to use `PasswordAuthorization` with our API

**Comment by qrilka** [comment]
The link was a bit incorrect - the real code is in the template, for our project I've just overridden `templates/rest_framework_swagger/base.html` and replaced `ApiKeyAuthorization` with `PasswordAuthorization`

**Comment by marcgibbons** [comment]
Authorization is now customizable in v2 by defining the OpenAPI securityDefinitions object.
