### ISSUE TITLE
Provide wheel package on PyPI

### ISSUE THREAD

**Issue by edmorley** [marcgibbons/django-rest-swagger#373]
Please could you provide a wheel archive on PyPI alongside the standard package? http://pythonwheels.com/

Many thanks :-)

**Comment by ariovistus** [comment]
I attempted to do this for 0.3.5. can someone verify that I succeeded?

**Comment by edmorley** [comment]
Looks good, thank you :-)
https://pypi.python.org/packages/py2.py3/d/django-rest-swagger/django_rest_swagger-0.3.5-py2.py3-none-any.whl#md5=c8788db0e6991c126a0cc4bbb91e4efb
