### ISSUE TITLE
ModelViewSet documentation

### ISSUE THREAD

**Issue by SimoV8** [marcgibbons/django-rest-swagger#374]
Hi, I'm using django-rest-swagger to document my django rest framework API. I'm using the ModelViewSet class and I have a couple of questions for which I didn't find an answer on the documentation: 
- I'm using two view sets with the same prefix (I'm using the NestedSimpleRouter router) and by default swagger put them on the same menu: there's a way to split them in two separate lists?
- for some methods like `list` or `retrieve` I'm using the default implementation, but I would like to add a short description in the documentation so that other developers know how to use them. Is it possible to add a custom description (not the generic one related with the whole ViewSet) without overwriting the method?
- In a ViewSet I'm using `perform_update` instead of `update`, but the documentation in `perform_update` is ignored. There's a way to show it?

Thank you in advance.

**Comment by SimoV8** [comment]
Are these features missing?

**Comment by ankitml** [comment]
The problem with update and partial_update is there. I dont support update in my APIs and have specified it in 

http_method_names of the viewset and not having 'PUT' there. However, there is an endpoint in the swagger documentation of PUT even when it isnt supported.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.

**Comment by davidmir** [comment]
But how can we comment individual actions of the default methods?
