### ISSUE TITLE
Consistent ValueError in 0.3.4 when used with a HashedFilesMixin-based class as STATICFILES_STORAGE

### ISSUE THREAD

**Issue by amrael** [marcgibbons/django-rest-swagger#375]
The error message is
`ValueError: The file '' could not be found with <xxxx.storage.S3HashedFilesStorage object at 0x7f5e67f8b590>.`

This issue is caused by https://github.com/marcgibbons/django-rest-swagger/commit/e460e0a2be87859dbbe3b1fadaeb00b972ba84b2

Passing empty string to static tag is not allowed in HashedFilesMixin.

**Comment by marcgibbons** [comment]
Fixed in latest stable/0.3.x and v2
