### ISSUE TITLE
Should query params from filter appear in methods other than GET (list)?

### ISSUE THREAD

**Issue by cescp** [marcgibbons/django-rest-swagger#377]
I have the following code:
models.py:
```
from django.db import models

class Book(models.Model):
    title = models.CharField( max_length=200 )
```
views.py:
```
import django_filters
from rest_framework import viewsets

class BookFilterSet(django_filters.FilterSet):    
    class Meta:
        model = Book
        fields = ['title',]

class BookViewSet(viewsets.ModelViewSet):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

    # filter
    filter_backends = (DjangoFilterBackend,)
    filter_class = BookFilterSet
```
When swagger documentation is created, field "title" appears in GET (list), GET (retrieve), POST,
PUT, PATCH and DELETE, as Parameter Type: query.
I expected to see it in GET (list), because it is a filter, but not in the other cases.
Am I wrong?

Francesc

**Comment by monk8800** [comment]
Have a look at the docs http://django-rest-swagger.readthedocs.org/en/latest/yaml.html you can use YAML docString to omit_parameters in specific HTTP methods


    class BookViewSet(viewsets.ModelViewSet):
	    """
	    REST end point Description here
	    ---
	    update:
	          serializer: BookSerializer
	          omit_parameters:
	               - query
	      
	    partial_update:
	           serializer: BookSerializer
	           omit_parameters:
	               - query
	      
	    """
 		queryset = Book.objects.all()
    	serializer_class = BookSerializer

	    # filter
	    filter_backends = (DjangoFilterBackend,)
	    filter_class = BookFilterSet

**Comment by cescp** [comment]
Thanks, this is what I wanted!

Francesc

**Comment by sillygod** [comment]
Thanks for the answer. However, I wonder why not just change this part code

```python
def get_parameters(self):
        """
        Returns parameters for an API. Parameters are a combination of HTTP
        query parameters as well as HTTP body parameters that are defined by
        the DRF serializer fields
        """
        params = []
        path_params = self.build_path_parameters()
        body_params = self.build_body_parameters()
        form_params = self.build_form_parameters()
        query_params = self.build_query_parameters()
        if django_filters is not None:
            query_params.extend(
                self.build_query_parameters_from_django_filters())

        if path_params:
            params += path_params

        if self.get_http_method() not in ["GET", "DELETE", "HEAD"]:
            params += form_params

            if not form_params and body_params is not None:
                params.append(body_params)

        #  original
        #  if query_params:
        #     params += query_params
        #  do a simple restrication like the following

        if self.get_http_method() in ["GET"]:
            params += query_params

        return params
```

I don't know any http method needs to consume the query string except GET?

Regards,
Jing

**Comment by smcoll** [comment]
@sillygod i just used a third-party API the other day which used query params in addition to form params for `POST` requests.  They weren't filters, though, so my vote would be:

```
if django_filters is not None and self.get_http_method() == "GET":
    query_params.extend(
        self.build_query_parameters_from_django_filters())
```

Should any other methods be included, like `OPTIONS` or `HEAD`?

**Comment by marcgibbons** [comment]
Closing this out as DRF is now generating the schema / parameters.

**Comment by ranvijay-sachan** [comment]
@sillygod  @marcgibbons I am using latest DRF/Django/Swagger and getting same error can you please take a look: https://stackoverflow.com/questions/48007965/django-swagger-how-to-disable-djangofilterbackend-query-filters-from-delete-pu

**Comment by ranvijay-sachan** [comment]
Here is the solution:

from rest_framework.schemas import AutoSchema
from django.utils.six.moves.urllib import parse as urlparse
import coreapi, coreschema


```
class CustomSchema(AutoSchema):
    def get_link(self, path, method, base_url):
        fields = self.get_path_fields(path, method)
        fields += self.get_serializer_fields(path, method)
        fields += self.get_pagination_fields(path, method)
        if self.view.action in ['list']:
            fields += self.get_filter_fields(path, method)

        manual_fields = self.get_manual_fields(path, method)
        fields = self.update_fields(fields, manual_fields)

        if fields and any([field.location in ('form', 'body') for field in fields]):
            encoding = self.get_encoding(path, method)
        else:
            encoding = None

        description = self.get_description(path, method)

        if base_url and path.startswith('/'):
            path = path[1:]

        return coreapi.Link(
            url=urlparse.urljoin(base_url, path),
            action=method.lower(),
            encoding=encoding,
            fields=fields,
            description=description
        )

class MyUserViewSet(viewsets.ModelViewSet):
    """
    API endpoint that allows users to be viewed or edited.

    """
    model = MyUser
    serializer_class = MyUserSerializer
    queryset = MyUser.objects.all()
    filter_backends = (DjangoFilterBackend, OrderingFilter)
    filter_class = MyUserFilter
    ordering_fields = ('last_name', 'first_name', 'email', 'is_active')
    ordering = ('last_name', 'first_name')
    permission_classes = (IsAuthenticated,)
    schema = CustomSchema()
```

https://stackoverflow.com/questions/48007965/django-swagger-how-to-disable-djangofilterbackend-query-filters-from-delete-pu/48247883#48247883
