### ISSUE TITLE
Django 1.8+ deprecation warning for urlpatterns in urls.py:10

### ISSUE THREAD

**Issue by edmorley** [marcgibbons/django-rest-swagger#380]
Using django-rest-swagger v0.3.4 with Django v1.8.7, and running ` python -Wall manage.py runserver` then loading the site in the browser, I see this deprecation warning in the console:
```python
/home/vagrant/venv/local/lib/python2.7/site-packages/rest_framework_swagger/urls.py:10: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^api-docs/(?P<path>.*)/?$', SwaggerApiView.as_view(), name='django.swagger.api.view'),
```

`urlpatterns` here:
https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/urls.py#L6

...needs updating according to:
https://docs.djangoproject.com/en/1.8/releases/1.8/#django-conf-urls-patterns

**Comment by pquentin** [comment]
@ariovistus Can we get a release with this commit? Even if this was deprecated in 1.8 LTS, the deprecation warnings only started appearing in 1.9, which was released yesterday.

Thanks!
