### ISSUE TITLE
Unable to navigate APis

### ISSUE THREAD

**Issue by Colleoni** [marcgibbons/django-rest-swagger#384]
Hi, thank you for this fantastic plugin. I use it often and I really appreciate the simply way it permits to document API. However, today I have encountered a problem with a serialiser.ListField, which is rendered as string instead of array. I have checked the current master and I have noticed that a solution to this problem has been added. However, when I move from the last stable release to the current master I am not able to navigate my API anymore.
I think some errors have been introduced with commit #367 and #368. I have tried to fix, but unfortunately it seems that I am not able. So I decided to write this issues to inform you of this problem.
Hope you can fix it.

Thanks again,
   Luca

**Comment by marcgibbons** [comment]
Hi - introspection has been moved up to Django REST Framework / CoreAPI. Currently, everything is typed as a string, however, this is being worked on in:
https://github.com/tomchristie/django-rest-framework/issues/4422
