### ISSUE TITLE
Override introspection?

### ISSUE THREAD

**Issue by dtheodor** [marcgibbons/django-rest-swagger#385]
Hi, is it possible to override the introspection behavior?

In particular, I have a custom APIView base class which allows me to declare my views like this

```python
class MyView(APIView):
    request_serializer = Serializer1
    response_serializer = Serializer2
```

I don't want to repeat the serializer information in the docstring; I want to override the introspection behavior to get the serializers directly from the view class variables.

Is this possible? I see something similar to this using this `'view_mocker'` functionality (which looks like a _very_ weird way to override behavior unless I don't understand what it is trying to solve), but the view mocker only supports getting a single serializer, not different ones for request/response.

I was expecting to find something like choosing the introspection class at settings level, but I don't see any such option. Any thoughts on this?

**Comment by marcgibbons** [comment]
Likely this could be solved by using read_only and write_only fields on the serializer rather than using 2 different classes.

DRF is now responsible for schema generation as of 3.4.

**Comment by dtheodor** [comment]
> Likely this could be solved by using read_only and write_only fields on the serializer rather than using 2 different classes.

But the request data is a completely different thing than the response data, why would I put these two different data structures in the same serializer?

> DRF is now responsible for schema generation as of 3.4.

No clue what this means or how this helps, can you elaborate?

**Comment by marcgibbons** [comment]
@dtheodor Sure. Django REST Framework has a new feature in 3.4 which auto-generates a documentation schema for the REST API; the responsibility for introspection and overrides is now handled by DRF, whereas this project is responsible for rendering.

See:
http://www.django-rest-framework.org/api-guide/schemas/
http://www.coreapi.org/
