### ISSUE TITLE
Update urlpatterns to be a list of django.conf.urls.url() instances

### ISSUE THREAD

**Issue by Woile** [marcgibbons/django-rest-swagger#387]
Hello guys, django.conf.urls.patterns() is deprecated and will be removed in Django 1.10, as the DeprecationWarning says: "Update your urlpatterns to be a list of django.conf.urls.url() instances instead."
The file is rest_framework_swagger/urls.py

**Comment by angvp** [comment]
This was fixed on 7ea0e2d8387b622f671638613a476dcbff6438e1
