### ISSUE TITLE
custom RelatedField serializers shown as string

### ISSUE THREAD

**Issue by jowenn** [marcgibbons/django-rest-swagger#389]
I think it is somehow related to https://github.com/marcgibbons/django-rest-swagger/issues/361
but it is not exactly the same issue.

I have a Model serializer with a related field and a customer serializer for that field:
Basically it is something like:

class MaterialAmountAvailableField(serializers.RelatedField):
    def to_representation(self, value):
        return value.value

class MaterialInfoSerializerBase(serializers.ModelSerializer):
    amount_available=MaterialAmountAvailableField(source="stock_counter",read_only=True)
    class Meta:
        fields=('m_id','m_name','amount_available')
        read_only_fields=('m_id','m_name','amount_available')

My problem is that amount_available is shown as string always. I think this is caused by introspectors.py: 
def get_data_type(field)

It would be nice, if this great library  would support RelatedField and for instance allow setting a custom field swagger_datatype="int" to set the type of the related field. 

Right now I have to set the whole datatype description in yams and set the omit_serializer: true option, which works but is a littlebit ugly.

If the idea or handling that is okay, I would try to come back with a pull request, when I have some time

**Comment by marcgibbons** [comment]
@jowenn I'm not sure how this could be accomplished. It might be worth asking for this feature on Django REST Framework. Maybe an argument like `ouput_field` like on Django model expressions could satisfy this.
Many thanks!
