### ISSUE TITLE
Upgrading this package breaks existing setup because of the required package definitions

### ISSUE THREAD

**Issue by iambibhas** [marcgibbons/django-rest-swagger#391]
My project uses Django 1.7.* and DRF 2.4.*.

Today I started upgrading with `pip install --upgrade django-rest-swagger`, it started to download Django 1.9, because
```
install_requires = [
    'django>=1.5',
    'djangorestframework>=2.3.8',
    'PyYAML>=3.10',
]```

Any way to make pip upgrade just this package somehow?

**Comment by cancan101** [comment]
I had a similar issue, but I believe this can be solved by installing django-rest-swagger at the same time as a pinned version of django.
