### ISSUE TITLE
Read only API in documentation?

### ISSUE THREAD

**Issue by whoisearth** [marcgibbons/django-rest-swagger#394]
I've set the following as my swagger config - 

setttings.py

    'enabled_methods': [
        'get'
    ],

I'm also limiting my rest framework to Read Only:

    'DEFAULT_PERMISSION_CLASSES': ('rest_framework.permissions.IsAuthenticatedOrReadOnly',),

But the problem is when I go to the API docs it's still showing documentation for everything but get which I don't want.

Is there a way to limit the documentation to only show for GET?

**Comment by monk8800** [comment]
I dont think this has been addressed yet. similar question can be found here 
https://github.com/marcgibbons/django-rest-swagger/issues/142

**Comment by marcgibbons** [comment]
As of v2, the schema is provided by DRF. There is an option to pass in the request object into the schema generator which will filter out endpoints which require authentication unless the user is logged in.
