### ISSUE TITLE
Multiple response type: docstring tags break

### ISSUE THREAD

**Issue by RobinPeens** [marcgibbons/django-rest-swagger#396]
If i create a docstring as per below for one API endpoint it works as expected showing the full json for the results once i have more than one endpoint this no longer works as expected:
type: 
          success:
            required: true
            type: boolean
          message:
            required: true
            type: string
          results:
            required: false
            type: array
            items:
                type: LogDataSerializer

**Comment by marcgibbons** [comment]
DRF is now responsible for generating the schema, YAML docstrings are deprecated. Closing out.
