### ISSUE TITLE
Context (inc request) should be passed to serializer in introspection

### ISSUE THREAD

**Issue by stevelacey** [marcgibbons/django-rest-swagger#397]
I use `kwargs['context']['request']` in my serializer `__init__`'s in order to restrict querysets based on the users access privileges and remove some superuser-only fields.

This fails with django-rest-swagger since no context is passed in:

https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/introspectors.py#L424

Could/should a context with a fake request (inc user) be passed into serializers similarly to how it is done in views?

https://github.com/marcgibbons/django-rest-swagger/blob/0.3.4/rest_framework_swagger/introspectors.py#L226-L228

**Comment by dpaluch-rp** [comment]
Hello,
I think there is better idea than solutions in: https://github.com/marcgibbons/django-rest-swagger/issues/328

**Comment by ezheidtmann** [comment]
I would also use this; my case is that I limit available fields based on the scope attached to OAuth tokens. So I need access to the request (with token) in the serializer. 

As a workaround, is it possible to override the introspection methods for a viewset?

**Comment by ezheidtmann** [comment]
I found a workaround in my situation: If the context is not provided, I don't show any fields. Swagger continues to show all fields, which is OK.

Evan

**Comment by marcgibbons** [comment]
DRF 3.4 is now responsible for schema generation and uses request context.
