### ISSUE TITLE
Not able to show array with limited length info.

### ISSUE THREAD

**Issue by smills2929** [marcgibbons/django-rest-swagger#400]
I am using a length 2 array [x, y] for POSTing location data to the api. How do I specify that it is both length 2, and in the [x, y] format? Currently the type is just 'string' which doesn't tell users very much.

If this isn't possible, any ideas how I could inform users of the format of that array variable?

**Comment by marcgibbons** [comment]
Typing is coming in https://github.com/tomchristie/django-rest-framework/issues/4422.
However, afaik, an array with a limited length is not supported by SwaggerUI.
