### ISSUE TITLE
displayed endpoint url list is not sorted

### ISSUE THREAD

**Issue by megapctr** [marcgibbons/django-rest-swagger#401]
URLs are displayed in order they're registered, which may not be sorted (e.g. when using `drf-nested-routers`)

example:
```
GET  /api/v1/foos/{foo_pk}/bars/{pk}/
POST /api/v1/foos/{foo_pk}/bars/{pk}/
GET  /api/v1/foos/{foo_pk}/eggs/
POST /api/v1/foos/{foo_pk}/eggs/
GET  /api/v1/foos/{foo_pk}/bars/{bar_pk}/spam/
POST /api/v1/foos/{foo_pk}/bars/{bar_pk}/spam/
```

It would be much easier to read docs if urls were sorted

**Comment by Skorpyon** [comment]
Same issue. OrderedDict in Router httpmethods don't save.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating the schema and will set the order v2. However, SwaggerUI does have an option to sort operations and tags. Will be adding support for this shortly.

**Comment by marcgibbons** [comment]
As of 2.0.4, it is now possible to sort the endpoints using 
`APIS_SORTER` to `alpha`
http://marcgibbons.github.io/django-rest-swagger/settings/#swaggerui-settings
