### ISSUE TITLE
How to show my REST APIs by rest_framework_swagger?

### ISSUE THREAD

**Issue by thomasliub** [marcgibbons/django-rest-swagger#402]
I am new for rest_framework_swagger. I wonder my REST APIs showed by rest_framework_swagger by following http://django-rest-swagger.readthedocs.org/en/latest/. I am using Django REST framework with view APIView. Followed the quick start steps, I can see the swagger page. But there is a problem to show the model schema for PUT, POST. (Even no window to set the data body)

Implementation Notes
    Org list view
Response Class
    ModelModel Schema
    object
Do I need to write a model schema for swagger? Or what other configurations I need?

**Comment by marcgibbons** [comment]
Were the post/put methods defined on the view?
