### ISSUE TITLE
Unable to generate Docs on model with ArrayField

### ISSUE THREAD

**Issue by ppiccolo** [marcgibbons/django-rest-swagger#403]
Hi, 

if my model use the django.contrib.postgres.fields ArrayField drf swagger silently fail and no docs are generated on the web interface ... only links to registered endpoint 

bye

**Comment by pbassut** [comment]
+1

**Comment by larubbio** [comment]
I'm getting a similar error using a field defined like this:

```
    participants = serializers.ListField(
        child=serializers.IntegerField()
    )
```

I get the following error from swagger in my browser:

```
Uncaught TypeError: Cannot read property '$ref' of undefined
```

This is the raw json that is generated for that field:

```
{  
  "name":"participants",
  "paramType":"form",
  "required":true,
  "type":"array",
  "description":""
},
```

I think the issue that is being hit is:

https://github.com/swagger-api/swagger-js/issues/85

and to fix it a type would need to be set for the inner type of the array

**Comment by gcko** [comment]
can you please check if this PR #414 takes care of this issue for you?

**Comment by ivanvenosdel** [comment]
@gcko That PR doesn't fix the issue for us.

**Comment by aiboy** [comment]
Any progress so far?

**Comment by marcgibbons** [comment]
Should be fixed in latest 0.3.6

**Comment by alfdev** [comment]
I have the same issue even with latest version django-rest-swagger==0.3.6

**Comment by nass600** [comment]
Any update on this?

**Comment by marcgibbons** [comment]
Many changes have been made since this issue was opened; currently in v2, only strings are supported, however, typing is coming in DRF 3.5. https://github.com/tomchristie/django-rest-framework/issues/4422

**Comment by marcgibbons** [comment]
In the latest version, application/json is used by default and data is posted in the request body. This allows the input of arbitrary data types not typically suited for form data.
