### ISSUE TITLE
reStructuredText docs not rendering

### ISSUE THREAD

**Issue by carsongee** [marcgibbons/django-rest-swagger#407]
I followed the documentation for doing reStructuredText doc strings, and it works fine in the django rest framework docs:
![image](https://cloud.githubusercontent.com/assets/596029/12817103/4d6a1abc-cb1e-11e5-8829-028f28bbd9cd.png)

but in the swagger docs it doesn't render:
![image](https://cloud.githubusercontent.com/assets/596029/12817132/6bfc2c90-cb1e-11e5-98ef-dfb0da06515d.png)

What I found interesting is that if I install markdown, the docs do get rendered as markdown, which sort of works.  It seems to me that there is probably just one place it isn't calling the DRF `VIEW_DESCRIPTION_FUNCTION` callable, but I couldn't find it easily.

here are the pip freeze related packages
```
django-rest-swagger==0.3.5
djangorestframework==3.3.2
```
I'm happy to write the code if someone can point me at the possible places this might be happening, and thanks so much for the awesome project!

**Comment by javiromero** [comment]
Hey @carsongee did you found anyway to solve this problem?
```
docutils==0.12
django-rest-swagger==0.3.6
djangorestframework==3.3.3
```

**Comment by carsongee** [comment]
I'm afraid not, we are still just using the markdown rendering which makes it more readable but still not great:
![image](https://cloud.githubusercontent.com/assets/596029/14936716/e1d910c2-0ec1-11e6-94be-3e9d8f1e9493.png)

**Comment by marcgibbons** [comment]
Yaml docstrings have been deprecated as of v2, so won't be supporting a fix. Thank you!
