### ISSUE TITLE
Support for custom routers

### ISSUE THREAD

**Issue by woegjiub** [marcgibbons/django-rest-swagger#408]
Currently, `rest_framework_swagger.urlparser.UrlParser` uses a hardcoded value to determine if an endpoint is a router.

This is done by comparing the view's` __module__` to `rest_framework.routers`.

This will return false if the user has replaced the router with a subclass.

Simply checking the `__name__` against `APIRoot` works, but feels less than ideal. Depending on how acceptable the overhead is, it may be worth doing a check on the `__mro__` to see if `rest_framework.routers.DefaultRouter.get_api_root_view().APIRoot` is in there, but as it's dynamically generated, that will still involve string comparisons.

**Comment by marcgibbons** [comment]
This is now supported in DRF 3.4
