### ISSUE TITLE
Problem with custom CSRF cookie name

### ISSUE THREAD

**Issue by 43ndr1k** [marcgibbons/django-rest-swagger#412]
I'm using the Python package django-rest-swagger with Django 1.9.2 and encounter problems while making a POST requests.
The API returns the error: "CSRF Failed: CSRF token missing or incorrect."

I looked at the request headers and the header looks like this:
X-CSRFToken:[object Object]

The object seems to be undefined.
How can I solve this problem?

 My javascript in the rest_framework_swagger index.html file:

  $(function () {
      window.swaggerUi = new SwaggerUi({
      url: "{{ swagger_settings.discovery_url }}",
      apiKey: "{{ swagger_settings.api_key }}",
      dom_id: "swagger-ui-container",
      supportedSubmitMethods: {{ swagger_settings.enabled_methods }},
      onComplete: function(swaggerApi, swaggerUi){
        log("Loaded SwaggerUI")
        $('pre code').each(function(i, e) {hljs.highlightBlock(e)});
      },
      onFailure: function(data) {
        log("Unable to Load SwaggerUI");
      },
      docExpansion: "{{ swagger_settings.doc_expansion }}",
    });

    $('#input_apiKey').change(function() {
      var key = $('#input_apiKey')[0].value;
      log("key: " + key);
      if(key && key.trim() != "") {
        console.log("added key " + key);
        window.authorizations.add("key", new ApiKeyAuthorization("Authorization", "{{ swagger_settings.token_type }} " + key, "header"));
      }
    })
    {% if swagger_settings.api_key %}
      window.authorizations.add("key", new ApiKeyAuthorization("Authorization", "{{ swagger_settings.token_type }} " + "{{ swagger_settings.api_key }}", "header"));
    {% endif %}
    window.swaggerUi.load();
  });

**Comment by marcgibbons** [comment]
This should now be fixed in v2.
