### ISSUE TITLE
Authorizations Object

### ISSUE THREAD

**Issue by davidrenne** [marcgibbons/django-rest-swagger#415]
https://github.com/OAI/OpenAPI-Specification/blob/master/versions/1.2.md#514-authorizations-object

Any ideas on how I can change the code base to support this?

Ideally somehow I could express certain methods in my YAML which do not need authentication.  Such as methods which are to create new authTokens.

Any ideas on where in the code I can play with this to add this and how I might design this to add new keys to YAML would be appreciated. 

It would add value to my project because I use restunited.com and when I import my DRF swagger doc url into their system, I always have to manually create the authentication record and assign to all my methods and then remove the authentication association for my authTokenCreate method.

**Comment by marcgibbons** [comment]
This can now be achieved in v2 by configuring the securityDefinitions setting.
http://marcgibbons.github.io/django-rest-swagger/settings/#authentication
