### ISSUE TITLE
swagger not show when view have custom decorator

### ISSUE THREAD

**Issue by truonghoangnguyen** [marcgibbons/django-rest-swagger#426]
1. create decorator function
```
def platform_required(function):
    def wrapper(*args, **kwargs):
        return function(*args, **kwargs)
    return wrapper
```
2. view add decorator
```
@api_view(['POST'])
@platform_required
def authen_google(request):#, platform):
    """
     Login  googke
    ---
    parameters:
        - name: clientId
          description: client id
  """
```
result:
![image](https://cloud.githubusercontent.com/assets/1657877/14311238/8a285202-fc10-11e5-8893-9ac83fcb97f5.png)

**Comment by mkurnikov** [comment]
Add `functools.wraps` decorator to the inner function wrapper in the decorator implementation: 
```
from functools import wraps
def platform_required(function):
    @wraps(function)
    def wrapper(*args, **kwargs):
        return function(*args, **kwargs)
    return wrapper
```
It will set original function docs to the wrapper.

**Comment by rishikesh67** [comment]
> Add `functools.wraps` decorator to the inner function wrapper in the decorator implementation:
> 
> ```
> from functools import wraps
> def platform_required(function):
>     @wraps(function)
>     def wrapper(*args, **kwargs):
>         return function(*args, **kwargs)
>     return wrapper
> ```
> 
> It will set original function docs to the wrapper.

This is an excellent answer. I appreciate this.

**Comment by hygull** [comment]
> Add `functools.wraps` decorator to the inner function wrapper in the decorator implementation:
> 
> ```
> from functools import wraps
> def platform_required(function):
>     @wraps(function)
>     def wrapper(*args, **kwargs):
>         return function(*args, **kwargs)
>     return wrapper
> ```
> 
> It will set original function docs to the wrapper.

I liked this. It's an excellent answer to get rid of the issue.
