### ISSUE TITLE
Opening the docs makes 2 requests for each endpoint

### ISSUE THREAD

**Issue by mochawich** [marcgibbons/django-rest-swagger#440]
This issue isn't new I have had it since I started using DRF Swagger. I always wondered if this is a wrong configuration from my side or something else.

![](http://i.imgur.com/ss7GYMq.png)

As you can see for each endpoint two requests were made, they are identical indeed by looking at the response size.

**Comment by marcgibbons** [comment]
@mochawich This should be going away in v2 as the spec will be rendered to a single file rather than issuing requests for every single endpoint. Not sure what is causing these duplicates though...

**Comment by monk8800** [comment]
@marcgibbons when will version 2 be released ? I noticed the same thing, i too thought perhaps something to do with the way i configured swagger.

**Comment by mochawich** [comment]
@marcgibbons thank you!
looking forward v2. Closing this for now
