### ISSUE TITLE
pytype for array

### ISSUE THREAD

**Issue by pauk-slon** [marcgibbons/django-rest-swagger#442]
Using `pytype` as a type for item of array does not work. 

Example:

    parameters:
        - name: body
          paramType: body
          type: array
          items:
            pytype: MySerializer

`Data Type` will be represented as `array[string]` instead of expecting pretty serializer description.

**Comment by jmhobrien** [comment]
I'm seeing this limitation as well. Looking forward to a solution.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema. Closing out.
