### ISSUE TITLE
How can I change the documented type of a SerializerMethodField?

### ISSUE THREAD

**Issue by ezheidtmann** [marcgibbons/django-rest-swagger#445]
I have a serializer like this:

```python
class ThingSerializer(serializers.ModelSerializer):
    is_ok = serializers.SerializerMethodField()

    def get_is_ok(self, thing):
        return True
```

I'd like the generated documentation to say that this is a `boolean` field, but it currently says it's a `string`.

I've tried adding a `type` key to my ViewSet's yaml docstring, but that completely overrides all the field information, which I'd like to avoid.

It looks like there's no way to override the field type, but I'm hoping I'm wrong. Thanks for any help.

Evan

**Comment by alexislg2** [comment]
Same issue here

**Comment by marcgibbons** [comment]
DRF 3.4 is now responsible for schema generation.

**Comment by DataGreed** [comment]
@marcgibbons so what's is the right way to do it with DRF?
