### ISSUE TITLE
API under / is not rendered properly 

### ISSUE THREAD

**Issue by stankiewicz** [marcgibbons/django-rest-swagger#446]
Hi
I've setup urls like below:
```
urlpatterns = [
    url(r'^docs/', include('rest_framework_swagger.urls')),
    url(r'^uk_postcode/', include(postcodes_urls)),
    url(r'^/', include(postcodes_urls))
]
```
postcodes_urls is as follows:
```
urlpatterns = [
    url(r'^/$',
        UKPostcodeValidateView.as_view(),
        name='validate_uk_postcode'),
]
```
Problem:
1) Rendering is invalid:

<img width="600" alt="swagger-django" src="https://cloud.githubusercontent.com/assets/8183568/15261525/5d1e4054-195d-11e6-9f4e-6ee2fa39d66d.png">

2) /api/docs response contains lists of apis (including / ) :
```
{"info":{"description":"","license":"","title":"","contact":"","termsOfServiceUrl":"","licenseUrl":""},"basePath":"http://127.0.0.1:8000/docs/api-docs","swaggerVersion":"1.2","apiVersion":"0.1","apis":[{"path":"/"},{"path":"/uk_postcode"}]}
```
and when iterating over nested apis documents (/docs/api-docs/uk_postcode) it calls again /docs/api-docs/ 

is it valid issue?

**Comment by marcgibbons** [comment]
I am not sure I understand the problem. However, the schema generation has changed in v2 and is now handled by Django REST Framework.
