### ISSUE TITLE
Empty {% static %} tag in base.html leads to errors with django-storages

### ISSUE THREAD

**Issue by ddemid** [marcgibbons/django-rest-swagger#447]
[`window.static_url = "{% static '' %}";`](https://github.com/marcgibbons/django-rest-swagger/commit/e460e0a2be87859dbbe3b1fadaeb00b972ba84b2)

Error
`ValueErrorboto.s3.bucket in new_key
errorEmpty key names are not allowed`

I believe this is not the best usage of static tag. Why STATIC_URL wasn't OK?

**Comment by marcgibbons** [comment]
Fixed
