### ISSUE TITLE
Errors with Django 1.10

### ISSUE THREAD

**Issue by tarkatronic** [marcgibbons/django-rest-swagger#452]
I get the following when I added Django 1.10a1 to my tox environment:

```
.tox/py27-django110/lib/python2.7/site-packages/rest_framework_swagger/urls.py:2: in <module>
    from rest_framework_swagger.views import SwaggerResourcesView, SwaggerApiView, SwaggerUIView
.tox/py27-django110/lib/python2.7/site-packages/rest_framework_swagger/views.py:8: in <module>
    from django.shortcuts import render_to_response, RequestContext
E   ImportError: cannot import name RequestContext
```

I believe this is because `RequestContext` is supposed to come from `django.template`, not `django.shortcuts`.

https://docs.djangoproject.com/en/1.9/ref/templates/api/#django.template.RequestContext

AFAIK, changing this should be fully backward compatible.

**Comment by asadeque** [comment]
Thanks, it works

**Comment by aj07mm** [comment]
I'm getting this after the changes you mentioned:

```
from rest_framework_swagger.views import get_swagger_view
ImportError: cannot import name get_swagger_view
```
django 1.10.3

**Comment by tarkatronic** [comment]
@aj07mm I believe that is an unrelated issue: https://github.com/carltongibson/django-filter/issues/567
