### ISSUE TITLE
Separate docs for separate groups of apps.

### ISSUE THREAD

**Issue by f1shear** [marcgibbons/django-rest-swagger#454]
Is it possible to generate more than one  swagger api documentation  like api1 and api2 in same django project ?
The api1 and api2  deals with almost mutually exclusive apps inside django project.

**Comment by marcgibbons** [comment]
@f1shear Currently no, but I am planning on doing this in v2. #443

**Comment by marcgibbons** [comment]
Now available in v2. By creating multiple schema_views based on specific urlpatterns, multiple SwaggerUIs can be rendered in a project.
