### ISSUE TITLE
`request_serializer` option doesn't work for GET queries

### ISSUE THREAD

**Issue by swapnilsm** [marcgibbons/django-rest-swagger#455]
Setting the `request_serializer` option for GET queries doesn't show query parameters. While it works for POST queries and displays the parameters as form inputs.

**Comment by marcgibbons** [comment]
@swapnilsm Yes, this isn't currently supported. However, a form will be generated if you are using filters.

You can also create form fields by doing the following in the docstring:
```
class MyView(APIVIew):
    """
    My great description

    param1 -- Param1 description
    """
```
Hope this helps!

**Comment by swapnilsm** [comment]
Yes I looked into the code and figured that out. I am happy to implement
this feature and create pull request if you allow me to.
Please let me know if you have any other plans for this.

**Comment by panchicore** [comment]
+1

**Comment by marcgibbons** [comment]
Going to close this out. DRF 3.4 now handles schema generation.
