### ISSUE TITLE
Allow to set Selialiser name in documentation

### ISSUE THREAD

**Issue by Skorpyon** [marcgibbons/django-rest-swagger#458]
I didn' found a way how to set Serializer name in documentation.
Really, sometime, I don't want show a real Serializer name, __BaseCustomerProfilePOSTWithRestrictrictionsSerializer__.
Need feature to set visible name.

It may be realized with some update, for example:

```python
class IntrospectorHelper(object):
...
@staticmethod
    def get_serializer_name(serializer):
    ...
        if inspect.isclass(serializer):
            if hasattr(serializer, 'Meta') and hasattr(serializer.Meta, 'swagger_name'):
                return serializer.swagger_name
            return serializer.__name__

        return serializer.__class__.__name__
````

This way allow to set visible name of Serializer.
```python
class BaseCustomerProfilePOSTWithRestrictrictionsSerializer(serializers.MmodelSerializer):
    class Meta:
        swagger_name = 'CustomerProfile'
````

**Comment by marcgibbons** [comment]
This no longer in v2; DRF is responsible for generating the schema.
