### ISSUE TITLE
Change the name in 'Response Class' -> 'Model'

### ISSUE THREAD

**Issue by pfertyk** [marcgibbons/django-rest-swagger#463]
I have the following API view:

```python
from rest_framework.authtoken.views import ObtainAuthToken


class UglyAPILoginClassName(ObtainAuthToken):
    def post(self, request):
        """
        Short description
        ---
        type:
          token:
            type: string
            required: true
          full_name:
            type: string
            required: true
        """
        return Response({
            'token': 'token123',
            'full_name': 'John Doe'
        })
```
which I later use like this:
```python
url(r'^ugly-token-auth/', UglyAPILoginClassName.as_view(), name='ugly_login'),
```

Swagger creates the following:
![swagger_ugly](https://cloud.githubusercontent.com/assets/11876747/16374977/4c09d82c-3c59-11e6-9c7e-2589a91d6094.png)

Under 'Response Class' -> 'Model' you can see an automatically generated name `UglyAPILoginClassNamePostResponse`. It looks terrible. I would like to hide it somehow from users. How can I do that? Can I specify another name in the docstring? Or maybe hide the name (leaving just the curly braces and everything between them)? Or can I hide the 'Model' tab, leaving only 'Model Schema'?

**Comment by marcgibbons** [comment]
DRF is now responsible for generating the schema and setting these properties.
