### ISSUE TITLE
#Not working on production deployed on aws. if debug is true works on localhost  else fails on localhost as well.

### ISSUE THREAD

**Issue by Applebit** [marcgibbons/django-rest-swagger#464]
//settings.py
`

import os
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SECRET_KEY = '-lyhc0klqecyn(c-8m3$+e!xmjm^vmva_9quqvo&ga7qyq0))i'

#DEBUG = True

ALLOWED_HOSTS = ['.mozioservice.us-west-2.elasticbeanstalk.com', '.localhost']

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'serviceprovider',
    'rest_framework',
    'rest_framework_swagger',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MozioServiceManager.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MozioServiceManager.wsgi.application'

if 'RDS_HOSTNAME' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': os.environ['RDS_DB_NAME'],
            'USER': os.environ['RDS_USERNAME'],
            'PASSWORD': os.environ['RDS_PASSWORD'],
            'HOST': os.environ['RDS_HOSTNAME'],
            'PORT': os.environ['RDS_PORT'],
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'
`
//urls.py
`
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('serviceprovider.urls')),
    url(r'^docs/', include('rest_framework_swagger.urls')),
]
`

![screenshot from 2016-06-28 01-25-47](https://cloud.githubusercontent.com/assets/11220070/16393685/4e9920d6-3ccf-11e6-8f30-6bc629eec5e9.png)

Please help.
Thanks

**Comment by marcgibbons** [comment]
@Applebit This is probably happening because you have not configured static files. By default, Django won't serve staticfiles when DEBUG=False. Are you able to see other pages, like the Django admin, for example?

See: https://docs.djangoproject.com/en/1.9/howto/static-files/#serving-static-files-during-development

Hope this helps!

P.S. Make sure you change your secret key in production, since it is now it has been exposed for the world to see!

**Comment by Applebit** [comment]
Thanks Bro, I got the point. I must have google before report bug my apologies.

Thanks for help :)

**Comment by marcgibbons** [comment]
All good!
