### ISSUE TITLE
Is django version 1.7.1 necessary?

### ISSUE THREAD

**Issue by djKooks** [marcgibbons/django-rest-swagger#471]
When I run runtests.py, I see a problem like below.

```
...
module 'html.parser' has no attribute 'HTMLParseError'
...
```

It is not appearing on django 1.9.x version, which I am using on my project. Is this version necessary for this project?

**Comment by dyroffk** [comment]
Related to this I'm wondering why Django 1.7.1 is defined in [requirements.txt](https://github.com/marcgibbons/django-rest-swagger/blob/develop/requirements.txt#L1), but Django >=1.8 is in [setup.py](https://github.com/marcgibbons/django-rest-swagger/blob/develop/setup.py#L41)

Which is the actual minimum requirement?

**Comment by djKooks** [comment]
@dyroffk I'm not sure, but 1.9.x looks fine too until I tested on.

**Comment by marcgibbons** [comment]
Dropped support in 0.3.9 / v2
