### ISSUE TITLE
ReStructuredText - Summary breaks down when there's a class reference.

### ISSUE THREAD

**Issue by Attil** [marcgibbons/django-rest-swagger#472]
Hello,

Thanks for your library! It's really useful.

When using RST to generate documentation from docstrings, an error is sometimes encountered which results in the following message in summary.
```
 A viewset for the :py:class:`~ System Message: WARNING/2 (, line 1); backlink Inline interpreted text or phrase reference start-string without end-string.
```

I've managed to track it down.

Because `rest_framework_swagger.introspectors.get_summary` splits on dots, something like ``py:class:`~.Dish`` will be cut in half, which results in ``py:class:`~``, which is of course not valid RST syntax.

Are there any workarounds for this issue?

**Comment by marcgibbons** [comment]
Thank you! The docstrings have been completely deprecated as of v2, so this should no longer be an issue.
