### ISSUE TITLE
How to represent a dictionary for Swagger UI

### ISSUE THREAD

**Issue by vaibhavshah846** [marcgibbons/django-rest-swagger#474]
Hi,
I have a Django REST API GET method that would return a dictionary as a respose as follows:
```
{
  "page" : 
          {
            "id ": 123
          } 
}
```
I am trying to document that API GET method using swagger as follows:

```
'''
            Get the details of a particular Page.
            This API returns the details of a particular Page page_id belonging to the Guest Campaign tracking_id.
            ---
            type:
                page:
                    id:
                        required: true
                        type: integer

            responseMessages:
                -   code: 200
                    message: Success
                -   code: 404
                    message: Guest Campaign or Guest Page does not exist or Page Not Found
                -   code: 500
                    message: Exception occured at server

            produces:
                - application/json
        '''
```

But its getting rendered in the Swagger UI as shown in the below screenshots:
![swag1](https://cloud.githubusercontent.com/assets/20414624/16794528/e317c960-48f5-11e6-8062-3c9dbee9b957.png)
![swag2](https://cloud.githubusercontent.com/assets/20414624/16794532/ea747ad2-48f5-11e6-9b66-2dc423b79524.png)

Why is it showing the page field under Model as undefined and an empty dictionary under ModelSchema?

How to accomplish what I want?

Please Help.

**Comment by marcgibbons** [comment]
DRF is now responsible for generating schema in version 3.4 and is supporting pagination.
