### ISSUE TITLE
ImportError: cannot import name duration_string (DRF 3.4.0)

### ISSUE THREAD

**Issue by madEng84** [marcgibbons/django-rest-swagger#476]
Hi,
With the new version of Django rest framework (3.4.0) there is an import error.

> docgenerator.py [line 6]

`from rest_framework.compat import duration_string` 

n.b.
I'm using django-rest-swagger==0.3.8 (actually latest pip version)

**Comment by marcgibbons** [comment]
@madEng84 Thanks for flagging this. I've updated PyPI to default to 2.0.0. I will backport a fix for 0.3.x series.

**Comment by marcgibbons** [comment]
@madEng84 I was unable to find `duration_string` anywhere in the codebase. Can you provide a full stack trace?

**Comment by marcgibbons** [comment]
Closing this out. Please reopen if still having problems.
