### ISSUE TITLE
Error in host

### ISSUE THREAD

**Issue by vtisnado** [marcgibbons/django-rest-swagger#482]
Hi, 
I'm getting an error in the Swagger API page at the end of the page near [ BASE URL: ]. Checking in the online validator says that the host is empty. 

There is any configuration I forgot in the settings.py? I'm sorry if this is not the place to put this question, but I can't find any related info in the documentation and examples. Thanks in advance.

```
{
   "schemaValidationMessages":[
      {
         "level":"error",
         "domain":"validation",
         "keyword":"pattern",
         "message":"ECMA 262 regex \"^[^{}/ :\\\\]+(?::\\d+)?$\" does not match input string \"\"",
         "schema":{
            "loadingURI":"#",
            "pointer":"/properties/host"
         },
         "instance":{
            "pointer":"/host"
         }
      }
   ]
}
```

You can check the error here: http://loyalty.copiaypega.net/doc/

**Comment by tomchristie** [comment]
Did you resolve this issue. (I see the link is now loading correctly)

**Comment by rloomans** [comment]
I'm still getting this issue at https://measuremate.herokuapp.com/docs/

**Comment by marcgibbons** [comment]
@tomchristie @rloomans I've fixed in a feature branch but haven't had the chance to push it up yet. It's a bit hacky; I'm setting the host by using the renderer_context's request.get_host inside the renderer. Hoping to have some time to push this week/weekend.

**Comment by tomchristie** [comment]
> It's a bit hacky; I'm setting the host by using the renderer_context's request.get_host inside the renderer.

Okey doke. That sounds like a reasonable enough approach, although let me know if you'd like a second set of eyes on it. Really we ought to make sure that you can get the host information from the `Document` url.

**Comment by marcgibbons** [comment]
@tomchristie Agreed. Ideally, the url would be set by the `SchemaGenerator` and do so dynamically based on the schema view's request. Since it's optional on the generator though, how do you think it could be accomplished?

**Comment by tomchristie** [comment]
Perhaps this?...

1. Attempt to get it from `Document.url`.
2. Fallback to getting it from the request in the renderer context.

Also an option that we *could* make the `request` argument in `get_schema` be mandatory, and only ever generate schemas from with view code.

**Comment by marcgibbons** [comment]
@tomchristie 👍  for the fallback.
 
Making the request mandatory for the schema generation might be a good idea, not only for solving this particular problem, but also to support views which multiple serializer classes based on an evaluation of the `request.user` for example.

The downside is that users would have to be logged in to view the schema for endpoints which don't allow anonymous access. Perhaps this could be controlled with a boolean on the generator (i.e. `filter_by_user`) rather than explicitly including/excluding the request?

**Comment by tomchristie** [comment]
Ah yeah, I'd rather forgotten about the use case of "present all the information, even if the current user does not have permissions to all the endpoints".
