### ISSUE TITLE
yaml specifications in __pydoc__ are ignored

### ISSUE THREAD

**Issue by prinsherbert** [marcgibbons/django-rest-swagger#492]
There is nothing in the documentation on this, for example:

How to set 'produces' or how to specify optional parameters and their value restrictions.

**Comment by marcgibbons** [comment]
@prinsherbert The YAML docstring implementation has been deprecated in v2, and schema generation is handled by DRF.  
See: http://www.django-rest-framework.org/api-guide/schemas/

This is actively being developed and overriding features will be rolled out incrementally both in DRF and here. You can still use 0.3.x series in the meantime if you need to.
