### ISSUE TITLE
function based views cause get_serializer_class error

### ISSUE THREAD

**Issue by rainyday** [marcgibbons/django-rest-swagger#501]
It seems that If I have any class based views at all in my application then the entire swagger page fails to load properly and I get `AttributeError: 'view_name' object has no attribute 'get_serializer_class'`

Am I doing something wrong here or does swagger just not work if you use any function based views?

**Comment by marcgibbons** [comment]
@rainyday This is likely related to https://github.com/tomchristie/django-rest-framework/issues/4265 which has been resolved in 3.4.1. Can you confirm?

**Comment by rainyday** [comment]
The exact error seems to be fixed but I'm now getting AttributeError when accessing attributes like self.request or self.kwargs in get_serializer_class

**Comment by tomchristie** [comment]
Fixes incoming for those.

**Comment by tomchristie** [comment]
> when accessing attributes like self.request or self.kwargs in get_serializer_class

Those also now resolved in 3.4.4.

Tho note that function based views with multiple methods are still not going to be handled. See https://github.com/tomchristie/django-rest-framework/pull/4400
