### ISSUE TITLE
The raw json generated from django swagger fails when validated using swagger-tools

### ISSUE THREAD

**Issue by abhishesh** [marcgibbons/django-rest-swagger#504]
I use DRF 3.3.2 and django-rest-swagger==0.3.6
The raw swagger spec generated doesn't pass `swagger-tools validate myapi.json`

**Comment by angvp** [comment]
Check that swagger-tools is validating against 1.2 spec .. otherwise you will need to check a tool that is validating against 2.0 spec and upgrade to django-rest-swagger==2.0.3 at least
