### ISSUE TITLE
How to control doc expansion in django-rest-swagger v2?

### ISSUE THREAD

**Issue by Nnonexistent** [marcgibbons/django-rest-swagger#507]
There was a `doc_expansion` setting in older versions.

**Comment by dyroffk** [comment]
Seems like it might be hard coded in init.js (https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/static/rest_framework_swagger/init.js#L34), unless you can find somewhere it gets overridden by Django settings.

**Comment by marcgibbons** [comment]
Yes, I'm working on exposing these UI as settings. Thanks!

**Comment by marcgibbons** [comment]
Added DOC_EXPANSION in #519 + docs.
