### ISSUE TITLE
0.3.10 error when authentication

### ISSUE THREAD

**Issue by jacoor** [marcgibbons/django-rest-swagger#509]
Hello
Thanks for wonderful app!
I found a problem in it:
When I put correct token into api key field I get:
"VM313:2 Uncaught SyntaxError: Unexpected token < in JSON at position 1"
Investigation shows that server under /api-docs/ url returns HTML instead of JSON.  Downgrading to version 0.3.9 solved the issue.

Furthermore: installing only version 0.3.9 w/o reloading web page still shows the issue, so it seems like some headers are being sent incorrectly and trigger HTML response instead of JSON.

**Comment by marcgibbons** [comment]
Hi, this is captured in #497. Thanks!
