### ISSUE TITLE
Swagger do not expose serializers details with drf >=3.4

### ISSUE THREAD

**Issue by gitfred** [marcgibbons/django-rest-swagger#511]
I experienced that after change from djswagger 0.3.10 and drf 3.3.3 to the newest ones Serializer's details (like fields types and structure) are not exposed anymore.

**Comment by kevin-brown** [comment]
Field types is covered by https://github.com/marcgibbons/django-rest-swagger/issues/490.

**Comment by marcgibbons** [comment]
Marking as duplicate. Thank you!

**Comment by gitfred** [comment]
Sorry about that folks, thanks!
