### ISSUE TITLE
How to sort endpoints?

### ISSUE THREAD

**Issue by aronroberts** [marcgibbons/django-rest-swagger#512]
I apologize if I have missed something obvious but I'd like to sort the endpoints alphabetically. Is this possible?

**Comment by marcgibbons** [comment]
At the moment, but I am working on this for the next release

**Comment by angvp** [comment]
I've done this on the add customizations method wanna a PR for this?

**Comment by marcgibbons** [comment]
Basic SwaggerUI settings are exposed (#519)
