### ISSUE TITLE
run_example.sh doesn't work without tweaking

### ISSUE THREAD

**Issue by cdman** [marcgibbons/django-rest-swagger#524]
On Ubuntu 16.04 with docker 1.11.2 I had to change run_example.sh from `docker build . -t django-rest-swagger-example` to `docker build -t django-rest-swagger-example .` (put the dot at the end).

Even so it only worked after multiple re-runs and me running `manage.py migrate` manually inside the container (ie. it doesn't seem to work correctly when the image is re-built from scratch on the machine).

**Comment by marcgibbons** [comment]
Fixed in 2.0.5
