### ISSUE TITLE
Issues with Schemas Generation

### ISSUE THREAD

**Issue by psychok7** [marcgibbons/django-rest-swagger#525]
So i have upgraded to `djangorestframework==3.4.4` and `django-rest-swagger==2.0.4` and i am trying to accomplish one of the 2 things. 

First, using the `SchemaGenerator` i would like to EDIT the generated document and add new information to it . I tried fiddling with it but with no luck..

Second, i tried creating a custom shema as described here http://www.django-rest-framework.org/api-guide/schemas/#explicit-schema-definition and it works with `CoreJSONRenderer` but it does not seem to work with `OpenAPIRenderer` and  `SwaggerUIRenderer` because i get no navigation like the autogenerated shema generator.

I get this instead:

![screen](https://cloud.githubusercontent.com/assets/282284/17734119/1b870616-6472-11e6-8cf9-625267180678.png)

Is this not supported yet or i am doing it wrong?

Thanks

**Comment by conor10** [comment]
I'm hitting the same issue.

If we take the example schema from the Django Rest Framework:

http://www.django-rest-framework.org/api-guide/schemas/

```python
schema = coreapi.Document(
    title='Flight Search API',
    url='https://api.example.org/',
    content={
        'search': coreapi.Link(
            url='/search/',
            action='get',
            fields=[
                coreapi.Field(
                    name='from',
                    required=True,
                    location='query',
                    description='City name or airport code.'
                ),
                coreapi.Field(
                    name='to',
                    required=True,
                    location='query',
                    description='City name or airport code.'
                ),
                coreapi.Field(
                    name='date',
                    required=True,
                    location='query',
                    description='Flight date in "YYYY-MM-DD" format.'
                )
            ],
            description='Return flight availability and prices.'
        )
    }
)


@api_view()
@renderer_classes([OpenAPIRenderer, SwaggerUIRenderer])
def schema_view(request):
    return response.Response(schema)
```

This is using:

Django==1.10
django-rest-swagger==2.0.3
djangorestframework==3.4.3


The rendered Swagger view is blank as per the below:

<img width="579" alt="screen shot 2016-08-27 at 21 48 09" src="https://cloud.githubusercontent.com/assets/2148266/18027176/3b776ad4-6ca0-11e6-9026-2cbd1c113129.png">

Cheers.

**Comment by tanwirahmad** [comment]
I am having the same problem with django-rest-swagger 2.0.5 and djangorestframework 3.4.3

**Comment by psychok7** [comment]
@marcgibbons do you have any idea what could be causing this??

**Comment by ravibala1** [comment]
I'm seeing the same behavior with django-rest-swagger 2.0.5 and djangorestframework 3.4.6

**Comment by psychok7** [comment]
@marcgibbons do you need any more information so that this issue can be addressed?

**Comment by psychok7** [comment]
this issue is not happening anymore in 
```
djangorestframework==3.5.0
django-rest-swagger==2.0.7
```
