### ISSUE TITLE
Anyway to set content-type for swagger docs?

### ISSUE THREAD

**Issue by Zaccc123** [marcgibbons/django-rest-swagger#529]
My app api is set to only support `application/json`.

All the `POST` request in swagger docs is giving error `415` as it is default to `application/x-www-form-urlencoded`.

I have read the docs and can't seems to find any where to update the `Content-Type` for swagger docs. I have try changing the url `?format=` and it does not work as well.

Anyone know if we could do this?

<img width="913" alt="screen shot 2016-08-19 at 7 10 59 pm" src="https://cloud.githubusercontent.com/assets/11663635/17808110/ba5dd65a-6640-11e6-86fc-2f73cd6c6fc8.png">

**Comment by marcgibbons** [comment]
Short answer is no, but we absolutely need this, particularly to represent complex data types which don't work within the constraints of form-data.

Couple of things we need to accomplish this is:
- Adjustment of how the encoding is set for the Document by the schema generator:
https://github.com/tomchristie/django-rest-framework/blob/e3f8d06bafd37780d6010b0a963029a3448d5e54/rest_framework/schemas.py#L244-L263

  If the parser/renderer classes support form data (default), the encoding on the Document should be set to x-www-form. If not (and presuming JSON), then the encoding should be set to application/json

- CoreAPI currently supports 3 types of parameter locations: `query`, `path` and `form`. For `application/json` types we'd want a location something like `body` with a schema (similarly to OpenAPI).

Need to cc @tomchristie on this one.

**Comment by tomchristie** [comment]
Fields have an `encoding` attribute which may be set. This should default to `application/json` unless set otherwise. ('form' in Core API does not mean quite the same thing as 'form' in Swagger.)

If we're picky then the swagger generation could try to determine the top-level default and only include the encoding when it differs from that. Otherwise it should probably just include the encoding on all links.

The docs on http://www.coreapi.org/specification/transport/ need some improvement here, as they don't outline this correctly yet. (eg. 'body' *is* an available option.)

To outline that here:

* 'form' - The field should be included as a key-value pair, in the given encoding for the Link. Other 'form' fields may also exist.
* 'body' - The field should be included as the value itself, in the given encoding for the Link. No other 'body' or 'form' fields may also exist.

**Comment by NickStefan** [comment]
I understand that a "correct" fix is possibly in progress, but is there a quick setting somewhere to force the swagger docs to use json body fields rather than forms?

**Comment by NickStefan** [comment]
must admit that that might not even be what i want. I see that form isnt the same thing as a "form"

http://www.django-rest-framework.org/api-guide/schemas/#explicit-schema-definition
```
"form"

Included in the request body, as a single item of a JSON object or HTML form. For example {"colour": "blue", ...}. Typically for POST, PUT and PATCH requests. Multiple "form" fields may be included on a single link.

These fields will normally correspond with serializer fields on a view.

"body"

Included as the complete request body. Typically for POST, PUT and PATCH requests. No more than one "body" field may exist on a link. May not be used together with "form" fields.

These fields will normally correspond with views that use ListSerializer to validate the request input, or with file upload views.

encoding

"application/json"

JSON encoded request content. Corresponds to views using JSONParser. Valid only if either one or more location="form" fields, or a single location="body" field is included on the Link.
```

I guess what I'd like is to get the JSON editing field going for the whole request.

**Comment by tomchristie** [comment]
What did the 1.x version do?

My simple take is that we should just be using location=body for any case where application/json is valid.

If you wanted to be smarter you could use multipart/urlencoded in cases where the serializer only has primative field types.

@marcgibson happy to help resolving this. On leave next few days but this is top of my big list right now.

**Comment by paulosuzart** [comment]
I've followed the very straight instruction at the official doc. And in my case I get two crazy things:

   1. All API request generated by the UI sets the  `--header 'Accept: application/openapi+json'` for all API endpoints. A workaround is call it by hand and remove the header but:
   1. The API is unable to answer. When issuing a request to any API endpoint, it returns the swagger 2.0 definition of my API.

Anyone facing similar issues?

`django-rest-swagger==2.0.5`

**Comment by tomchristie** [comment]
Now resolved in the latest versions of `openapi-codec`.

**Comment by prafulbagai** [comment]
How do we do this? I'm unable to find it anywhere in the docs?

**Comment by Cospel** [comment]
I'm also interested in changing content-type. How do I do this?

**Comment by prafulbagai** [comment]
In your views, add `parser_classes = (FormParser,)`.
