### ISSUE TITLE
TemplateDoesNotExist at /docs/    rest_framework_swagger/index.html

### ISSUE THREAD

**Issue by RicterZ** [marcgibbons/django-rest-swagger#53]
When I run `python manage.py runserver`,and access to /doc in the browser, the error occurred.

```
TemplateDoesNotExist at /docs/
rest_framework_swagger/index.html
```

**Comment by m-haziq** [comment]
I am getting the same error: though I tried the solution you provided above, but nothing changed, still error is same: TemplateDoesNotExist at /docs/ rest_framework_swagger/index.html
I am using: 
django==1.10
django-rest-swagger==2.1.2
djangorestframework==3.6.2
I even tried re installing all the packages in new virtual environment as well, any suggestions please @marcgibbons

**Comment by m-haziq** [comment]
I have found the problem, as I was integrating it into my existing code in which settings.py did not have following parameters:
`TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]`
Now adding this , swagger is working fine!

**Comment by GaneshGeteres** [comment]
I am trying this but not working getting "django.template.exceptions.TemplateDoesNotExist: rest_framework_swagger/index.html" Error.
using django-rest-swagger (2.1.2) and 
djangorestframework-recursive==0.1.1
djangorestframework==3.4.6

can you please provide me the right steps.

**Comment by nepaliwhitehat** [comment]
Go To the installed app and import 'def_yasg it will work =[
.......--

'drf_yasg',
]

**Comment by akrapovich** [comment]
you must add `'rest_framework_swagger'` to `INSTALLED_APPS` in Django settings.

**Comment by shravanign** [comment]
I am also getting same error. Have tried all mentioned, but still getting same error
