### ISSUE TITLE
can't exclude urls in latest version?

### ISSUE THREAD

**Issue by judyyy** [marcgibbons/django-rest-swagger#530]
![image](https://cloud.githubusercontent.com/assets/13639037/17828851/bf00adc4-66cf-11e6-80d4-33556fc2cc29.png)

![image](https://cloud.githubusercontent.com/assets/13639037/17828855/e015f6ae-66cf-11e6-928e-3b37d6161b92.png)

**Comment by marcgibbons** [comment]
Hey @judyyy, it is possible to explicitly list which urlpatterns you wish to be documented, however, as of v2, this is done by specifying this in the schema generator.

E.g.
```python
generator = SchemaGenerator(
    title='Stock Prices API',
    patterns=...
)
```

http://www.django-rest-framework.org/api-guide/schemas/#schemagenerator
