### ISSUE TITLE
Only one endpoint is shown in app

### ISSUE THREAD

**Issue by zloy531** [marcgibbons/django-rest-swagger#533]
Example: https://gist.github.com/anonymous/11de3418af0d70bb93a44320e68809b7

I'm not very experienced with drf and I cannot find the solution. First model stores metadata for real data in the second. And both of them are `list actions`. I cannot use `detail-view` of DataSet with nested data, because in this case I lose an ability filter/paginate nested data automatically.
rest_framework/schemas.py:100 - here all this is writing into dict, and one endpoint is losing.

I think, this is the drf-swagger problem, why I  cannot have two read endpoints in one app? But I cannot  think out, how fix it cheaply.

**Comment by marcgibbons** [comment]
@zloy531 I'm not sure how this fits into this project as I am not seeing swagger being used at all in your example. Please take a look at the Django REST Framework tutorials and documentation - it is excellent.

Thanks!
