### ISSUE TITLE
How to use the new version (2+) with TokenAuthentication?

### ISSUE THREAD

**Issue by duduklein** [marcgibbons/django-rest-swagger#535]
As far as I understand, the way to include the TokenAuthentication is use the SECURITY_DEFINITIONS settings.

In the [OpenAPI Docs](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#security-definitions-object), in the "api_key" type, there are 3 keys: "type", "name", "in".

I guess that "in" should be "header", name "Authorization" and type should be left "apiKey". Where should I put the value "Token MYTOKEN"?

This ticket may be related to #497 , but I'm not sure.

Thanks in advance

**Comment by marcgibbons** [comment]
Hi @duduklein - the security definitions are 1:1 with the OpenAPI spec and the `in` can either be `header` or `query`.

To set the token, click the "Authorize" button in the UI.

**Comment by duduklein** [comment]
@marcgibbons Which UI are you talking about? 
In the base.html in DRS, there is no UI button to test. Which UI are you talking about?

**Comment by marcgibbons** [comment]
Is the Authorize button not rendering? It is present when security definitions have been defined. It opens a modal and you set your key there.

![image](https://cloud.githubusercontent.com/assets/1726961/17966389/44704a6a-6a8f-11e6-972a-bc56faf04a53.png)

**Comment by duduklein** [comment]
Thanks for your quick answer.
No, it's not rendering. Is this supposed to ne rendered by a JS? If yes,
which one, so I can debug why.

Le jeu. 25 août 2016 à 12:46, Marc Gibbons <notifications@github.com> a
écrit :

**Comment by duduklein** [comment]
I have put a breakpoint in the `OpenAPIRenderer.add_security_definitions` methond, but when the page loads it does not get there.

**Comment by duduklein** [comment]
@marcgibbons , Do you have any idea of what could be causing this? Can you point me out in your base.html template where the security definitions are rendered, so they can be picked up by the js?
Thanks in advance

**Comment by pySilver** [comment]
same story: http://take.ms/68EFs

```python
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'oauth2': {
            'type': 'apiKey',
            'description': 'Personal API Key authorization',
            'name': 'Token',
            'in': 'header',
        }
    },
}
````

**Comment by pySilver** [comment]
@duduklein have you managed to solve this?

**Comment by marcgibbons** [comment]
@duduklein Sorry, I have not had then chance to look into it further. Hoping to have some time next week.

@pySilver You are seeing a 401 error because permissions appear to be enforced on your schema view. Try using the AllowAny permission class on the schema view. This seems scary, but if you are passing the request object into the generator, and endpoints are protected, only publicly available ones will appear.

**Comment by duduklein** [comment]
@marcgibbons I have exactly the same screen and error that @pySilver (I did not solve the issue).

Regarding the schema view, I have the following (copied from the docs):
```
@api_view()
@renderer_classes([OpenAPIRenderer, SwaggerUIRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='API DOCS')
    return response.Response(generator.get_schema(request=request))
```
In my urls, I have:
```
urlpatterns = [
    url(r'^0.1/', include(version_urls)),
    url(r'^docs/', schema_view, name="description-complete"),
]
```

version_urls are the API entrypoints. Maybe one cause of the issue is that both of us have the docs at "/docs/" instead of the root level "/" and/or the fact that the APIs entrypoints are not at the root level, but at "/0.1/" for me. I don't know about @pySilver 

My settings are the following:
```
SWAGGER_SETTINGS = {
        "USE_SESSION_AUTH": False,
        "LOGIN_URL": "/",
        "LOGOUT_URL": "/",
        "SUPPORTED_SUBMIT_METHOD": ['get', 'post', 'put', 'delete', 'patch'],
        "APIS_SORTER": "alpha",
        "VALIDATOR_URL": None,
        'SECURITY_DEFINITIONS': {
            "api_key": {
                "type": "apiKey",
                "name": "Authorization",
                "in": "header"
            },
        }
     }
```

**Comment by marcgibbons** [comment]
@duduklein Have you tried setting your permission to `AllowAny` on the schema view?

**Comment by duduklein** [comment]
@marcgibbons I'm not sure how you intended to do this, but I tried managed to replace `APIView.permission_classes` from line 73 of decorators.py with `[AllowAny]`, from `from rest_framework.permissions import AllowAny`

When I do this, I don't have the same error and the "Authorize" button appears. What is annoying is the fact that the "/docs/" entry which is not an API entry appears as being one. I clicked on it to see what happens. Here are the results:

![image](https://cloud.githubusercontent.com/assets/2512289/18318947/f321b6f4-7523-11e6-9869-fc9e83669dd1.png)

Once I enter my token; it does get the api entries, but not all of them. But this is probably a different issue. I'll try to debug it and will open a different ticket if needed.

**Comment by pySilver** [comment]
@duduklein you could simply use permission decorator instead

**Comment by duduklein** [comment]
@pySilver Thanks :)

Now the issue is how can we get rid of the "/docs/" entry which is not an api one.
Do you have the same issue?

**Comment by marcgibbons** [comment]
@duduklein I have seen this as well. Please open an issue on DRF for this.

I am thinking of including a view in this package which has some default settings for people to get up and running quickly, as permissions have caused problems for several people. 

Thanks for your help!

**Comment by kravietz** [comment]
If you have caching enabled in Django it can also cause headaches with Swagger as it will show unauthenticated list of endpoints even when you're authorized. I struggled with this for a while and finally solved this by simply wrapping all the API class based views in `never_cache` decorator.
