### ISSUE TITLE
Method docstrings not included in generated docs

### ISSUE THREAD

**Issue by jwineinger** [marcgibbons/django-rest-swagger#537]
I recently upgraded from 0.3.5 to 2.0.4.  Previously, docstrings on view methods (MyView.get) would be included in the swagger generated docs, but with the new version I don't get any docs included. It does seem to introspect serializer fields and such, but the docstrings help users of the API understand what an endpoint does and when to use it.  Is there any way to get those included with the current release?

**Comment by jwineinger** [comment]
Looks like django-rest-framework doesn't support it yet =P 

https://github.com/tomchristie/django-rest-framework/issues/4241
> 
Add descriptions to schema generation, and document use of describe.

**Comment by tawanda** [comment]
I also have this problem, the old version of rest swagger imported doc strings, and also showed dictionaries in the doc string nicely formatted, why take that away. Or is there an option to manually include them?

**Comment by NickStefan** [comment]
Also looking for a solution

**Comment by judyyy** [comment]
I also have this problem

**Comment by alexmicrosrv** [comment]
Also the same problem. But when I make a GET request with the DRF API, docstrings appear on top of the result page.
So it's a posible django-rest-swagger problem ?

**Comment by blurrcat** [comment]
It seems this project has nothing to do with the problem. The schema generation part is now(restframework 3.4+) done by restframework and this project merely uses generated coreapi objects to render swagger.json.

**Comment by jwineinger** [comment]
This project will have to implement it with DRF supports it. I did a quick hack to my local DRF to include the docstrings, verified that they are output in the XHR request, but did not appear in the django-rest-swagger front-end.

**Comment by blurrcat** [comment]
As a quick workaround, try the following:
```py
class SchemaGenerator(schemas.SchemaGenerator):
    def get_link(self, path, method, callback, view):
        # link is an instance of `coreapi.Link`
        link = super(
            SchemaGenerator, self).get_link(path, method, callback, view)
        action = self.get_action(path, method, callback)
        func = getattr(view, action, None)
        if func:
            link._description = func.__doc__
        return link
```

**Comment by jwineinger** [comment]
Yeah, that was the quick hack I did.  Seems like something similar to this could be used to fix #536 as well.

**Comment by paulosuzart** [comment]
I think it also doesn't support the Generic Views doc strings.

**Comment by c-bata** [comment]
@paulosuzart Yeah, that's right.
It requires further discussion on django-rest-framework repository.
https://github.com/tomchristie/django-rest-framework/issues/4444

**Comment by Zeliboba5** [comment]
@paulosuzart For generic views you can see my attempt in https://github.com/tomchristie/django-rest-framework/issues/4444

**Comment by marcgibbons** [comment]
Docstring introspection is now provided in DRF 3.5+. Closing out.
