### ISSUE TITLE
Add block `extra_scripts` to base.html template

### ISSUE THREAD

**Issue by Skorpyon** [marcgibbons/django-rest-swagger#539]
I suggest add new block to base template same as `exstra_styles` for allow override this block and include translator and translations instead override whole base.html

**Comment by marcgibbons** [comment]
Pull requests are welcome 😄

**Comment by Skorpyon** [comment]
{% block extra_scripts %} already awailable on a bottom of `base.html` so i close this, it is my inadvertence.
