### ISSUE TITLE
Django 1.10 problem url

### ISSUE THREAD

**Issue by flaudizio** [marcgibbons/django-rest-swagger#544]
Hi,

I'm having this problem:

ImportError: No module named 'rest_framework_swagger.urls'

when I add this line:

url(r'^docs/', include('rest_framework_swagger.urls')),

**Comment by kevin-brown** [comment]
`rest_framework_swagger.urls` no longer exists in Django REST Swagger version 2.

**Comment by flaudizio** [comment]
Thank's, I'm was confusing with how to work.

Regards.

**Comment by pnaylor** [comment]
What should be used instead in version 2?
