### ISSUE TITLE
Swagger file

### ISSUE THREAD

**Issue by SvetlanaM** [marcgibbons/django-rest-swagger#546]
It is possible get json swagger file?

**Comment by ivlevdenis** [comment]
Yes. Use only `OpenAPIRenderer` in your schema view.

**Comment by SvetlanaM** [comment]
I will try

**Comment by marcgibbons** [comment]
Yes, by using the OpenAPIRenderer, you can get the spec by either providing `?format=openapi` or setting the header `Content-Type: application/openapi+json`
