### ISSUE TITLE
Getting AssertionError: Expected a coreapi.Document when using format=openapi

### ISSUE THREAD

**Issue by aldwyn** [marcgibbons/django-rest-swagger#547]
Hi, I have the following set-up.

**settings.py**
```python
REST_FRAMEWORK = {
   'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.BrowsableAPIRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.CoreJSONRenderer',
        'rest_framework_swagger.renderers.SwaggerUIRenderer',
        'rest_framework_swagger.renderers.OpenAPIRenderer',
    )
}
```

**views.py**
```python
from rest_framework import mixins
from rest_framework.viewsets import GenericViewSet
from rest_framework.routers import DefaultRouter

class ProspectViewSet(mixins.CreateModelMixin,
                      mixins.ListModelMixin,
                      mixins.RetrieveModelMixin,
                      mixins.UpdateModelMixin,
                      GenericViewSet):
    queryset = Prospect.objects.all()
    renderer_classes = (SwaggerUIRenderer, OpenAPIRenderer)

prospect_router = DefaultRouter(schema_title='Prospect Public API')
prospect_router.register(r'prospects', ProspectViewSet)
```

**urls.py**
```python
from django.conf.urls import include
from django.conf.urls import url

from .views import prospect_router

urlpatterns = [
    url(r'^api/public/', include(prospect_router.urls)),
]
```

When I try to browse `http://localhost:8000/api/public/?format=openapi`, I get the following error:
```python
Traceback:

File "/var/www/myproject/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  174.                     response = self.process_exception_by_middleware(e, request)

File "/var/www/myproject/venv/local/lib/python2.7/site-packages/django/core/handlers/base.py" in get_response
  172.                     response = response.render()

File "/var/www/myproject/venv/local/lib/python2.7/site-packages/django/template/response.py" in render
  160.             self.content = self.rendered_content

File "/var/www/myproject/venv/local/lib/python2.7/site-packages/rest_framework/response.py" in rendered_content
  72.         ret = renderer.render(self.data, accepted_media_type, context)

File "/var/www/myproject/venv/local/lib/python2.7/site-packages/rest_framework_swagger/renderers.py" in render
  21.         data = self.get_openapi_specification(data)

File "/var/www/myproject/venv/local/lib/python2.7/site-packages/rest_framework_swagger/renderers.py" in get_openapi_specification
  34.             type(data)

Exception Type: AssertionError at /api/public/
Exception Value: Expected a coreapi.Document, but received <class 'collections.OrderedDict'> instead.
```
Where the **`data`** is equivalent to:
```python
OrderedDict([('prospects', 'http://localhost:28001/api/public/?format=openapi')])
```

I am using `djangorestframework==3.4.6` and `django-rest-swagger==2.0.5`. I was thorough with the installation and usage guide,  but am I missing anything?

**Comment by kliver** [comment]
Is just wrong, i did the same (doc is not clear enough).

Anyway, this worked for me

urls.py:
`from rest_services.apis.rest_services.views import schema_view

urlpatterns = [
                  url('^$', schema_view),
...
`

rest_services.apis.rest_services.views.py

`
from rest_framework.response import Response
from rest_framework import renderers, schemas
from rest_framework.decorators import api_view, renderer_classes
from rest_framework_swagger.renderers import OpenAPIRenderer, SwaggerUIRenderer

@api_view()
@renderer_classes([SwaggerUIRenderer, OpenAPIRenderer, renderers.CoreJSONRenderer])
def schema_view(request):
    generator = schemas.SchemaGenerator(title='AVRIL API')
    return Response(generator.get_schema(request=request))
`
You could change some settings in settings.py
`
SWAGGER_SETTINGS = {
    'LOGIN_URL': 'rest_framework:login',
    'LOGOUT_URL': 'rest_framework:logout',
    'USE_SESSION_AUTH': True,
    'DOC_EXPANSION': 'list',
    'APIS_SORTER': 'alpha',
    'SHOW_REQUEST_HEADERS': True
}
`
Thats all as long i remember.

**Comment by marcgibbons** [comment]
@aldwyn The renderer classes go on the schema (default router), not on your viewset.

**Comment by Gauravwagh81** [comment]
I fixed this issue by adding
`'DEFAULT_SCHEMA_CLASS': 'rest_framework.schemas.coreapi.AutoSchema',` . In settings.py file

**Comment by giorgiberia** [comment]
still unclear what is correct solution for this issue

**Comment by Guyzai** [comment]
Remove this :
@renderer_classes([SwaggerUIRenderer, OpenAPIRenderer, renderers.CoreJSONRenderer])
