### ISSUE TITLE
Load UI from a Swagger definition file

### ISSUE THREAD

**Issue by AndreLobato** [marcgibbons/django-rest-swagger#567]
There is a way to support rendering the UI from a definition file (json/yaml)?

I just cannot rely on the restframework SchemaGenerator as does not reproduce exactly the API as I want. So I must define manually the openapi specification. The only method I found to load swagger files was to use the [core-api/python-openapi-codec/](https://github.com/core-api/python-openapi-codec/). But I don't seem to load correctly a valid openapi 2.0 definitions (maybe don't support 2.0?) I created using the Swagger editor.

**Comment by AndreLobato** [comment]
I found out why was not working, so was just because I had not defined `operationId` on the paths. Which is not required to have a valid swagger file but the python-openapi-codec, relies on it.

But after loading the definitions file correctly it seems to have broken the Try It Out! button. 

In the javascript console I get...
```
SyntaxError: An invalid or illegal string was specified (swagger-ui.js:18624)
```

**Comment by clemenbor** [comment]
I am having exactly a similar problem. I find the Core API from the restframework way too limited when  specifying the Document to be generated by the SchemaGenerator. So I was wondering if it's possible to load a swagger json/yaml file instead?. 

It would be very helpful to have full control.

**Comment by marcgibbons** [comment]
@AndreLobato If you are looking to render an existing OpenAPI spec (not rendered by DRF, or converted from CoreAPI), then there is no need to use this project. Download SwaggerUI and point it to your static JSON schema. Hope this helps!

**Comment by AndreLobato** [comment]
That's a very sensible solution, I see your point. Thanks
