### ISSUE TITLE
How to force a DictField to be documented as an object, not a string?

### ISSUE THREAD

**Issue by tardate** [marcgibbons/django-rest-swagger#568]
When passing a dict/hash of arbitrary data in an API, we're using `DictField` (same applies for `JSONField`). A good example is an errors collection, where we really don't want to define a serializer with all the possible elements it may contain. So we declare like this:

    class CustomSerializer(serializers.Serializer):
        errors = serializers.DictField(
            required=False, help_text="Error conditions, if any"
        )

The problem is this shows up in the swagger UI as a string:

    CustomSerializer {
      errors (string): Error conditions, if any
    }

Likewise in swagger doc:

    "CustomSerializer": {
      "required": [
        "errors"
      ],
      "id": "CustomSerializer",
      "properties": {
        "errors": {
          "description": "Error conditions, if any",
          "required": false,
          "readOnly": false,
          "type": "string"
        }
      }
    },

This is causing problems for API clients that are attempting to introspect on the basis of the swagger doc. Is there a way to define these elements better - at least not have them declared as a string? Am I missing something obvious?

Note we are still on 0.3.x branch (0.3.10)

**Comment by marcgibbons** [comment]
Unfortunately this is not supported in the 0.3.x., but is now possible in the latest version

**Comment by korbinianfritsch** [comment]
I am currently on 2.1.2 and experiencing an issue very much alike.

```python
# serializers.py

class NestedObjectSerializer(serializers.Serializer):

    key = serializers.CharField(
        max_length=200,
    )
    value = serializers.DecimalField(
        max_digits=3,
        decimal_places=2,
    )


class RequestSerializer(serializers.Serializer):

    dictionary = serializers.DictField()
    nested_object = NestedObjectSerializer(
        many=True,
    )
```

```python
# views.py

class SomeView(GenericAPIView):

    permission_classes = []
    serializer_class = RequestSerializer

    def post(self, request):
        request_serializer = RequestSerializer(data=request.data)
        request_serializer.is_valid(raise_exception=True)

        ...

        return Response(response_serializer.data)
```

Although I am using a DictField in the Request Serializer, Swagger UI shows the data type of the field as `string` in both the Model & Example Value:
```python
# Swagger UI

{                           |
  "dictionary": "string",   |   inline_model {
  "nested_object": [        |     lead_profile (string): ,
    "string"                |     data_point_requests (Array[string]):
  ]                         |   }
}                           |   
```
Same applies for the nested serialized object.

I am thankful for any hints!
