### ISSUE TITLE
why swagger_settings in settings.py is not work?

### ISSUE THREAD

**Issue by larryhq** [marcgibbons/django-rest-swagger#577]
djangp-rest-framework 3.5.2
django-rest-swagger 2.1.0
In my settings.py,I config swagger_settings like:
```
# Django REST Swagger
SWAGGER_SETTINGS = {
    'exclude_namespaces': ['v1'],
    'api_version': 'v2.0.0',
    'api_path': '/',  # Specify the path to your API not a root level
    'api_key': '',  # An API key
    'is_authenticated': True,
    'is_superuser': True,
    'info': {
        'title': '{} API 文档'.format(DOMAIN_NAME),
        'description': 'v2.0.0'
    },
    'doc_expansion': 'list'
}
```
but it not work, why? Is it remove in version 2.x?
If I want to use the settings, how can I do?
And I have anther question:
In rest-swaager  0.3.10, the url order in documentation is sorted by my urls.py, but in the newest version, it sorted by what?

**Comment by marcgibbons** [comment]
@larryhq Correct. The settings have changed in v2. Please consult the documentation:
http://marcgibbons.github.io/django-rest-swagger/settings/

**Comment by larryhq** [comment]
@marcgibbons  thanks very much .
I have some other questions:
1、In v2 is there some method instead of api_version, is_authenticated, is_superuser like v0.3.10?
what can I do If I want to realization it ?
2、 I have very many urls in a dir,  when I make the documentation, can I assort them with the first word like the example in http://marcgibbons.github.io/django-rest-swagger/

**Comment by marcgibbons** [comment]
@larryhq 

For question no. 1, I think the answer you are looking for is here https://github.com/marcgibbons/django-rest-swagger/issues/589

2. There is a setting to sort alphabetically; Swagger UI (see their docs) also provide a way to add custom sorting logic. I'm not sure if that helps?

Many thanks
