### ISSUE TITLE
Error with custom user model

### ISSUE THREAD

**Issue by JamesRamm** [marcgibbons/django-rest-swagger#579]
I am using `allauth` with a custom user model which removes the `username` field, authenticating with the `email` field. 

After setting up, I get the following error when navigating to the docs:

```
django.core.exceptions.ImproperlyConfigured
ImproperlyConfigured: Field name `username` is not valid for model `CustomUser`.
```

**Comment by marcgibbons** [comment]
@JamesRamm I'm afraid I don't have enough information to understand the issue or how it relates to Swagger. Feel free to reopen with a stacktrace and further details. Many thanks!

**Comment by maihuymao** [comment]
@marcgibbons I have the same issue. Please take a look at my log. Thanks!
[swagger_custom_user.txt](https://github.com/marcgibbons/django-rest-swagger/files/905090/swagger_custom_user.txt)

**Comment by marcgibbons** [comment]
@ricoyakuza Judging by the stacktrace, it looks like you have a view somewhere in your app (maybe from a 3rd party lib? that references `username` in a serializer?

There is no reference to `username` in this project or DRF's `schemas.py`

**Comment by ricoyakuza** [comment]
Thanks for your support. This problem actually comes from 3rd party lib (rest_auth in my case).

**Comment by MrEmanuel** [comment]
I solved this problem by adding a username field on the serializer even though I don't have one on the model. 
`serializer = ""`

**Comment by FabrizioA** [comment]
Hi, anyone solved this issue?

**Comment by simo97** [comment]
No, still running into that problem
