### ISSUE TITLE
instance failed to match exactly one schema (matched 0 out of 2)

### ISSUE THREAD

**Issue by codalprashant** [marcgibbons/django-rest-swagger#586]
{"schemaValidationMessages":[{"level":"error","domain":"validation","keyword":"oneOf","message":"instance failed to match exactly one schema (matched 0 out of 2)","schema":{"loadingURI":"http://swagger.io/v2/schema.json#","pointer":"/definitions/parametersList/items"},"instance":{"pointer":"/paths/~1api~1users~1/post/parameters/0"}}]}

Works well on local but not on server. Giving above error.

**Comment by marcgibbons** [comment]
@codalprashant I'm afraid I don't understand. Feel free to reopen with additional information and ideally a failing test to recreate a bug. Thank you.

**Comment by hdeliwala** [comment]
@codalprashant  I am also getting same error. Works fine in my local. but In server I am getting error.

**Comment by andy-radkevich** [comment]
{
    "schemaValidationMessages": [
        {
            "level": "error",
            "domain": "validation",
            "keyword": "oneOf",
            "message": "instance failed to match exactly one schema (matched 0 out of 2)",
            "schema": {
                "loadingURI": "http://swagger.io/v2/schema.json#",
                "pointer": "/definitions/parametersList/items"
            },
            "instance": {
                "pointer": "/paths/~1channels~1/get/parameters/3"
            }
        }
    ]
}
![screenshot from 2017-07-24 10-02-27](https://user-images.githubusercontent.com/9484902/28511902-19a6bc4a-7058-11e7-9586-5fb219bed565.png)
![screenshot from 2017-07-24 10-00-57](https://user-images.githubusercontent.com/9484902/28511914-2708aa24-7058-11e7-856b-c2acbd6f5c3e.png)

**Comment by ramdesh** [comment]
Hi we are getting this same error, when we serve the Swagger locally and validate, it does not give the error, but when serving online, it gives the error. 
Is there any solution to this?

**Comment by diabluchanskyi** [comment]
I can confirm that we get the same behaviour on 2.2.6 version

**Comment by GLOBE1984** [comment]
We are getting the same error as ramdesh @ramdesh . Any solution on this?

**Comment by prsheth** [comment]
Any solutions for this? . We are experiencing the same error.

**Comment by oloendithas** [comment]
+
