### ISSUE TITLE
It seems swagger get docs from another serializer of the same name.

### ISSUE THREAD

**Issue by thinker3** [marcgibbons/django-rest-swagger#587]
The fields need to fill in are right.
The two serializers have the same name, but in different module.
After I changed one name, it get the right docs.

**Comment by marcgibbons** [comment]
@thinker3 If you believe this is a bug with the schema generation, could you please open an issue on Django REST Framework (ideally accompanied by a unit test) to recreate the issue? Many thanks

**Comment by thinker3** [comment]
I solved this by specify action and request_serializer and response_serializer.

**Comment by yli-cpr** [comment]
We see the problem, too. The REST framework works, but the generated swagger page has this problem.
