### ISSUE TITLE
Post parameters in not shown in swagger

### ISSUE THREAD

**Issue by mhipo1364** [marcgibbons/django-rest-swagger#588]
Hi

The swagger panel in my project does not show from to post data, how can I enable it?

`django 1.10.3`
`drf 3.5.3`
`swagger 2.1.0`

**Comment by marcgibbons** [comment]
@mhipo1364 I'm afraid I don't have enough information to address this. Do you mean that the POST endpoints do not appear in the list of endpoints? If so, this means you are not authenticated when viewing your spec.

**Comment by mhipo1364** [comment]
@marcgibbons no, I mean, how could I see my input values as a form in swagger in my POST verb?

**Comment by marcgibbons** [comment]
@mhipo1364 Do you mean to POST as form data rather than `application/json`?

The OpenAPI spec generated by DRF/CoreAPI determines whether to use `body` or `form` based on the Django REST Framework parses classes used, and by the order in which they are defined. By default, the `JSONParser` comes first. 

By modifying the parser classes either on your view, or changing the `DEFAULT_PARSER_CLASSES` setting for Django REST Framework, the documentation will use the first parser it recognizes:

Example:
```python
# settings.py
REST_FRAMEWORK = {
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
        'rest_framework.parsers.JSONParser',
    ]
```

**Comment by utkbansal** [comment]
@marcgibbons I have got a similar issue - The POST data doesn't show up as a form. I have opened a question with complete details here - http://stackoverflow.com/questions/41104615/django-rest-swagger-how-can-i-specify-the-parameter-for-post-requests-while-usi

**Comment by cjl328** [comment]
I'm also having the same issue of the post parameters not showing up as a form. Following utkbansal's example, I also tried adding in views:
def get_serializer(self):
    return UserAuthenticationSerializer

**Comment by ulgens** [comment]
@marcgibbons Your solution works. Thank you!

**Comment by pmontu** [comment]
@marcgibbons, I just did this
```python
from rest_framework.authtoken.views import ObtainAuthToken
class AuthTokenView(ObtainAuthToken, GenericAPIView):
    pass
```
and
```python
url(r'^api-token-auth/', AuthTokenView.as_view())
```
to get form inputs for username and password [screenshot](https://drive.google.com/file/d/0Bz2z1Vn8y3JNLUp1MTNlRVFtRnM/view?usp=sharing)

Am i doing the right thing?

**Comment by voblivion** [comment]
Hey @pmontu ! Same issue and your workaround works for me :+1: thx ! I think, considered how ObtainAuthToken works, rest_framework should update this view.

**Comment by m-haziq** [comment]
Thanks @marcgibbons , your solution works, I wish these details were added somewhere in the documentation as well , which ll make it easy to learn.
