### ISSUE TITLE
Export the swagger definition

### ISSUE THREAD

**Issue by jheld** [marcgibbons/django-rest-swagger#590]
Is there a way to export the swagger definition?
For instance, if the developer wanted to use a tool like Postman, and wanted the docs in a good format to write tests & calls, is there a way to get the file that Postman could use: https://www.getpostman.com/docs/importing_swagger

I'm also not sure if the swagger usage there would be YAML based or not.

**Comment by marcgibbons** [comment]
@jheld Yes, you can view the spec by passing the `?format=openapi` query parameter to your schema view. This will render the OpenAPI/Swagger specification instead of the UI.
