### ISSUE TITLE
Enable setting to toggle swagger UI

### ISSUE THREAD

**Issue by cizixs** [marcgibbons/django-rest-swagger#591]
Is there a setting that can toggle swagger UI? 
This can be very useful when working with different environments, like production and testing.

I notice that [drfdocs has such setting](http://drfdocs.com/settings/), so hoping django-rest-swagger could add this feature.

**Comment by marcgibbons** [comment]
@cizixs I'm hesitant to introduce this, given that the UI/Spec is simply a view that gets defined and registered however the use wants. Also, given that DRS supports multiple instances of swagger docs, having a general on/off setting may not be appropriate to all instances.

Instead, I would suggest adding logic in either your view, or in urls.py to read a setting variable.
