### ISSUE TITLE
Authorize button

### ISSUE THREAD

**Issue by b505d987** [marcgibbons/django-rest-swagger#600]
Hello.

I have a little problem with Authorize button.
I use basic auth and set login/logout url. What Authorize button doing? 
I need only Login/Logout button and I would like hide 'Authorize'? How can I do it? 

Thank you.

**Comment by marcgibbons** [comment]
Yes, by default, the Authorize button shows up for basic auth. 
To remove, try setting `SECURITY_DEFINITIONS`: None

**Comment by b505d987** [comment]
@marcgibbons Thank you!
