### ISSUE TITLE
Using Regex Flags with DRS

### ISSUE THREAD

**Issue by Keilan** [marcgibbons/django-rest-swagger#602]
Hey all,

We've had to make our API fully case insensitive, and we've implemented this using a regex flag, like this:
```
urlpatterns = patterns('',
    url(r'^(?i)widget/', include(apps.widget)),
    url(r'^(?i)widget2/', include('apps.widget2')),
    url(r'^(?i)docs/', include('rest_framework_swagger.urls')),
)
```
Unfortunately this breaks our swagger documentation. The /docs/ endpoint then tries to make a call like `/docs/api-docs/{var}widget`, which doesn't return anything, and so we end up with no documented endpoints. It seems like the issue is caused by some sort of conversion of flags to {var} which doesn't play nice with Django urlpatterns. Is there any way around this? Perhaps using middleware to adjust the url?

**Comment by kevin-brown** [comment]
Unrelated, but the Django Developers Mailing List is looking for input from people who use regex flags, as they're considering deprecating them.

https://groups.google.com/forum/#!topic/django-developers/Y51CKkqq6Ng

**Comment by Keilan** [comment]
Thanks for the link - it looks like they want them gone, so I'll see if I can get the ball rolling with my team going back to case sensitive.

**Comment by marcgibbons** [comment]
Yeah, sounds like regex is toast. The 404 redirect suggestion from the thread seems like a good alternative:
http://librelist.com/browser/flask/2011/6/24/case-insensitive-routing/#ea14dfeac18a440b8a792358691f15e0

In any, introspection is done by DRF now; if we're missing something - let's open an issue / pr there.

Many thanks!
