### ISSUE TITLE
Uncaught ReferenceError: SwaggerUi is not defined

### ISSUE THREAD

**Issue by antorenge** [marcgibbons/django-rest-swagger#612]
Hi, I am getting a blank page when loading swagger on my browser, on checking the terminal this is what I get. I am I doing something wrong? 

Package versions:
`django-rest-swagger==2.1.1`
`djangorestframework==3.5.3`

```
handlebars-2.0.0.js:27 Uncaught a {description: undefined, fileName: undefined, lineNumber: undefined, message: "Unknown template object: function", name: "Error"…}
e @ handlebars-2.0.0.js:27
a.template @ handlebars-2.0.0.js:27
(anonymous) @ swagger-ui.min.js:1
(anonymous) @ swagger-ui.min.js:1

init.js:36 Uncaught ReferenceError: SwaggerUi is not defined
    at HTMLDocument.<anonymous> (init.js:36)
    at k (jquery-1.8.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.0.min.js:2)
    at Function.ready (jquery-1.8.0.min.js:2)
    at HTMLDocument.D (jquery-1.8.0.min.js:2)
```

**Comment by BrianChapman** [comment]
I had the same problem. Try a hard refresh (clear your cache). That fixed it for me.

**Comment by antorenge** [comment]
Thanks for the tip, though, still not working. 

```
init.js:36 Uncaught ReferenceError: SwaggerUi is not defined
    at HTMLDocument.<anonymous> (init.js:36)
    at k (jquery-1.8.0.min.js:2)
    at Object.fireWith [as resolveWith] (jquery-1.8.0.min.js:2)
    at Function.ready (jquery-1.8.0.min.js:2)
    at HTMLDocument.D (jquery-1.8.0.min.js:2)
```

Do I have to install swagger UI separately?

Since, with ?format=openapi works but ?format=swagger doesn't work.

**Comment by dimm0** [comment]
Same issue
django-rest-swagger 2.1.2
Django 1.10.6

**Comment by marcgibbons** [comment]
Is this happening with DEBUG=True/False ?
Not sure how to recreate this.

**Comment by dimm0** [comment]
DEBUG=True in django, but that error is in browser's javascript console, not in the web page itself. The web page only has a green header, everything else is empty.

**Comment by dimm0** [comment]
<img width="1081" alt="screen shot 2017-03-28 at 1 59 50 pm" src="https://cloud.githubusercontent.com/assets/1425007/24427185/e9bda476-13be-11e7-98ad-2d9d465c5eba.png">

**Comment by marcgibbons** [comment]
I can't recreate this. Does it render here: https://django-rest-swagger.herokuapp.com/ ?
I am in  the process of updating the UI version 3; hopefully this goes away. See #637

**Comment by dimm0** [comment]
Will it help to do the debug here: https://comet-nucleus-dev.sdsc.edu/nucleus/docs/ ?

**Comment by antorenge** [comment]
To solve this make sure you remove all swagger static files generated in static folder. It worked for me.

**Comment by huhu-jin** [comment]
i have this problem too.i remove the static in the package .and  put it again.it works .it is so  wired.
