### ISSUE TITLE
Field with nested object?

### ISSUE THREAD

**Issue by jl-DaDar** [marcgibbons/django-rest-swagger#616]
I can't seem to get nested object to work.

for example, 
```
categories: [
{category object],...
]

I am adding them by doing
```
		coreapi.Field(
			name='categories',
			location='form',
			required=True,
			description='categories',
			type='array',
			schema=schema,

		),
```


where schema is another field list?

is this not supported? How do I let swagger support nested schema?

**Comment by marcgibbons** [comment]
@jl-DaDar Please redirect this issue / question to the CoreAPI project as it is out of scope of this project. Many thanks.
