### ISSUE TITLE
error in url with format

### ISSUE THREAD

**Issue by emacsway** [marcgibbons/django-rest-swagger#617]
I have url conf:

```
urlpatterns = format_suffix_patterns([
    url(r'^retail-size-mapping$', views.RetailSizeMappingListView.as_view()),
], allowed=['json', 'xlsx'])
```
so, it has look:
`^v2/size-mapping/ ^retail-size-mapping\.(?P<format>(json|xlsx))/?$`

In swagger I see:

```
Curl
curl -X GET --header 'Accept: text/html' 'https://api-ivan.joordev.com/v2/size-mapping/retail-size-mapping.xlsx)/'
Request URL
https://api-ivan.joordev.com/v2/size-mapping/retail-size-mapping.xlsx)/
Response Body
```

![image](http://storage2.static.itmages.com/i/17/0215/h_1487121246_6813984_d1c7e0398b.png)

**Comment by marcgibbons** [comment]
@emacsway Do you mind opening an issue on Django REST Framework and if at all possible, provide a failing unit test for this? Many thanks
