### ISSUE TITLE
Nested URLs not displaying correclty

### ISSUE THREAD

**Issue by julienfabre** [marcgibbons/django-rest-swagger#618]
Hello,

I'm trying to document the following endpoints:

_main url conf_
```python
urlpatterns =[
    url(r'^tickers/', include('tickerapi.urls')),
]
```

_and tickerapi/urls:_

```python
schema_view = get_swagger_view(title='Ticker API')

urlpatterns = [
    url(r'^docs/', schema_view),
    url(r'^(?P<channel_name>[-\w]+)/', include([
        url(r'^$', views.ChannelUpdateView.as_view(),name='channel_update'), 
        url(r'^ONAIR$', views.CarouselsOnAirContentList.as_view(),name='carousel_onair_content_list'),      
        url(r'^(?P<carousel_name>[-\w]+)$', views.CarouselUpdateView.as_view(), name='carousel_update'),
    ])),
]
```

As you can see, my url are nested in order to have different views handling the following urls:

- /tickers/{channel_name} (Operations: PUT, PATCH)

- /tickers/{channel_name}/ONAIR (Operations: GET)

- /tickers/{channel_name}/{carousel_name} (Operations: GET, PUT, PATCH)

Only a part of the nested urls are displayed, like so: 

![django_swagger_issue](https://cloud.githubusercontent.com/assets/14291638/22975371/cda424fc-f386-11e6-9f19-e7480054e2c3.JPG)

From what I can understand _/tickers/{channel_name}_ and _/tickers/{channel_name}/{carousel_name}_ is considered to be the same endpoint. Indeed, if I only allow GET operation on the view handling _/tickers/{channel_name}/{carousel_name}_ (using a ListAPIView), the missing nest URL is showing in Swagger, minus the GET operation: 

![django_swagger_issue_2](https://cloud.githubusercontent.com/assets/14291638/22975411/f82a26e0-f386-11e6-8a76-0b59213ca376.JPG)

Thank you

**Comment by marcgibbons** [comment]
@julienfabre Do you mind opening an issue for this on Django REST Framework, and perhaps include a failing test to demonstrate? Introspection / schema generation is handled there. Many thanks!

**Comment by chandanpal** [comment]
@marcgibbons : How did you solved this issue??
