### ISSUE TITLE
'NoneType' object has no attribute 'user'

### ISSUE THREAD

**Issue by BojanKogoj** [marcgibbons/django-rest-swagger#619]
When I call `get_object` inside `get_serializer_context` swagger has no `request`. For example

```python
class SomeView(generics.CreateAPIView):

    def get_object(self):
        pk = self.kwargs.get('id')
        
        try:
            return Something.objects.get(
                pk=pk, owner=self.request.user  # Issue
            )
        except Something.DoesNotExist:
            raise exceptions.NotFound(_('Something does not exist.'))

    def get_serializer_context(self):
        context = super(SomeView, self).get_serializer_context()
        context['something'] = self.get_object()
        return context 
```
This works fine, except for swagger docs. Somehow it doesn't have request and it will throw 
```
AttributeError at /
'NoneType' object has no attribute 'user'

Request Method: GET
Request URL: http://localhost:8000/
Django Version: 1.10.1
Python Executable: ..../bin/python
Python Version: 2.7.10
```

If I try to go around this, and use
```python
user = self.request.user if request else None
```
it will display swagger page, but endpoint request (`?format=openapi`) will fail, throwing 'Something does not exist'

The only solution I have so far is using `get_queryset` instead of `get_object` and using `first()` in serializer, which makes more code than I would like.

Using
> djangorestframework==3.5.4
> django-rest-swagger==2.1.1

**Comment by marcgibbons** [comment]
Where is this exception being raised?
A possibility is that the `request` object is not being passed into your schema generator?

http://www.django-rest-framework.org/api-guide/schemas/#get_schemaself-request

**Comment by BojanKogoj** [comment]
I get the exception whenever I try to use `self.request`, for example `owner=self.request.user`

**Comment by marcgibbons** [comment]
@BojanKogoj How are you instantiating the schema view? Using the shortcut or using your own?

**Comment by ercchy** [comment]
He is using his own view, which is pretty generic:
```
def schema_view(request, format=None):
    generator = SchemaGenerator(title='API Title', patterns=public_apis)
    return Response(generator.get_schema())
```

**Comment by marcgibbons** [comment]
@ercchy @BojanKogoj Thanks. You need to pass in the `request` into the schema generator if your views / serializers depend on it.

e.g.:
`return Response(generator.get_schema(request))`

See: 
http://www.django-rest-framework.org/api-guide/schemas/#get_schemaself-request

> The request argument is optional, and may be used if you want to apply per-user permissions to the resulting schema generation.

**Comment by BojanKogoj** [comment]
@marcgibbons if I pass `request` it doesn't render all endpoints (30 out of 89)

**Comment by marcgibbons** [comment]
Correct, once you pass in the `request` object, the permission classes will be enforced on your endpoints. You'll need to login to view all the endpoints.
