### ISSUE TITLE
Django APIView serializer not being render

### ISSUE THREAD

**Issue by Root-shady** [marcgibbons/django-rest-swagger#620]
I had the following code in my view.py.
```
  class Login(APIView):
    """
    User login, suport username/email password combination authentication
    """
    permission_classes = ([AllowAny,])
    renderer_classes =([JSONRenderer, BrowsableAPIRenderer,])
    serializer_class = LoginSerializer

    def get_serializer_class(self, *args, **kwargs):
        return self.serializer_class

    def post(self, request, format=None):
        context = {}
        serializer = LoginSerializer(data=request.data)
        if serializer.is_valid():
            data = serializer.validated_data
    ...
```

And here is my LoginSerializer definition:
```
class LoginSerializer(serializers.Serializer):
    username =  serializers.CharField(required=True, max_length=100, label='username/email')
    password = serializers.CharField(required=True, max_length=50,
                style={'input_type': 'password'}, label='password')
```

When I follow the documentation and add swagger into my project, everything goes well, except that the serializer fields are not being displayed. I try to add the get_serializer_class method, but nothing happen.

![9 o ao 66d7 r4l h u](https://cloud.githubusercontent.com/assets/9251042/23700647/68f6a63e-042e-11e7-93dd-ffb884e16f96.png)

Using

```
djangorestframework==3.5.4
django-rest-swagger==2.1.1
```

**Comment by marcgibbons** [comment]
@Root-shady The serializer_class attribute only works with GenericAPIView. That may not fit the particular use case of the login, though you could use the user model as the queryset.

Otherwise, you can override the CoreAPI document to add Links to your schema (which then get converted to spec). See:
http://www.django-rest-framework.org/api-guide/schemas/#schemagenerator

**Comment by manuganji** [comment]
I'm using GenericAPIView with a serializer to output a **calculator** output. I believe setting the `serializer_class` on the view should make Swagger generate the fields in the UI right? But it's not rendering any fields. Why is it?

By the way, I'm not creating this View to do anything related to Models.
