### ISSUE TITLE
Not showing comments as function description

### ISSUE THREAD

**Issue by esclkm** [marcgibbons/django-rest-swagger#622]
I cant use python comments to describe my api in swagger
it makes swagger useless
i cant to set description for fields
i cant explain responses

can you help me?
![image](https://cloud.githubusercontent.com/assets/780145/23830544/46c12330-071e-11e7-9281-5d3d016251e0.png)

**Comment by esclkm** [comment]
![image](https://cloud.githubusercontent.com/assets/780145/23830629/6abf2618-0720-11e7-9f12-804380b36043.png)

**Comment by marcgibbons** [comment]
@esclkm Please take a look at the Django REST Framework schemas are. This explains how to annotate your views as well as override the SchemaGenerator with your own.

http://www.django-rest-framework.org/api-guide/schemas/

If you believe there is a bug (i.e. docstring not being picked up for function-based views), please open an issue and a failing test case on the DRF project.

Hope this helps!

**Comment by GaneshGeteres** [comment]
Hi i am also facing the same problem even after the providing the comments in get function.

**Comment by jadedh** [comment]
This thread helped me solved my problem. Here is my solution. Hope it helps!

views.py
```python
class SurgeryView(viewsets.ModelViewSet):
    '''
    This endpoint presents treatment types.

    Try it yourself by setting query parameters surgery_type: **nose**, sub_type **1**,
    '''
    queryset = SurgeryType.objects.all()
    serializer_class = SurgeryTypeSerializer
```
