### ISSUE TITLE
How to use exclude_namespaces 

### ISSUE THREAD

**Issue by nyssance** [marcgibbons/django-rest-swagger#64]
Such as 'exclude_namespaces': ['/users/'] not work
Is there some example?
Thank you.

**Comment by brsbilgic** [comment]
@apelliciari I applied exactly the same approach but it still doesn't exclude the urls properly.  
This is my urls.py

public_apis = patterns('',
    url(r'^api/v2/', include('apps.main.urls')),
)

internal_apis = patterns('',
                         url(r'^api/v2/admin_ext/', include('apps.admin_ext.urls')),
                         )

urlpatterns = patterns('',
                       url(r'^', include(internal_apis, namespace="internals")),
                       url(r'^', include(public_apis, namespace="publics")),
                       url(r'^api/v2/docs/', include('rest_framework_swagger.urls')),
                       url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
                       )


Swagger version is 0.2.6 and django rest 3.0.2. The only difference your from your code piece is when setting urlpatterns parameter. Could you explain why you set it like urlpatterns = urlpatterns + patterns()
Where do you initially set urlpatterns?

**Comment by apelliciari** [comment]
@brsbilgic nothing really special, just definition and some other urls

```python

urlpatterns = []

if 'rosetta' in settings.INSTALLED_APPS:
    urlpatterns = urlpatterns + patterns('',
                                         url(r'^rosetta/', include('rosetta.urls')),
                                         )

```
