### ISSUE TITLE
How to avoid to list POST updates (have only POST inserts)

### ISSUE THREAD

**Issue by apelliciari** [marcgibbons/django-rest-swagger#66]
Hi,

how can I exclude POST updates to my resources?

When i expose a resource for POST method, i get two endpoints:
```
POST /api/resources
POST /api/resources/{pk}
```

how can i avoid to list the second one? 

A concrete example:

http://i.imgur.com/KQPEsAF.png

I use a simple viewset with zero custom definitions

```python
class ReasonViewSet(models.ViewSet):
    """ [comment] """
    serializer_class = ReasonSerializer
```

**Comment by mverteuil** [comment]
You're using a viewset, not a view. You're not using DRF correctly, so that's your issue. :hamburger:
