### ISSUE TITLE
How to comment single mixins method in a viewset for default methods (create, destroy etc..)

### ISSUE THREAD

**Issue by apelliciari** [marcgibbons/django-rest-swagger#67]
Hi,

i would like to customize comments shown in swagger for my viewsets for available actions.

Now i have a docstring on the Viewset 

```python
class ReplyViewSet(ReazioneViewSet):
    """ Replies are free comments to reasons """
    serializer_class = ReplySerializer
```

and the result is http://i.imgur.com/Q7CCfTo.png

I would like to be able to change GET description (for example).

I have successfully added personalized comments for custom action defined with @action decorator, obviously adding docstring for the method.

**But for method inherited from mixins (like create, destroy, list etc), what is the best way to achieve this?**

I've tried overriding the default method, adding the custom docstring and then calling super (like above)

```python
    def create(self, request, *args, **kwargs):
        """ Custom comment """
        super(model.ViewSet, self).create(request, *args, **kwargs)
```

but i get an AssertionError from DRF

**Comment by cancan101** [comment]
:+1:  on seeing something here.

**Comment by humitos** [comment]
I'm having the same issue, any news on this? Thanks!
