### ISSUE TITLE
Add some way to include a high level API description

### ISSUE THREAD

**Issue by decentral1se** [marcgibbons/django-rest-swagger#676]
![image](https://user-images.githubusercontent.com/1991377/28190824-c671f96c-6824-11e7-9396-5fed22285024.png)

I see a `info_description markdown` div but no way to pass this in?

**Comment by oden65** [comment]
A work around for this that I have been using is to override the index.html template file. Not ideal but it gets the job done.

**Comment by lwm** [comment]
Thanks @oden65, I'll give it a shot!
