### ISSUE TITLE
How to add models to swagger?

### ISSUE THREAD

**Issue by ckcollab** [marcgibbons/django-rest-swagger#698]
Hey there! Thanks so much for this project, appreciate all the hard work.

Swagger UI has these nice models on the bottom, it seems:

![image](https://user-images.githubusercontent.com/2185159/29890460-82eadff6-8d7c-11e7-84f8-324282ef1b6c.png)

Using django-rest-swagger, how do I display my models there? Apologies if this is listed somewhere, I noodled around the docs and issues.. didn't see anything. Will happily submit a PR adding these details to docs somewhere!

Thanks for any help.

**Comment by tuffnatty** [comment]
@ckcollab This issue is a duplicate of #583 . Please close it as the maintainer seems to be out of reach.

**Comment by ckcollab** [comment]
Thanks!
