### ISSUE TITLE
JWT Auth and authenticated resources

### ISSUE THREAD

**Issue by TomaszKolek** [marcgibbons/django-rest-swagger#709]
Hey. I do not see any Authenticated resources. My settings:
```
SWAGGER_SETTINGS = {
    'USE_SESSION_AUTH': False,
    'SECURITY_DEFINITIONS': {
        'apiKey': {
            'type': 'apiKey',
            'description': 'Personal API Key authorization',
            'name': 'Authorization',
            'in': 'header',
        }
    },
}

```

When I click on `Authorize` and provide value `JWT <my-token>` I still can only see resources that don't require auth.

When I commented out `permission_classes = (IsAuthenticated,)` I could see the resource with commented permission_classes. What I'm doing wrong?

**Comment by JoshYuJump** [comment]
Same issue here
When `permission_classes = (IsAuthenticated,)` is on, the endpoint is not show in the docs.

**Comment by JoshYuJump** [comment]
My workaround is changed the SECURITY_DEFINITIONS to basic 
```python
'SECURITY_DEFINITIONS': {
    'basic': {
        'type': 'basic',
    }
},
```

And Add basic authentication to DRF settings
```python
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
}
```

**Comment by kaldown** [comment]
Assuming problem solved - could you provide solution, please.

**Comment by ihd2911** [comment]
Same here.
