### ISSUE TITLE
Django 2.0 path URL patterns are not supported

### ISSUE THREAD

**Issue by jacebrowning** [marcgibbons/django-rest-swagger#718]
Django 2.0 (alpha) adds a `path()` utility to build URLs: https://docs.djangoproject.com/en/2.0/ref/urls/#django.urls.path

These seem to cause the Swagger UI to insert backlashes in all routes:

<img width="480" alt="screen shot 2017-11-27 at 8 44 55 pm" src="https://user-images.githubusercontent.com/939501/33298371-f2c46ca2-d3b3-11e7-9c05-050f2d1fe6e0.png">

which results in every click of "Try it out!" returning a 404.

**Comment by y-nakazawa** [comment]
This problem seems to be caused by [DRF](http://www.django-rest-framework.org/).
- django-rest-swagger==2.1.2
- djangorestframework==3.7.3）

where applicable:
- path: rest_framework/schemas/generators.py
- methods: get_api_endpoints()

I coped in this way.

from（Generally it is the 167th line）
```
path_regex = prefix + get_regex_pattern(pattern)
```

to
```
path_regex = (prefix + get_regex_pattern(pattern)).replace("\\", "")
```

Because I think that there is a better method, I want to know it.

**Comment by tarkatronic** [comment]
@y-nakazawa Is there a bug in DRF to track this behavior? Or is there a way it can be worked around it in this package? Either way, there needs to be a way to track that this issue is being worked on.

**Comment by tiltec** [comment]
I'll work on this, probably by submitting a PR to DRF.

**Comment by tiltec** [comment]
Should be fixed in DRF 3.7.4

**Comment by gamedll** [comment]
My config:

djangorestframework==3.7.3
django-rest-swagger==2.1.2
  
    re_path('jwt/api-token-auth/', obtain_jwt_token),
    re_path('jwt/api-token-refresh/', refresh_jwt_token),
    re_path('jwt/api-token-verify/', verify_jwt_token),
    re_path('api-docs/', get_swagger_view(title='Swagger API'), name='swagger_api_docs'),

![1](https://user-images.githubusercontent.com/17548520/34377132-8a59cfc0-eb2a-11e7-90a1-65ff89d26ebb.png)

**Comment by jacebrowning** [comment]
I can confirm that bumping Django REST Framework to 3.7.4 fixes this issue.
