### ISSUE TITLE
Could not work the Swagger UI at django-rest-swagger 2.2.0

### ISSUE THREAD

**Issue by muff1225** [marcgibbons/django-rest-swagger#758]
Would anyone know how to fix this problems?

Shown up this page when accessed get_swagger_view.
![swaggerui](https://user-images.githubusercontent.com/1371233/41200279-a5bfcca4-6cdc-11e8-9954-660c4b8c3904.png)

This is a pip list in my computer.
``` bash
# pip list
Package             Version
------------------- ---------
certifi             2018.4.16
chardet             3.0.4
coreapi             2.3.3
coreschema          0.0.4
Django              2.0.5
django-filter       1.1.0
django-rest-swagger 2.2.0
djangorestframework 3.8.2
idna                2.6
itypes              1.1.0
Jinja2              2.10
MarkupSafe          1.0
openapi-codec       1.3.2
pip                 10.0.1
psycopg2            2.7.4
pytz                2018.4
requests            2.18.4
setuptools          39.0.1
simplejson          3.15.0
uritemplate         3.0.0
urllib3             1.22
uWSGI               2.0.17
wheel               0.31.0
```

This is urls.py.
urls.py
```Python
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework_swagger.views import get_swagger_view

schema_view = get_swagger_view(title='Pastebin API')


urlpatterns = [
    url(r'^$', schema_view),
]
```

**Comment by muff1225** [comment]
My systems could not work swagger UI but it could work generate a swagger format as `https://localhost/?format=openapi`.

**Comment by mattiasa** [comment]
It looks like the browser can't find static files it needs. Are you serving your static files directly through a webserver? If so, you have to run Django's collectstatic management command to copy all the app's static files to the correct location. https://docs.djangoproject.com/en/2.0/ref/contrib/staticfiles/#collectstatic

You can probably see in the browser's inspector that you get a 404 on all the static files.

**Comment by muff1225** [comment]
@mattiasa 
You were right.  
SwaggerUI have ran on my computer after I had added `STATIC_ROOT = os.path.join(BASE_DIR, 'static')` in settings.py and had ran `python manage.py collectstatic`.

I appreciated you.
