### ISSUE TITLE
Django Rest framework swagger base url Https

### ISSUE THREAD

**Issue by meikelwis** [marcgibbons/django-rest-swagger#782]
I have successfully running my rest framework swagger on localhost.. These was my rest framework swagger localhost screenshoot. It has run successfully.

<img width="1440" alt="screen shot 2018-11-02 at 15 32 30" src="https://user-images.githubusercontent.com/19665580/47905958-ced2b980-deba-11e8-8e84-fda9fe6d1e52.png">

Now i want to deploy it on server testing. These is the screenshot result of my testing deployment.

<img width="1434" alt="screen shot 2018-11-02 at 15 36 03" src="https://user-images.githubusercontent.com/19665580/47905979-d8f4b800-deba-11e8-9652-6b30dd5be34b.png">

As you can see the base path changed and served from localhost, the schemes read the right configuration which is https schemes, and the application run in the right domain which is api.executivemafia.com, so that's not problem. The problem come when I want to try the API. The server point is localhost. So it's make my endpoint request become 'https://127.0.0.1:8000/instagram/hello".

My questions are:

Why the rest framework swagger still read localhost although my application already served in https://api.executivemafia.com/docs/? Fyi, I set the proxy pass nginx to locahost:8000 because my gunicorn run on localhost:8000.

Can the base url rest framework swagger testing server using my testing server domain end point ? If it's able to, how to do it?

Any help and reference will be appreciated.
I am using django-rest-swagger version 2.2.0

Thank you Guys!!

Regards,

Meikelwis Wijaya

**Comment by meikelwis** [comment]
Solved by adding these line in my nginx configuration

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Forwarded-Proto $scheme;
      proxy_set_header Host $http_host;
      # we don't want nginx trying to do something clever with
      # redirects, we set the Host: header above already.
      proxy_redirect off;

**Comment by Accpet** [comment]
Have you solved this problem?
