### ISSUE TITLE
all of a sudden  stopped working 

### ISSUE THREAD

**Issue by Joojoo1020** [marcgibbons/django-rest-swagger#792]
It was working fine and I did not change anything related to swagger or any of the APIs, 
and I now get : 

![image](https://user-images.githubusercontent.com/17168374/49694928-7771da00-fb47-11e8-89e3-ab82f042b69a.png)

I would really appreciate any help on this.

**Comment by gjost** [comment]
Your web server cannot find the static files.

**Comment by Joojoo1020** [comment]
I found out that I needed to run : 
       
       python manage collectstatic

after I install the package 
It works now.
