### ISSUE TITLE
Allow parameter documentation to span more than one line in the docstring

### ISSUE THREAD

**Issue by haplo** [marcgibbons/django-rest-swagger#81]
Current version of rest-framework-swagger doesn't allow defining parameters in more than one line, only the first line is displayed.

For example consider this line:

    store_id -- (optional) store number to which restrict the
    search. If this parameter is provided then the available inventory
    for each product will be included in the response.

The current code is splitting the lines and taking only the first one, as it contains "--". Problem is in [introspectors.py:L253](https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/introspectors.py#L253).

I can create a patch for this issue so the whole paragraph of the parameter description is used, removing endlines appropiately.

**Comment by marcgibbons** [comment]
The docstring parameters feature has been deprecated as of v2
