### ISSUE TITLE
How to handle TemplateDoesNotExist

### ISSUE THREAD

**Issue by shravanign** [marcgibbons/django-rest-swagger#825]
I am trying to integrate django-rest-swagger to my already defined APIs, but I am getting TemplateDoesNotExist exception. I have added a screenshot for reference.

![Screenshot from 2020-03-23 14-15-52](https://user-images.githubusercontent.com/32588934/77417487-766fc500-6deb-11ea-9889-41a3d0ed7c4c.png)

Can anyone please help me out?

**Comment by smbasha47** [comment]
Are you using Django 3? if yes in this version Django deprecated staticfiles import in the template.
I am also waiting for this fix

**Comment by shravanign** [comment]
Yes Django 3. Thank you for the information.

**Comment by smbasha47** [comment]
looks like this repo is not active. someone actually fixed this issue sent for merge but it never got merged into master

**Comment by shravanign** [comment]
I have solved the issue using drf-yasg instead of django-rest-swagger. Drf-yasg is a generation from django-rest-swagger.
