### ISSUE TITLE
Issue with reverse-proxied nginx + gunicorn + django setup

### ISSUE THREAD

**Issue by rkishore** [marcgibbons/django-rest-swagger#83]
First off, thanks for this wonderful utility to document APIs. 

I ran into the following issue and was hoping for help/guidance to fix it. When running nginx to reverse-proxy a gunicorn-django backend, I see that rest-framework-swagger uses the proxied backend's absolute URL to access resources/information. Because the proxied backend is not accessible from the client, swagger UI cannot display the information to the client.

Diagrammatically, my setup is as follows:
client ---> nginx (http://example.com:8002) ---> gunicorn-django (http://example.com:8000)

In the case above, rest-framework-swagger tries to access http://example.com:8000 from the client directly. I don't think this is correct behavior. Should it not be using  http://example.com:8002 instead?

Looking into the code, I see the relevant lines of implementation @ https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/views.py#L27

and

https://github.com/marcgibbons/django-rest-swagger/blob/master/rest_framework_swagger/apidocview.py#L10

Since the proxied setup I have is pretty common, was wondering if others have faced this issue and how they solved it? 

I am using django-rest-swagger v0.1.14, nginx/v1.1.19, django v1.5.1, gunicorn v17.5, and django-rest-framework v2.3.13.

**Comment by SebasDesimone** [comment]
Django Rest Swagger calls "request.get_host()" to get the host. This method "returns the HTTP host using the environment or request headers". https://github.com/django/django/blob/master/django/http/request.py#L72

So you could config your Django settings with:

ALLOWED_HOSTS = ['__your_nginx_external_hostname__']
USE_X_FORWARDED_HOST=True
