### ISSUE TITLE
Question: How do I specify a 'root' api path?

### ISSUE THREAD

**Issue by mmedal** [marcgibbons/django-rest-swagger#92]
I have created a new version of an api I provide and would like to auto document it with django_rest_swagger. When following the steps in the README, I am presented with a swagger-ui that has the following structure:

    /api/v1.0
        ...collapsable with flat list of all v1.0 API actions (not separated by view)
    /api/v2.0
        ...collapsable with flat list of all v2.0 API actions (not separated by view)

I would like to only document my v2.0 API in swagger and while I realize that I can exclude my v1.0 using namespaces, I would also like the UI's "collapsing" components to be API-view separated under v2.0, like so:

    v2.0-ApiView1
        ...collapsable with actions provided by ApiView1
    v2.0-ApiView2
        ...collapsable with actions provided by ApiView2

Any tips on how to achieve this?

**Comment by marcgibbons** [comment]
This is now handled by DRF.
